ProgramNode(0...40)(
  [],
  StatementsNode(0...40)(
    [DefNode(0...18)(
       (4...7),
       nil,
       ParametersNode(8...12)(
         [RequiredParameterNode(8...9)(), RequiredParameterNode(11...12)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       nil,
       [IDENTIFIER(8...9)("_")],
       (0...3),
       nil,
       (7...8),
       (12...13),
       nil,
       (15...18)
     ),
     DefNode(20...40)(
       (24...27),
       nil,
       ParametersNode(28...34)(
         [RequiredParameterNode(28...30)(), RequiredParameterNode(32...34)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       nil,
       [IDENTIFIER(28...30)("_a")],
       (20...23),
       nil,
       (27...28),
       (34...35),
       nil,
       (37...40)
     )]
  )
)
