ProgramNode(0...25)(
  [],
  StatementsNode(0...25)(
    [ArrayNode(0...10)(
       [KeywordHashNode(2...8)(
          [AssocNode(2...8)(
             IntegerNode(2...3)(),
             IntegerNode(7...8)(),
             EQUAL_GREATER(4...6)("=>")
           )]
        )],
       BRACKET_LEFT_ARRAY(0...1)("["),
       BRACKET_RIGHT(9...10)("]")
     ),
     ArrayNode(12...25)(
       [IntegerNode(14...15)(),
        KeywordHashNode(17...23)(
          [AssocNode(17...23)(
             IntegerNode(17...18)(),
             IntegerNode(22...23)(),
             EQUAL_GREATER(19...21)("=>")
           )]
        )],
       BRACKET_LEFT_ARRAY(12...13)("["),
       BRACKET_RIGHT(24...25)("]")
     )]
  )
)
