ProgramNode(0...2)(
  ScopeNode(0...0)([]),
  StatementsNode(0...2)(
    [CallNode(0...2)(
       CallNode(1...2)(
         nil,
         nil,
         IDENTIFIER(1...2)("m"),
         nil,
         ArgumentsNode(3...6)(
           [CallNode(3...6)(
              nil,
              nil,
              IDENTIFIER(3...6)("foo"),
              nil,
              nil,
              nil,
              nil,
              "foo"
            )]
         ),
         nil,
         nil,
         "m"
       ),
       nil,
       BANG(0...1)("!"),
       nil,
       nil,
       nil,
       nil,
       "!"
     )]
  )
)
