ProgramNode(0...19)(
  ScopeNode(0...0)([]),
  StatementsNode(0...19)(
    [LambdaNode(0...9)(
       ScopeNode(0...2)([IDENTIFIER(3...8)("scope")]),
       MINUS_GREATER(0...2)("->"),
       PARENTHESIS_LEFT(2...3)("("),
       BlockParametersNode(3...8)(
         ParametersNode(3...8)(
           [RequiredParameterNode(3...8)(IDENTIFIER(3...8)("scope"))],
           [],
           nil,
           [],
           nil,
           nil
         ),
         []
       ),
       PARENTHESIS_RIGHT(8...9)(")"),
       nil
     ),
     CallNode(14...19)(
       nil,
       nil,
       IDENTIFIER(14...19)("scope"),
       nil,
       nil,
       nil,
       nil,
       "scope"
     )]
  )
)
