ProgramNode(0...19)(
  [],
  StatementsNode(0...19)(
    [LambdaNode(0...9)(
       [IDENTIFIER(3...8)("scope")],
       (0...2),
       BlockParametersNode(2...9)(
         ParametersNode(3...8)(
           [RequiredParameterNode(3...8)()],
           [],
           [],
           nil,
           [],
           nil,
           nil
         ),
         [],
         (2...3),
         (8...9)
       ),
       nil
     ),
     CallNode(14...19)(
       nil,
       nil,
       IDENTIFIER(14...19)("scope"),
       nil,
       nil,
       nil,
       nil,
       "scope"
     )]
  )
)
