ProgramNode(0...40)(
  [],
  StatementsNode(0...40)(
    [CaseNode(0...40)(
       CallNode(5...8)(
         nil,
         nil,
         IDENTIFIER(5...8)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       [WhenNode(10...25)(
          (10...14),
          [StringNode(15...20)((15...16), (16...19), (19...20), "bar")],
          StatementsNode(22...25)(
            [CallNode(22...25)(
               nil,
               nil,
               IDENTIFIER(22...25)("bar"),
               nil,
               nil,
               nil,
               nil,
               "bar"
             )]
          )
        )],
       ElseNode(27...40)(
         (27...31),
         StatementsNode(32...35)(
           [CallNode(32...35)(
              nil,
              nil,
              IDENTIFIER(32...35)("baz"),
              nil,
              nil,
              nil,
              nil,
              "baz"
            )]
         ),
         (37...40)
       ),
       (0...4),
       (37...40)
     )]
  )
)
