ProgramNode(0...30)(
  [],
  StatementsNode(0...30)(
    [CaseNode(0...30)(
       CallNode(5...8)(
         nil,
         nil,
         IDENTIFIER(5...8)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       [WhenNode(10...25)(
          (10...14),
          [StringNode(15...20)((15...16), (16...19), (19...20), "bar")],
          StatementsNode(22...25)(
            [CallNode(22...25)(
               nil,
               nil,
               IDENTIFIER(22...25)("bar"),
               nil,
               nil,
               nil,
               nil,
               "bar"
             )]
          )
        )],
       nil,
       (0...4),
       (27...30)
     )]
  )
)
