ProgramNode(0...16)(
  [],
  StatementsNode(0...16)(
    [BeginNode(0...16)(
       (0...5),
       nil,
       nil,
       nil,
       EnsureNode(6...16)(
         KEYWORD_ENSURE(6...12)("ensure"),
         nil,
         KEYWORD_END(13...16)("end")
       ),
       (13...16)
     )]
  )
)
