ProgramNode(0...29)(
  [],
  StatementsNode(0...29)(
    [BeginNode(0...29)(
       (0...5),
       StatementsNode(7...11)(
         [CallNode(7...11)(
            nil,
            nil,
            IDENTIFIER(7...11)("meth"),
            nil,
            nil,
            nil,
            nil,
            "meth"
          )]
       ),
       nil,
       nil,
       EnsureNode(13...29)(
         (13...19),
         StatementsNode(21...24)(
           [CallNode(21...24)(
              nil,
              nil,
              IDENTIFIER(21...24)("bar"),
              nil,
              nil,
              nil,
              nil,
              "bar"
            )]
         ),
         (26...29)
       ),
       (26...29)
     )]
  )
)
