ProgramNode(2...15)(
  ScopeNode(0...0)([]),
  StatementsNode(2...15)(
    [HashNode(2...15)(
       BRACE_LEFT(0...1)("{"),
       [AssocNode(2...8)(
          SymbolNode(2...6)(
            nil,
            LABEL(2...5)("foo"),
            LABEL_END(5...6)(":"),
            "foo"
          ),
          IntegerNode(7...8)((7...8), 10),
          nil
        ),
        AssocSplatNode(10...15)(
          CallNode(12...15)(
            nil,
            nil,
            IDENTIFIER(12...15)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          ),
          (10...12)
        )],
       BRACE_RIGHT(16...17)("}")
     )]
  )
)
