ProgramNode(0...38)(
  [],
  StatementsNode(0...38)(
    [IfNode(0...38)(
       (0...2),
       CallNode(3...6)(
         nil,
         nil,
         IDENTIFIER(3...6)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       StatementsNode(8...11)(
         [CallNode(8...11)(
            nil,
            nil,
            IDENTIFIER(8...11)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       IfNode(13...25)(
         (13...18),
         CallNode(19...22)(
           nil,
           nil,
           IDENTIFIER(19...22)("baz"),
           nil,
           nil,
           nil,
           nil,
           "baz"
         ),
         StatementsNode(24...25)([IntegerNode(24...25)()]),
         ElseNode(27...38)(
           (27...31),
           StatementsNode(32...33)([IntegerNode(32...33)()]),
           (35...38)
         ),
         nil
       ),
       (35...38)
     )]
  )
)
