ProgramNode(0...10)(
  [],
  StatementsNode(0...10)(
    [IfNode(0...10)(
       (4...6),
       CallNode(7...10)(
         nil,
         nil,
         IDENTIFIER(7...10)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       StatementsNode(0...3)(
         [CallNode(0...3)(
            nil,
            nil,
            IDENTIFIER(0...3)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )]
       ),
       nil,
       nil
     )]
  )
)
