ProgramNode(0...17)(
  [],
  StatementsNode(0...17)(
    [DefNode(0...17)(
       IDENTIFIER(4...5)("f"),
       nil,
       ParametersNode(6...11)(
         [],
         [],
         [],
         nil,
         [],
         KeywordRestParameterNode(6...11)((6...8), (8...11)),
         nil
       ),
       nil,
       [IDENTIFIER(8...11)("foo")],
       (0...3),
       nil,
       (5...6),
       (11...12),
       nil,
       (14...17)
     )]
  )
)
