ProgramNode(0...0)(
  ScopeNode(0...0)(
    [IDENTIFIER(12...13)("c"),
     IDENTIFIER(15...16)("d"),
     IDENTIFIER(25...26)("b"),
     IDENTIFIER(67...68)("a")]
  ),
  StatementsNode(0...0)(
    [MultiWriteNode(0...7)(
       [SplatNode(0...1)(USTAR(0...1)("*"), nil)],
       EQUAL(2...3)("="),
       CallNode(4...7)(
         nil,
         nil,
         IDENTIFIER(4...7)("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       ),
       nil,
       nil
     ),
     MultiWriteNode(9...22)(
       [MultiWriteNode(9...10)(
          [SplatNode(9...10)(USTAR(9...10)("*"), nil)],
          nil,
          nil,
          nil,
          nil
        ),
        LocalVariableWriteNode(12...13)(IDENTIFIER(12...13)("c"), nil, nil),
        LocalVariableWriteNode(15...16)(IDENTIFIER(15...16)("d"), nil, nil)],
       EQUAL(17...18)("="),
       CallNode(19...22)(
         nil,
         nil,
         IDENTIFIER(19...22)("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       ),
       nil,
       nil
     ),
     MultiWriteNode(24...32)(
       [SplatNode(24...26)(
          USTAR(24...25)("*"),
          LocalVariableWriteNode(25...26)(IDENTIFIER(25...26)("b"), nil, nil)
        )],
       EQUAL(27...28)("="),
       CallNode(29...32)(
         nil,
         nil,
         IDENTIFIER(29...32)("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       ),
       nil,
       nil
     ),
     MultiWriteNode(34...45)(
       [MultiWriteNode(34...36)(
          [SplatNode(34...36)(
             USTAR(34...35)("*"),
             LocalVariableWriteNode(35...36)(
               IDENTIFIER(35...36)("b"),
               nil,
               nil
             )
           )],
          nil,
          nil,
          nil,
          nil
        ),
        LocalVariableWriteNode(38...39)(IDENTIFIER(38...39)("c"), nil, nil)],
       EQUAL(40...41)("="),
       CallNode(42...45)(
         nil,
         nil,
         IDENTIFIER(42...45)("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       ),
       nil,
       nil
     ),
     MultiWriteNode(47...65)(
       [InstanceVariableWriteNode(47...51)((47...51), nil, nil),
        ClassVariableWriteNode(53...58)((53...58), nil, nil)],
       EQUAL(59...60)("="),
       SplatNode(61...65)(
         USTAR(61...62)("*"),
         CallNode(62...65)(
           nil,
           nil,
           IDENTIFIER(62...65)("foo"),
           nil,
           nil,
           nil,
           nil,
           "foo"
         )
       ),
       nil,
       nil
     ),
     MultiWriteNode(67...77)(
       [LocalVariableWriteNode(67...68)(IDENTIFIER(67...68)("a"), nil, nil),
        SplatNode(70...71)(USTAR(70...71)("*"), nil)],
       EQUAL(72...73)("="),
       CallNode(74...77)(
         nil,
         nil,
         IDENTIFIER(74...77)("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       ),
       nil,
       nil
     ),
     MultiWriteNode(79...92)(
       [LocalVariableWriteNode(79...80)(IDENTIFIER(79...80)("a"), nil, nil),
        SplatNode(82...83)(USTAR(82...83)("*"), nil),
        LocalVariableWriteNode(85...86)(IDENTIFIER(85...86)("c"), nil, nil)],
       EQUAL(87...88)("="),
       CallNode(89...92)(
         nil,
         nil,
         IDENTIFIER(89...92)("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       ),
       nil,
       nil
     ),
     MultiWriteNode(94...105)(
       [LocalVariableWriteNode(94...95)(IDENTIFIER(94...95)("a"), nil, nil),
        SplatNode(97...99)(
          USTAR(97...98)("*"),
          LocalVariableWriteNode(98...99)(IDENTIFIER(98...99)("b"), nil, nil)
        )],
       EQUAL(100...101)("="),
       CallNode(102...105)(
         nil,
         nil,
         IDENTIFIER(102...105)("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       ),
       nil,
       nil
     ),
     MultiWriteNode(107...121)(
       [LocalVariableWriteNode(107...108)(
          IDENTIFIER(107...108)("a"),
          nil,
          nil
        ),
        SplatNode(110...112)(
          USTAR(110...111)("*"),
          LocalVariableWriteNode(111...112)(
            IDENTIFIER(111...112)("b"),
            nil,
            nil
          )
        ),
        LocalVariableWriteNode(114...115)(
          IDENTIFIER(114...115)("c"),
          nil,
          nil
        )],
       EQUAL(116...117)("="),
       CallNode(118...121)(
         nil,
         nil,
         IDENTIFIER(118...121)("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       ),
       nil,
       nil
     ),
     MultiWriteNode(123...0)(
       [LocalVariableWriteNode(123...124)(
          IDENTIFIER(123...124)("a"),
          nil,
          nil
        ),
        LocalVariableWriteNode(126...127)(
          IDENTIFIER(126...127)("b"),
          nil,
          nil
        )],
       EQUAL(128...129)("="),
       ArrayNode(0...0)(
         [SplatNode(130...134)(
            USTAR(130...131)("*"),
            CallNode(131...134)(
              nil,
              nil,
              IDENTIFIER(131...134)("foo"),
              nil,
              nil,
              nil,
              nil,
              "foo"
            )
          ),
          CallNode(136...139)(
            nil,
            nil,
            IDENTIFIER(136...139)("bar"),
            nil,
            nil,
            nil,
            nil,
            "bar"
          )],
         nil,
         nil
       ),
       nil,
       nil
     )]
  )
)
