ProgramNode(0...12)(
  [IDENTIFIER(0...1)("m")],
  StatementsNode(0...12)(
    [LocalVariableWriteNode(0...12)(
       (0...1),
       LambdaNode(4...12)(
         [IDENTIFIER(8...12)("args")],
         (4...6),
         BlockParametersNode(7...12)(
           ParametersNode(7...12)(
             [],
             [],
             [],
             RestParameterNode(7...12)((7...8), (8...12)),
             [],
             nil,
             nil
           ),
           [],
           nil,
           nil
         ),
         nil
       ),
       (2...3),
       0
     )]
  )
)
