ProgramNode(0...11)(
  [],
  StatementsNode(0...11)(
    [LambdaNode(0...11)(
       [:arg],
       (0...2),
       BlockParametersNode(3...11)(
         ParametersNode(4...10)(
           [],
           [OptionalParameterNode(4...10)(
              :arg,
              (4...7),
              (7...8),
              HashNode(8...10)((8...9), [], (9...10))
            )],
           [],
           nil,
           [],
           nil,
           nil
         ),
         [],
         (3...4),
         (10...11)
       ),
       nil
     )]
  )
)
