ProgramNode(0...6)(
  ScopeNode(0...0)([IDENTIFIER(0...1)("m")]),
  StatementsNode(0...6)(
    [LocalVariableWriteNode(0...6)(
       (0...1),
       LambdaNode(4...6)(
         ScopeNode(4...6)([IDENTIFIER(8...12)("args")]),
         MINUS_GREATER(4...6)("->"),
         nil,
         BlockParametersNode(7...12)(
           ParametersNode(7...12)(
             [],
             [],
             RestParameterNode(7...12)(
               STAR(7...8)("*"),
               IDENTIFIER(8...12)("args")
             ),
             [],
             nil,
             nil
           ),
           []
         ),
         nil,
         nil
       ),
       (2...3),
       0
     )]
  )
)
