ProgramNode(0...11)(
  ScopeNode(0...0)([]),
  StatementsNode(0...11)(
    [LambdaNode(0...11)(
       ScopeNode(0...2)([IDENTIFIER(4...7)("arg")]),
       MINUS_GREATER(0...2)("->"),
       PARENTHESIS_LEFT(3...4)("("),
       BlockParametersNode(4...9)(
         ParametersNode(4...9)(
           [],
           [OptionalParameterNode(4...9)(
              IDENTIFIER(4...7)("arg"),
              EQUAL(7...8)("="),
              HashNode(8...9)(
                BRACE_LEFT(8...9)("{"),
                [],
                BRACE_RIGHT(9...10)("}")
              )
            )],
           [],
           nil,
           [],
           nil,
           nil
         ),
         []
       ),
       PARENTHESIS_RIGHT(10...11)(")"),
       nil
     )]
  )
)
