ProgramNode(0...12)(
  [:m],
  StatementsNode(0...12)(
    [LocalVariableWriteNode(0...12)(
       :m,
       0,
       LambdaNode(4...12)(
         [:args],
         (4...6),
         BlockParametersNode(7...12)(
           ParametersNode(7...12)(
             [],
             [],
             [],
             RestParameterNode(7...12)((7...8), (8...12)),
             [],
             nil,
             nil
           ),
           [],
           nil,
           nil
         ),
         nil
       ),
       (0...1),
       (2...3)
     )]
  )
)
