ProgramNode(0...32)(
  ScopeNode(0...0)([]),
  StatementsNode(0...32)(
    [CallNode(0...18)(
       nil,
       nil,
       IDENTIFIER(0...1)("m"),
       nil,
       nil,
       nil,
       BlockNode(2...18)(
         ScopeNode(2...3)(
           [IDENTIFIER(6...9)("foo"), IDENTIFIER(11...14)("bar")]
         ),
         BlockParametersNode(6...15)(
           ParametersNode(6...15)(
             [RequiredDestructuredParameterNode(6...15)(
                [RequiredParameterNode(6...9)(),
                 RequiredParameterNode(11...14)()],
                PARENTHESIS_LEFT(5...6)("("),
                PARENTHESIS_RIGHT(14...15)(")")
              )],
             [],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         nil,
         (2...3),
         (17...18)
       ),
       "m"
     ),
     CallNode(21...32)(
       nil,
       nil,
       IDENTIFIER(21...22)("m"),
       nil,
       nil,
       nil,
       BlockNode(23...32)(
         ScopeNode(23...24)([IDENTIFIER(26...29)("foo")]),
         BlockParametersNode(26...29)(
           ParametersNode(26...29)(
             [RequiredParameterNode(26...29)()],
             [],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         nil,
         (23...24),
         (31...32)
       ),
       "m"
     )]
  )
)
