ProgramNode(0...29)(
  [],
  StatementsNode(0...29)(
    [BeginNode(0...29)(
       (0...5),
       StatementsNode(7...11)(
         [CallNode(7...11)(
            nil,
            nil,
            IDENTIFIER(7...11)("meth"),
            nil,
            nil,
            nil,
            nil,
            "meth"
          )]
       ),
       RescueNode(13...24)(
         (13...19),
         [],
         nil,
         nil,
         StatementsNode(21...24)(
           [CallNode(21...24)(
              nil,
              nil,
              IDENTIFIER(21...24)("foo"),
              nil,
              nil,
              nil,
              nil,
              "foo"
            )]
         ),
         nil
       ),
       nil,
       nil,
       (26...29)
     )]
  )
)
