ProgramNode(0...21)(
  [:foo],
  StatementsNode(0...21)(
    [LocalVariableWriteNode(0...21)(
       :foo,
       0,
       RescueModifierNode(6...21)(
         CallNode(6...10)(
           nil,
           nil,
           IDENTIFIER(6...10)("meth"),
           nil,
           nil,
           nil,
           nil,
           "meth"
         ),
         (11...17),
         CallNode(18...21)(
           nil,
           nil,
           IDENTIFIER(18...21)("bar"),
           nil,
           nil,
           nil,
           nil,
           "bar"
         )
       ),
       (0...3),
       (4...5)
     )]
  )
)
