ProgramNode(0...40)(
  [],
  StatementsNode(0...40)(
    [BeginNode(0...40)(
       (0...5),
       StatementsNode(7...11)(
         [CallNode(7...11)(
            nil,
            nil,
            IDENTIFIER(7...11)("meth"),
            nil,
            nil,
            nil,
            nil,
            "meth"
          )]
       ),
       RescueNode(13...24)(
         (13...19),
         [],
         nil,
         nil,
         StatementsNode(21...24)(
           [CallNode(21...24)(
              nil,
              nil,
              IDENTIFIER(21...24)("foo"),
              nil,
              nil,
              nil,
              nil,
              "foo"
            )]
         ),
         nil
       ),
       ElseNode(26...40)(
         (26...30),
         StatementsNode(32...35)(
           [CallNode(32...35)(
              nil,
              nil,
              IDENTIFIER(32...35)("bar"),
              nil,
              nil,
              nil,
              nil,
              "bar"
            )]
         ),
         (37...40)
       ),
       nil,
       (37...40)
     )]
  )
)
