ProgramNode(0...42)(
  [],
  StatementsNode(0...42)(
    [BeginNode(0...42)(
       (0...5),
       StatementsNode(7...11)(
         [CallNode(7...11)(
            nil,
            nil,
            IDENTIFIER(7...11)("meth"),
            nil,
            nil,
            nil,
            nil,
            "meth"
          )]
       ),
       RescueNode(13...24)(
         (13...19),
         [],
         nil,
         nil,
         StatementsNode(21...24)(
           [CallNode(21...24)(
              nil,
              nil,
              IDENTIFIER(21...24)("baz"),
              nil,
              nil,
              nil,
              nil,
              "baz"
            )]
         ),
         nil
       ),
       nil,
       EnsureNode(26...42)(
         (26...32),
         StatementsNode(34...37)(
           [CallNode(34...37)(
              nil,
              nil,
              IDENTIFIER(34...37)("bar"),
              nil,
              nil,
              nil,
              nil,
              "bar"
            )]
         ),
         (39...42)
       ),
       (39...42)
     )]
  )
)
