ProgramNode(0...21)(
  ScopeNode(0...0)([IDENTIFIER(0...3)("foo")]),
  StatementsNode(0...21)(
    [RescueModifierNode(0...21)(
       LocalVariableWriteNode(0...10)(
         (0...3),
         CallNode(6...10)(
           nil,
           nil,
           IDENTIFIER(6...10)("meth"),
           nil,
           nil,
           nil,
           nil,
           "meth"
         ),
         (4...5),
         0
       ),
       KEYWORD_RESCUE_MODIFIER(11...17)("rescue"),
       CallNode(18...21)(
         nil,
         nil,
         IDENTIFIER(18...21)("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       )
     )]
  )
)
