ProgramNode(0...13)(
  [],
  StatementsNode(0...13)(
    [DefNode(0...13)(
       IDENTIFIER(4...5)("f"),
       nil,
       ParametersNode(6...7)(
         [],
         [],
         [],
         RestParameterNode(6...7)((6...7), nil),
         [],
         nil,
         nil
       ),
       nil,
       [USTAR(6...7)("*")],
       (0...3),
       nil,
       (5...6),
       (7...8),
       nil,
       (10...13)
     )]
  )
)
