ProgramNode(0...17)(
  [],
  StatementsNode(0...17)(
    [LambdaNode(0...6)(
       [IDENTIFIER(4...5)("a")],
       (0...2),
       BlockParametersNode(3...6)(
         ParametersNode(4...5)(
           [RequiredParameterNode(4...5)()],
           [],
           [],
           nil,
           [],
           nil,
           nil
         ),
         [],
         (3...4),
         (5...6)
       ),
       nil
     ),
     LambdaNode(12...17)(
       [IDENTIFIER(15...16)("a")],
       (12...14),
       BlockParametersNode(14...17)(
         ParametersNode(15...16)(
           [RequiredParameterNode(15...16)()],
           [],
           [],
           nil,
           [],
           nil,
           nil
         ),
         [],
         (14...15),
         (16...17)
       ),
       nil
     )]
  )
)
