ProgramNode(0...17)(
  ScopeNode(0...0)([]),
  StatementsNode(0...17)(
    [LambdaNode(0...6)(
       ScopeNode(0...2)([IDENTIFIER(4...5)("a")]),
       MINUS_GREATER(0...2)("->"),
       PARENTHESIS_LEFT(3...4)("("),
       BlockParametersNode(4...5)(
         ParametersNode(4...5)(
           [RequiredParameterNode(4...5)()],
           [],
           [],
           nil,
           [],
           nil,
           nil
         ),
         []
       ),
       PARENTHESIS_RIGHT(5...6)(")"),
       nil
     ),
     LambdaNode(12...17)(
       ScopeNode(12...14)([IDENTIFIER(15...16)("a")]),
       MINUS_GREATER(12...14)("->"),
       PARENTHESIS_LEFT(14...15)("("),
       BlockParametersNode(15...16)(
         ParametersNode(15...16)(
           [RequiredParameterNode(15...16)()],
           [],
           [],
           nil,
           [],
           nil,
           nil
         ),
         []
       ),
       PARENTHESIS_RIGHT(16...17)(")"),
       nil
     )]
  )
)
