ProgramNode(0...3)(
  ScopeNode(0...0)([]),
  StatementsNode(0...3)(
    [CallNode(0...3)(
       nil,
       nil,
       IDENTIFIER(0...3)("fun"),
       nil,
       ArgumentsNode(4...8)(
         [ParenthesesNode(4...8)(
            StatementsNode(5...6)([IntegerNode(5...6)((5...6), 10)]),
            (4...5),
            (7...8)
          )]
       ),
       nil,
       nil,
       "fun"
     )]
  )
)
