ProgramNode(0...3)(
  ScopeNode(0...0)([]),
  StatementsNode(0...3)(
    [CallNode(0...3)(
       nil,
       nil,
       IDENTIFIER(0...3)("fun"),
       nil,
       ArgumentsNode(4...12)(
         [CallNode(4...12)(
            ParenthesesNode(4...7)(
              StatementsNode(5...6)([IntegerNode(5...6)((5...6), 10)]),
              (4...5),
              (6...7)
            ),
            DOT(7...8)("."),
            IDENTIFIER(8...12)("to_i"),
            nil,
            nil,
            nil,
            nil,
            "to_i"
          )]
       ),
       nil,
       nil,
       "fun"
     )]
  )
)
