ProgramNode(0...8)(
  ScopeNode(0...0)([]),
  StatementsNode(0...8)(
    [SourceFileNode(0...8)(
       KEYWORD___FILE__(0...8)("__FILE__"),
       "/fixtures/whitequark/string___FILE__.rb"
     )]
  )
)
