ProgramNode(4...11)(
  [],
  StatementsNode(4...11)(
    [IfNode(4...11)(
       (4...5),
       CallNode(0...3)(
         nil,
         nil,
         IDENTIFIER(0...3)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       StatementsNode(6...7)([IntegerNode(6...7)()]),
       ElseNode(8...11)(
         (8...9),
         StatementsNode(10...11)([IntegerNode(10...11)()]),
         nil
       ),
       nil
     )]
  )
)
