ProgramNode(0...14)(
  [],
  StatementsNode(0...14)(
    [UntilNode(0...14)(
       (5...10),
       CallNode(11...14)(
         nil,
         nil,
         IDENTIFIER(11...14)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       StatementsNode(0...4)(
         [CallNode(0...4)(
            nil,
            nil,
            IDENTIFIER(0...4)("meth"),
            nil,
            nil,
            nil,
            nil,
            "meth"
          )]
       )
     )]
  )
)
