ProgramNode(5...4)(
  ScopeNode(0...0)([]),
  StatementsNode(5...4)(
    [UntilNode(5...4)(
       KEYWORD_UNTIL_MODIFIER(5...10)("until"),
       CallNode(11...14)(
         nil,
         nil,
         IDENTIFIER(11...14)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       StatementsNode(0...4)(
         [CallNode(0...4)(
            nil,
            nil,
            IDENTIFIER(0...4)("meth"),
            nil,
            nil,
            nil,
            nil,
            "meth"
          )]
       )
     )]
  )
)
