ProgramNode(0...43)(
  [],
  StatementsNode(0...43)(
    [CaseNode(0...43)(
       CallNode(5...8)(
         nil,
         nil,
         IDENTIFIER(5...8)("foo"),
         nil,
         nil,
         nil,
         nil,
         "foo"
       ),
       [WhenNode(10...27)(
          (10...14),
          [IntegerNode(15...16)(),
           SplatNode(18...22)(
             (18...19),
             CallNode(19...22)(
               nil,
               nil,
               IDENTIFIER(19...22)("baz"),
               nil,
               nil,
               nil,
               nil,
               "baz"
             )
           )],
          StatementsNode(24...27)(
            [CallNode(24...27)(
               nil,
               nil,
               IDENTIFIER(24...27)("bar"),
               nil,
               nil,
               nil,
               nil,
               "bar"
             )]
          )
        ),
        WhenNode(29...38)(
          (29...33),
          [SplatNode(34...38)(
             (34...35),
             CallNode(35...38)(
               nil,
               nil,
               IDENTIFIER(35...38)("foo"),
               nil,
               nil,
               nil,
               nil,
               "foo"
             )
           )],
          nil
        )],
       nil,
       (0...4),
       (40...43)
     )]
  )
)
