# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.3.5", engine: "truffleruby", engine_version: "~> 24.2.0"

gemspec path: "../.."

gem "parser"
gem "rake"
gem "rake-compiler"
gem "test-unit"
