# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.3.7", engine: "truffleruby", engine_version: "~> 25.0.0"

gemspec path: "../.."

gem "parser"
gem "rake"
gem "rake-compiler"
gem "ruby_parser"
gem "test-unit"
