# frozen_string_literal: true

source "https://rubygems.org"

gem "minitest"
gem "parser"
gem "rake-compiler"
gem "rake"
gem "rbs"
gem "ruby_parser"
gem "sorbet"
gem "steep", ">= 1.7.0.dev.1"
gem "tapioca"
gem "test-unit"
