# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.0.0"

gemspec path: "../.."

gem "ffi"
gem "parser"
gem "rake"
gem "rake-compiler"
gem "rbs"
gem "ruby_memcheck"
gem "test-unit"
