/******************************************************************************/
/* This file is generated by the bin/template script and should not be        */
/* modified manually.                                                         */
/******************************************************************************/

#include "token_type_gen.h"
#include <string.h>

const char *
token_type_to_str(yp_token_type_t token_type) {
  switch (token_type) {
    case YP_TOKEN_EOF:
      return "EOF";
    case YP_TOKEN_INVALID:
      return "INVALID";
    case YP_TOKEN_AMPERSAND:
      return "AMPERSAND";
    case YP_TOKEN_AMPERSAND_AMPERSAND:
      return "AMPERSAND_AMPERSAND";
    case YP_TOKEN_AMPERSAND_AMPERSAND_EQUAL:
      return "AMPERSAND_AMPERSAND_EQUAL";
    case YP_TOKEN_AMPERSAND_EQUAL:
      return "AMPERSAND_EQUAL";
    case YP_TOKEN_BACK_REFERENCE:
      return "BACK_REFERENCE";
    case YP_TOKEN_BACKTICK:
      return "BACKTICK";
    case YP_TOKEN_BANG:
      return "BANG";
    case YP_TOKEN_BANG_AT:
      return "BANG_AT";
    case YP_TOKEN_BANG_EQUAL:
      return "BANG_EQUAL";
    case YP_TOKEN_BANG_TILDE:
      return "BANG_TILDE";
    case YP_TOKEN_BRACE_LEFT:
      return "BRACE_LEFT";
    case YP_TOKEN_BRACE_RIGHT:
      return "BRACE_RIGHT";
    case YP_TOKEN_BRACKET_LEFT:
      return "BRACKET_LEFT";
    case YP_TOKEN_BRACKET_LEFT_RIGHT:
      return "BRACKET_LEFT_RIGHT";
    case YP_TOKEN_BRACKET_RIGHT:
      return "BRACKET_RIGHT";
    case YP_TOKEN_CARET:
      return "CARET";
    case YP_TOKEN_CARET_EQUAL:
      return "CARET_EQUAL";
    case YP_TOKEN_CHARACTER_LITERAL:
      return "CHARACTER_LITERAL";
    case YP_TOKEN_CLASS_VARIABLE:
      return "CLASS_VARIABLE";
    case YP_TOKEN_COLON:
      return "COLON";
    case YP_TOKEN_COLON_COLON:
      return "COLON_COLON";
    case YP_TOKEN_COMMA:
      return "COMMA";
    case YP_TOKEN_COMMENT:
      return "COMMENT";
    case YP_TOKEN_CONSTANT:
      return "CONSTANT";
    case YP_TOKEN_DOT:
      return "DOT";
    case YP_TOKEN_DOT_DOT:
      return "DOT_DOT";
    case YP_TOKEN_DOT_DOT_DOT:
      return "DOT_DOT_DOT";
    case YP_TOKEN_EMBDOC_BEGIN:
      return "EMBDOC_BEGIN";
    case YP_TOKEN_EMBDOC_END:
      return "EMBDOC_END";
    case YP_TOKEN_EMBDOC_LINE:
      return "EMBDOC_LINE";
    case YP_TOKEN_EMBEXPR_BEGIN:
      return "EMBEXPR_BEGIN";
    case YP_TOKEN_EMBEXPR_END:
      return "EMBEXPR_END";
    case YP_TOKEN_EQUAL:
      return "EQUAL";
    case YP_TOKEN_EQUAL_EQUAL:
      return "EQUAL_EQUAL";
    case YP_TOKEN_EQUAL_EQUAL_EQUAL:
      return "EQUAL_EQUAL_EQUAL";
    case YP_TOKEN_EQUAL_GREATER:
      return "EQUAL_GREATER";
    case YP_TOKEN_EQUAL_TILDE:
      return "EQUAL_TILDE";
    case YP_TOKEN_FLOAT:
      return "FLOAT";
    case YP_TOKEN_GREATER:
      return "GREATER";
    case YP_TOKEN_GREATER_EQUAL:
      return "GREATER_EQUAL";
    case YP_TOKEN_GREATER_GREATER:
      return "GREATER_GREATER";
    case YP_TOKEN_GREATER_GREATER_EQUAL:
      return "GREATER_GREATER_EQUAL";
    case YP_TOKEN_GLOBAL_VARIABLE:
      return "GLOBAL_VARIABLE";
    case YP_TOKEN_IDENTIFIER:
      return "IDENTIFIER";
    case YP_TOKEN_IMAGINARY_NUMBER:
      return "IMAGINARY_NUMBER";
    case YP_TOKEN_INSTANCE_VARIABLE:
      return "INSTANCE_VARIABLE";
    case YP_TOKEN_INTEGER:
      return "INTEGER";
    case YP_TOKEN_KEYWORD___ENCODING__:
      return "KEYWORD___ENCODING__";
    case YP_TOKEN_KEYWORD___LINE__:
      return "KEYWORD___LINE__";
    case YP_TOKEN_KEYWORD___FILE__:
      return "KEYWORD___FILE__";
    case YP_TOKEN_KEYWORD_ALIAS:
      return "KEYWORD_ALIAS";
    case YP_TOKEN_KEYWORD_AND:
      return "KEYWORD_AND";
    case YP_TOKEN_KEYWORD_BEGIN:
      return "KEYWORD_BEGIN";
    case YP_TOKEN_KEYWORD_BEGIN_UPCASE:
      return "KEYWORD_BEGIN_UPCASE";
    case YP_TOKEN_KEYWORD_BREAK:
      return "KEYWORD_BREAK";
    case YP_TOKEN_KEYWORD_CASE:
      return "KEYWORD_CASE";
    case YP_TOKEN_KEYWORD_CLASS:
      return "KEYWORD_CLASS";
    case YP_TOKEN_KEYWORD_DEF:
      return "KEYWORD_DEF";
    case YP_TOKEN_KEYWORD_DEFINED:
      return "KEYWORD_DEFINED";
    case YP_TOKEN_KEYWORD_DO:
      return "KEYWORD_DO";
    case YP_TOKEN_KEYWORD_ELSE:
      return "KEYWORD_ELSE";
    case YP_TOKEN_KEYWORD_ELSIF:
      return "KEYWORD_ELSIF";
    case YP_TOKEN_KEYWORD_END:
      return "KEYWORD_END";
    case YP_TOKEN_KEYWORD_END_UPCASE:
      return "KEYWORD_END_UPCASE";
    case YP_TOKEN_KEYWORD_ENSURE:
      return "KEYWORD_ENSURE";
    case YP_TOKEN_KEYWORD_FALSE:
      return "KEYWORD_FALSE";
    case YP_TOKEN_KEYWORD_FOR:
      return "KEYWORD_FOR";
    case YP_TOKEN_KEYWORD_IF:
      return "KEYWORD_IF";
    case YP_TOKEN_KEYWORD_IN:
      return "KEYWORD_IN";
    case YP_TOKEN_KEYWORD_MODULE:
      return "KEYWORD_MODULE";
    case YP_TOKEN_KEYWORD_NEXT:
      return "KEYWORD_NEXT";
    case YP_TOKEN_KEYWORD_NIL:
      return "KEYWORD_NIL";
    case YP_TOKEN_KEYWORD_NOT:
      return "KEYWORD_NOT";
    case YP_TOKEN_KEYWORD_OR:
      return "KEYWORD_OR";
    case YP_TOKEN_KEYWORD_REDO:
      return "KEYWORD_REDO";
    case YP_TOKEN_KEYWORD_RESCUE:
      return "KEYWORD_RESCUE";
    case YP_TOKEN_KEYWORD_RETRY:
      return "KEYWORD_RETRY";
    case YP_TOKEN_KEYWORD_RETURN:
      return "KEYWORD_RETURN";
    case YP_TOKEN_KEYWORD_SELF:
      return "KEYWORD_SELF";
    case YP_TOKEN_KEYWORD_SUPER:
      return "KEYWORD_SUPER";
    case YP_TOKEN_KEYWORD_THEN:
      return "KEYWORD_THEN";
    case YP_TOKEN_KEYWORD_TRUE:
      return "KEYWORD_TRUE";
    case YP_TOKEN_KEYWORD_UNDEF:
      return "KEYWORD_UNDEF";
    case YP_TOKEN_KEYWORD_UNLESS:
      return "KEYWORD_UNLESS";
    case YP_TOKEN_KEYWORD_UNTIL:
      return "KEYWORD_UNTIL";
    case YP_TOKEN_KEYWORD_WHEN:
      return "KEYWORD_WHEN";
    case YP_TOKEN_KEYWORD_WHILE:
      return "KEYWORD_WHILE";
    case YP_TOKEN_KEYWORD_YIELD:
      return "KEYWORD_YIELD";
    case YP_TOKEN_LABEL:
      return "LABEL";
    case YP_TOKEN_LAMBDA_BEGIN:
      return "LAMBDA_BEGIN";
    case YP_TOKEN_LESS:
      return "LESS";
    case YP_TOKEN_LESS_EQUAL:
      return "LESS_EQUAL";
    case YP_TOKEN_LESS_EQUAL_GREATER:
      return "LESS_EQUAL_GREATER";
    case YP_TOKEN_LESS_LESS:
      return "LESS_LESS";
    case YP_TOKEN_LESS_LESS_EQUAL:
      return "LESS_LESS_EQUAL";
    case YP_TOKEN_MINUS:
      return "MINUS";
    case YP_TOKEN_MINUS_AT:
      return "MINUS_AT";
    case YP_TOKEN_MINUS_EQUAL:
      return "MINUS_EQUAL";
    case YP_TOKEN_MINUS_GREATER:
      return "MINUS_GREATER";
    case YP_TOKEN_NEWLINE:
      return "NEWLINE";
    case YP_TOKEN_NTH_REFERENCE:
      return "NTH_REFERENCE";
    case YP_TOKEN_PARENTHESIS_LEFT:
      return "PARENTHESIS_LEFT";
    case YP_TOKEN_PARENTHESIS_RIGHT:
      return "PARENTHESIS_RIGHT";
    case YP_TOKEN_PERCENT:
      return "PERCENT";
    case YP_TOKEN_PERCENT_EQUAL:
      return "PERCENT_EQUAL";
    case YP_TOKEN_PERCENT_LOWER_I:
      return "PERCENT_LOWER_I";
    case YP_TOKEN_PERCENT_LOWER_W:
      return "PERCENT_LOWER_W";
    case YP_TOKEN_PERCENT_LOWER_X:
      return "PERCENT_LOWER_X";
    case YP_TOKEN_PERCENT_UPPER_I:
      return "PERCENT_UPPER_I";
    case YP_TOKEN_PERCENT_UPPER_W:
      return "PERCENT_UPPER_W";
    case YP_TOKEN_PIPE:
      return "PIPE";
    case YP_TOKEN_PIPE_EQUAL:
      return "PIPE_EQUAL";
    case YP_TOKEN_PIPE_PIPE:
      return "PIPE_PIPE";
    case YP_TOKEN_PIPE_PIPE_EQUAL:
      return "PIPE_PIPE_EQUAL";
    case YP_TOKEN_PLUS:
      return "PLUS";
    case YP_TOKEN_PLUS_AT:
      return "PLUS_AT";
    case YP_TOKEN_PLUS_EQUAL:
      return "PLUS_EQUAL";
    case YP_TOKEN_QUESTION_MARK:
      return "QUESTION_MARK";
    case YP_TOKEN_RATIONAL_NUMBER:
      return "RATIONAL_NUMBER";
    case YP_TOKEN_REGEXP_BEGIN:
      return "REGEXP_BEGIN";
    case YP_TOKEN_REGEXP_END:
      return "REGEXP_END";
    case YP_TOKEN_SEMICOLON:
      return "SEMICOLON";
    case YP_TOKEN_SLASH:
      return "SLASH";
    case YP_TOKEN_SLASH_EQUAL:
      return "SLASH_EQUAL";
    case YP_TOKEN_STAR:
      return "STAR";
    case YP_TOKEN_STAR_EQUAL:
      return "STAR_EQUAL";
    case YP_TOKEN_STAR_STAR:
      return "STAR_STAR";
    case YP_TOKEN_STAR_STAR_EQUAL:
      return "STAR_STAR_EQUAL";
    case YP_TOKEN_STRING_BEGIN:
      return "STRING_BEGIN";
    case YP_TOKEN_STRING_CONTENT:
      return "STRING_CONTENT";
    case YP_TOKEN_STRING_END:
      return "STRING_END";
    case YP_TOKEN_SYMBOL_BEGIN:
      return "SYMBOL_BEGIN";
    case YP_TOKEN_TILDE:
      return "TILDE";
    case YP_TOKEN_TILDE_AT:
      return "TILDE_AT";
    case YP_TOKEN_WORDS_SEP:
      return "WORDS_SEP";
    case YP_TOKEN_MAXIMUM:
      return "MAXIMUM";
  }
}

yp_token_type_t
token_type_from_str(const char *str) {
  if (strncmp(str, "AMPERSAND_AMPERSAND_EQUAL", 25) == 0) return YP_TOKEN_AMPERSAND_AMPERSAND_EQUAL;
  if (strncmp(str, "AMPERSAND_AMPERSAND", 19) == 0) return YP_TOKEN_AMPERSAND_AMPERSAND;
  if (strncmp(str, "AMPERSAND_EQUAL", 15) == 0) return YP_TOKEN_AMPERSAND_EQUAL;
  if (strncmp(str, "AMPERSAND", 9) == 0) return YP_TOKEN_AMPERSAND;
  if (strncmp(str, "BACK_REFERENCE", 14) == 0) return YP_TOKEN_BACK_REFERENCE;
  if (strncmp(str, "BACKTICK", 8) == 0) return YP_TOKEN_BACKTICK;
  if (strncmp(str, "BANG_AT", 7) == 0) return YP_TOKEN_BANG_AT;
  if (strncmp(str, "BANG_EQUAL", 10) == 0) return YP_TOKEN_BANG_EQUAL;
  if (strncmp(str, "BANG_TILDE", 10) == 0) return YP_TOKEN_BANG_TILDE;
  if (strncmp(str, "BANG", 4) == 0) return YP_TOKEN_BANG;
  if (strncmp(str, "BRACE_LEFT", 10) == 0) return YP_TOKEN_BRACE_LEFT;
  if (strncmp(str, "BRACE_RIGHT", 11) == 0) return YP_TOKEN_BRACE_RIGHT;
  if (strncmp(str, "BRACKET_LEFT_RIGHT", 18) == 0) return YP_TOKEN_BRACKET_LEFT_RIGHT;
  if (strncmp(str, "BRACKET_LEFT", 12) == 0) return YP_TOKEN_BRACKET_LEFT;
  if (strncmp(str, "BRACKET_RIGHT", 13) == 0) return YP_TOKEN_BRACKET_RIGHT;
  if (strncmp(str, "CARET_EQUAL", 11) == 0) return YP_TOKEN_CARET_EQUAL;
  if (strncmp(str, "CARET", 5) == 0) return YP_TOKEN_CARET;
  if (strncmp(str, "CHARACTER_LITERAL", 17) == 0) return YP_TOKEN_CHARACTER_LITERAL;
  if (strncmp(str, "CLASS_VARIABLE", 14) == 0) return YP_TOKEN_CLASS_VARIABLE;
  if (strncmp(str, "COLON_COLON", 11) == 0) return YP_TOKEN_COLON_COLON;
  if (strncmp(str, "COLON", 5) == 0) return YP_TOKEN_COLON;
  if (strncmp(str, "COMMA", 5) == 0) return YP_TOKEN_COMMA;
  if (strncmp(str, "COMMENT", 7) == 0) return YP_TOKEN_COMMENT;
  if (strncmp(str, "CONSTANT", 8) == 0) return YP_TOKEN_CONSTANT;
  if (strncmp(str, "DOT_DOT_DOT", 11) == 0) return YP_TOKEN_DOT_DOT_DOT;
  if (strncmp(str, "DOT_DOT", 7) == 0) return YP_TOKEN_DOT_DOT;
  if (strncmp(str, "DOT", 3) == 0) return YP_TOKEN_DOT;
  if (strncmp(str, "EMBDOC_BEGIN", 12) == 0) return YP_TOKEN_EMBDOC_BEGIN;
  if (strncmp(str, "EMBDOC_END", 10) == 0) return YP_TOKEN_EMBDOC_END;
  if (strncmp(str, "EMBDOC_LINE", 11) == 0) return YP_TOKEN_EMBDOC_LINE;
  if (strncmp(str, "EMBEXPR_BEGIN", 13) == 0) return YP_TOKEN_EMBEXPR_BEGIN;
  if (strncmp(str, "EMBEXPR_END", 11) == 0) return YP_TOKEN_EMBEXPR_END;
  if (strncmp(str, "EOF", 3) == 0) return YP_TOKEN_EOF;
  if (strncmp(str, "EQUAL_EQUAL_EQUAL", 17) == 0) return YP_TOKEN_EQUAL_EQUAL_EQUAL;
  if (strncmp(str, "EQUAL_EQUAL", 11) == 0) return YP_TOKEN_EQUAL_EQUAL;
  if (strncmp(str, "EQUAL_GREATER", 13) == 0) return YP_TOKEN_EQUAL_GREATER;
  if (strncmp(str, "EQUAL_TILDE", 11) == 0) return YP_TOKEN_EQUAL_TILDE;
  if (strncmp(str, "EQUAL", 5) == 0) return YP_TOKEN_EQUAL;
  if (strncmp(str, "FLOAT", 5) == 0) return YP_TOKEN_FLOAT;
  if (strncmp(str, "GLOBAL_VARIABLE", 15) == 0) return YP_TOKEN_GLOBAL_VARIABLE;
  if (strncmp(str, "GREATER_EQUAL", 13) == 0) return YP_TOKEN_GREATER_EQUAL;
  if (strncmp(str, "GREATER_GREATER_EQUAL", 21) == 0) return YP_TOKEN_GREATER_GREATER_EQUAL;
  if (strncmp(str, "GREATER_GREATER", 15) == 0) return YP_TOKEN_GREATER_GREATER;
  if (strncmp(str, "GREATER", 7) == 0) return YP_TOKEN_GREATER;
  if (strncmp(str, "IDENTIFIER", 10) == 0) return YP_TOKEN_IDENTIFIER;
  if (strncmp(str, "IMAGINARY_NUMBER", 16) == 0) return YP_TOKEN_IMAGINARY_NUMBER;
  if (strncmp(str, "INSTANCE_VARIABLE", 17) == 0) return YP_TOKEN_INSTANCE_VARIABLE;
  if (strncmp(str, "INTEGER", 7) == 0) return YP_TOKEN_INTEGER;
  if (strncmp(str, "INVALID", 7) == 0) return YP_TOKEN_INVALID;
  if (strncmp(str, "KEYWORD___ENCODING__", 20) == 0) return YP_TOKEN_KEYWORD___ENCODING__;
  if (strncmp(str, "KEYWORD___FILE__", 16) == 0) return YP_TOKEN_KEYWORD___FILE__;
  if (strncmp(str, "KEYWORD___LINE__", 16) == 0) return YP_TOKEN_KEYWORD___LINE__;
  if (strncmp(str, "KEYWORD_ALIAS", 13) == 0) return YP_TOKEN_KEYWORD_ALIAS;
  if (strncmp(str, "KEYWORD_AND", 11) == 0) return YP_TOKEN_KEYWORD_AND;
  if (strncmp(str, "KEYWORD_BEGIN_UPCASE", 20) == 0) return YP_TOKEN_KEYWORD_BEGIN_UPCASE;
  if (strncmp(str, "KEYWORD_BEGIN", 13) == 0) return YP_TOKEN_KEYWORD_BEGIN;
  if (strncmp(str, "KEYWORD_BREAK", 13) == 0) return YP_TOKEN_KEYWORD_BREAK;
  if (strncmp(str, "KEYWORD_CASE", 12) == 0) return YP_TOKEN_KEYWORD_CASE;
  if (strncmp(str, "KEYWORD_CLASS", 13) == 0) return YP_TOKEN_KEYWORD_CLASS;
  if (strncmp(str, "KEYWORD_DEF", 11) == 0) return YP_TOKEN_KEYWORD_DEF;
  if (strncmp(str, "KEYWORD_DEFINED", 15) == 0) return YP_TOKEN_KEYWORD_DEFINED;
  if (strncmp(str, "KEYWORD_DO", 10) == 0) return YP_TOKEN_KEYWORD_DO;
  if (strncmp(str, "KEYWORD_ELSE", 12) == 0) return YP_TOKEN_KEYWORD_ELSE;
  if (strncmp(str, "KEYWORD_ELSIF", 13) == 0) return YP_TOKEN_KEYWORD_ELSIF;
  if (strncmp(str, "KEYWORD_END_UPCASE", 18) == 0) return YP_TOKEN_KEYWORD_END_UPCASE;
  if (strncmp(str, "KEYWORD_END", 11) == 0) return YP_TOKEN_KEYWORD_END;
  if (strncmp(str, "KEYWORD_ENSURE", 14) == 0) return YP_TOKEN_KEYWORD_ENSURE;
  if (strncmp(str, "KEYWORD_FALSE", 13) == 0) return YP_TOKEN_KEYWORD_FALSE;
  if (strncmp(str, "KEYWORD_FOR", 11) == 0) return YP_TOKEN_KEYWORD_FOR;
  if (strncmp(str, "KEYWORD_IF", 10) == 0) return YP_TOKEN_KEYWORD_IF;
  if (strncmp(str, "KEYWORD_IN", 10) == 0) return YP_TOKEN_KEYWORD_IN;
  if (strncmp(str, "KEYWORD_MODULE", 14) == 0) return YP_TOKEN_KEYWORD_MODULE;
  if (strncmp(str, "KEYWORD_NEXT", 12) == 0) return YP_TOKEN_KEYWORD_NEXT;
  if (strncmp(str, "KEYWORD_NIL", 11) == 0) return YP_TOKEN_KEYWORD_NIL;
  if (strncmp(str, "KEYWORD_NOT", 11) == 0) return YP_TOKEN_KEYWORD_NOT;
  if (strncmp(str, "KEYWORD_OR", 10) == 0) return YP_TOKEN_KEYWORD_OR;
  if (strncmp(str, "KEYWORD_REDO", 12) == 0) return YP_TOKEN_KEYWORD_REDO;
  if (strncmp(str, "KEYWORD_RESCUE", 14) == 0) return YP_TOKEN_KEYWORD_RESCUE;
  if (strncmp(str, "KEYWORD_RETRY", 13) == 0) return YP_TOKEN_KEYWORD_RETRY;
  if (strncmp(str, "KEYWORD_RETURN", 14) == 0) return YP_TOKEN_KEYWORD_RETURN;
  if (strncmp(str, "KEYWORD_SELF", 12) == 0) return YP_TOKEN_KEYWORD_SELF;
  if (strncmp(str, "KEYWORD_SUPER", 13) == 0) return YP_TOKEN_KEYWORD_SUPER;
  if (strncmp(str, "KEYWORD_THEN", 12) == 0) return YP_TOKEN_KEYWORD_THEN;
  if (strncmp(str, "KEYWORD_TRUE", 12) == 0) return YP_TOKEN_KEYWORD_TRUE;
  if (strncmp(str, "KEYWORD_UNDEF", 13) == 0) return YP_TOKEN_KEYWORD_UNDEF;
  if (strncmp(str, "KEYWORD_UNLESS", 14) == 0) return YP_TOKEN_KEYWORD_UNLESS;
  if (strncmp(str, "KEYWORD_UNTIL", 13) == 0) return YP_TOKEN_KEYWORD_UNTIL;
  if (strncmp(str, "KEYWORD_WHEN", 12) == 0) return YP_TOKEN_KEYWORD_WHEN;
  if (strncmp(str, "KEYWORD_WHILE", 13) == 0) return YP_TOKEN_KEYWORD_WHILE;
  if (strncmp(str, "KEYWORD_YIELD", 13) == 0) return YP_TOKEN_KEYWORD_YIELD;
  if (strncmp(str, "LABEL", 5) == 0) return YP_TOKEN_LABEL;
  if (strncmp(str, "LAMBDA_BEGIN", 12) == 0) return YP_TOKEN_LAMBDA_BEGIN;
  if (strncmp(str, "LESS_EQUAL_GREATER", 18) == 0) return YP_TOKEN_LESS_EQUAL_GREATER;
  if (strncmp(str, "LESS_EQUAL", 10) == 0) return YP_TOKEN_LESS_EQUAL;
  if (strncmp(str, "LESS_LESS_EQUAL", 15) == 0) return YP_TOKEN_LESS_LESS_EQUAL;
  if (strncmp(str, "LESS_LESS", 9) == 0) return YP_TOKEN_LESS_LESS;
  if (strncmp(str, "LESS", 4) == 0) return YP_TOKEN_LESS;
  if (strncmp(str, "MINUS_AT", 8) == 0) return YP_TOKEN_MINUS_AT;
  if (strncmp(str, "MINUS_EQUAL", 11) == 0) return YP_TOKEN_MINUS_EQUAL;
  if (strncmp(str, "MINUS_GREATER", 13) == 0) return YP_TOKEN_MINUS_GREATER;
  if (strncmp(str, "MINUS", 5) == 0) return YP_TOKEN_MINUS;
  if (strncmp(str, "NEWLINE", 7) == 0) return YP_TOKEN_NEWLINE;
  if (strncmp(str, "NTH_REFERENCE", 13) == 0) return YP_TOKEN_NTH_REFERENCE;
  if (strncmp(str, "PARENTHESIS_LEFT", 16) == 0) return YP_TOKEN_PARENTHESIS_LEFT;
  if (strncmp(str, "PARENTHESIS_RIGHT", 17) == 0) return YP_TOKEN_PARENTHESIS_RIGHT;
  if (strncmp(str, "PERCENT_EQUAL", 13) == 0) return YP_TOKEN_PERCENT_EQUAL;
  if (strncmp(str, "PERCENT_LOWER_I", 15) == 0) return YP_TOKEN_PERCENT_LOWER_I;
  if (strncmp(str, "PERCENT_LOWER_W", 15) == 0) return YP_TOKEN_PERCENT_LOWER_W;
  if (strncmp(str, "PERCENT_LOWER_X", 15) == 0) return YP_TOKEN_PERCENT_LOWER_X;
  if (strncmp(str, "PERCENT_UPPER_I", 15) == 0) return YP_TOKEN_PERCENT_UPPER_I;
  if (strncmp(str, "PERCENT_UPPER_W", 15) == 0) return YP_TOKEN_PERCENT_UPPER_W;
  if (strncmp(str, "PERCENT", 7) == 0) return YP_TOKEN_PERCENT;
  if (strncmp(str, "PIPE_EQUAL", 10) == 0) return YP_TOKEN_PIPE_EQUAL;
  if (strncmp(str, "PIPE_PIPE_EQUAL", 15) == 0) return YP_TOKEN_PIPE_PIPE_EQUAL;
  if (strncmp(str, "PIPE_PIPE", 9) == 0) return YP_TOKEN_PIPE_PIPE;
  if (strncmp(str, "PIPE", 4) == 0) return YP_TOKEN_PIPE;
  if (strncmp(str, "PLUS_AT", 7) == 0) return YP_TOKEN_PLUS_AT;
  if (strncmp(str, "PLUS_EQUAL", 10) == 0) return YP_TOKEN_PLUS_EQUAL;
  if (strncmp(str, "PLUS", 4) == 0) return YP_TOKEN_PLUS;
  if (strncmp(str, "QUESTION_MARK", 13) == 0) return YP_TOKEN_QUESTION_MARK;
  if (strncmp(str, "RATIONAL_NUMBER", 15) == 0) return YP_TOKEN_RATIONAL_NUMBER;
  if (strncmp(str, "REGEXP_BEGIN", 12) == 0) return YP_TOKEN_REGEXP_BEGIN;
  if (strncmp(str, "REGEXP_END", 10) == 0) return YP_TOKEN_REGEXP_END;
  if (strncmp(str, "SEMICOLON", 9) == 0) return YP_TOKEN_SEMICOLON;
  if (strncmp(str, "SLASH_EQUAL", 11) == 0) return YP_TOKEN_SLASH_EQUAL;
  if (strncmp(str, "SLASH", 5) == 0) return YP_TOKEN_SLASH;
  if (strncmp(str, "STAR_EQUAL", 10) == 0) return YP_TOKEN_STAR_EQUAL;
  if (strncmp(str, "STAR_STAR_EQUAL", 15) == 0) return YP_TOKEN_STAR_STAR_EQUAL;
  if (strncmp(str, "STAR_STAR", 9) == 0) return YP_TOKEN_STAR_STAR;
  if (strncmp(str, "STAR", 4) == 0) return YP_TOKEN_STAR;
  if (strncmp(str, "STRING_BEGIN", 12) == 0) return YP_TOKEN_STRING_BEGIN;
  if (strncmp(str, "STRING_CONTENT", 14) == 0) return YP_TOKEN_STRING_CONTENT;
  if (strncmp(str, "STRING_END", 10) == 0) return YP_TOKEN_STRING_END;
  if (strncmp(str, "SYMBOL_BEGIN", 12) == 0) return YP_TOKEN_SYMBOL_BEGIN;
  if (strncmp(str, "TILDE_AT", 8) == 0) return YP_TOKEN_TILDE_AT;
  if (strncmp(str, "TILDE", 5) == 0) return YP_TOKEN_TILDE;
  if (strncmp(str, "WORDS_SEP", 9) == 0) return YP_TOKEN_WORDS_SEP;
  // Fallback
  return YP_TOKEN_INVALID;
}
