# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "yarp"
  spec.version = "0.4.0"
  spec.authors = ["Shopify"]
  spec.email = ["ruby@shopify.com"]

  spec.summary = "Yet Another Ruby Parser"
  spec.homepage = "https://github.com/ruby/yarp"
  spec.license = "MIT"

  spec.require_paths = ["lib"]
  spec.files = [
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "LICENSE.md",
    "README.md",
    "config.yml",
    "docs/building.md",
    "docs/configuration.md",
    "docs/design.md",
    "docs/encoding.md",
    "docs/extension.md",
    "docs/fuzzing.md",
    "docs/heredocs.md",
    "docs/mapping.md",
    "docs/ripper.md",
    "docs/serialization.md",
    "docs/testing.md",
    "ext/yarp/api_node.c",
    "ext/yarp/api_pack.c",
    "ext/yarp/extension.c",
    "ext/yarp/extension.h",
    "ext/yarp/include/yarp.h",
    "ext/yarp/include/yarp/ast.h",
    "ext/yarp/include/yarp/defines.h",
    "ext/yarp/include/yarp/diagnostic.h",
    "ext/yarp/include/yarp/enc/yp_encoding.h",
    "ext/yarp/include/yarp/node.h",
    "ext/yarp/include/yarp/pack.h",
    "ext/yarp/include/yarp/parser.h",
    "ext/yarp/include/yarp/regexp.h",
    "ext/yarp/include/yarp/unescape.h",
    "ext/yarp/include/yarp/util/yp_buffer.h",
    "ext/yarp/include/yarp/util/yp_char.h",
    "ext/yarp/include/yarp/util/yp_constant_pool.h",
    "ext/yarp/include/yarp/util/yp_list.h",
    "ext/yarp/include/yarp/util/yp_memchr.h",
    "ext/yarp/include/yarp/util/yp_newline_list.h",
    "ext/yarp/include/yarp/util/yp_state_stack.h",
    "ext/yarp/include/yarp/util/yp_string.h",
    "ext/yarp/include/yarp/util/yp_string_list.h",
    "ext/yarp/include/yarp/util/yp_strpbrk.h",
    "ext/yarp/include/yarp/version.h",
    "ext/yarp/src-diagnostic.c",
    "ext/yarp/src-enc-ascii.c",
    "ext/yarp/src-enc-big5.c",
    "ext/yarp/src-enc-euc_jp.c",
    "ext/yarp/src-enc-gbk.c",
    "ext/yarp/src-enc-iso_8859_10.c",
    "ext/yarp/src-enc-iso_8859_11.c",
    "ext/yarp/src-enc-iso_8859_13.c",
    "ext/yarp/src-enc-iso_8859_14.c",
    "ext/yarp/src-enc-iso_8859_15.c",
    "ext/yarp/src-enc-iso_8859_16.c",
    "ext/yarp/src-enc-iso_8859_1.c",
    "ext/yarp/src-enc-iso_8859_2.c",
    "ext/yarp/src-enc-iso_8859_3.c",
    "ext/yarp/src-enc-iso_8859_4.c",
    "ext/yarp/src-enc-iso_8859_5.c",
    "ext/yarp/src-enc-iso_8859_6.c",
    "ext/yarp/src-enc-iso_8859_7.c",
    "ext/yarp/src-enc-iso_8859_8.c",
    "ext/yarp/src-enc-iso_8859_9.c",
    "ext/yarp/src-enc-koi8_r.c",
    "ext/yarp/src-enc-shared.c",
    "ext/yarp/src-enc-shift_jis.c",
    "ext/yarp/src-enc-unicode.c",
    "ext/yarp/src-enc-windows_1251.c",
    "ext/yarp/src-enc-windows_1252.c",
    "ext/yarp/src-enc-windows_31j.c",
    "ext/yarp/src-node.c",
    "ext/yarp/src-pack.c",
    "ext/yarp/src-prettyprint.c",
    "ext/yarp/src-regexp.c",
    "ext/yarp/src-serialize.c",
    "ext/yarp/src-token_type.c",
    "ext/yarp/src-unescape.c",
    "ext/yarp/src-util-yp_buffer.c",
    "ext/yarp/src-util-yp_char.c",
    "ext/yarp/src-util-yp_constant_pool.c",
    "ext/yarp/src-util-yp_list.c",
    "ext/yarp/src-util-yp_memchr.c",
    "ext/yarp/src-util-yp_newline_list.c",
    "ext/yarp/src-util-yp_state_stack.c",
    "ext/yarp/src-util-yp_string.c",
    "ext/yarp/src-util-yp_string_list.c",
    "ext/yarp/src-util-yp_strncasecmp.c",
    "ext/yarp/src-util-yp_strpbrk.c",
    "ext/yarp/src-yarp.c",
    "lib/yarp.rb",
    "lib/yarp/lex_compat.rb",
    "lib/yarp/node.rb",
    "lib/yarp/pack.rb",
    "lib/yarp/ripper_compat.rb",
    "lib/yarp/serialize.rb",
    "yarp.gemspec",
  ]

  spec.extensions = ["ext/yarp/extconf.rb"]
  spec.metadata["allowed_push_host"] = "https://rubygems.org"
end
