ProgramNode(0...76)(
  ScopeNode(0...0)([]),
  StatementsNode(0...76)(
    [CallNode(0...6)(
       nil,
       nil,
       IDENTIFIER(0...6)("public"),
       nil,
       nil,
       nil,
       nil,
       "public"
     ),
     DefNode(7...33)(
       IDENTIFIER(11...18)("printer"),
       nil,
       nil,
       StatementsNode(20...24)(
         [CallNode(20...24)(
            nil,
            nil,
            IDENTIFIER(20...24)("puts"),
            nil,
            ArgumentsNode(25...29)([SelfNode(25...29)()]),
            nil,
            nil,
            "puts"
          )]
       ),
       ScopeNode(7...10)([]),
       (7...10),
       nil,
       nil,
       nil,
       nil,
       (30...33)
     ),
     AliasNode(34...48)(
       SymbolNode(39...41)(nil, UPLUS(39...41)("+@"), nil, "+@"),
       SymbolNode(41...48)(
         nil,
         IDENTIFIER(41...48)("printer"),
         nil,
         "printer"
       ),
       (34...39)
     ),
     AndNode(52...76)(
       CallNode(52...63)(
         IntegerNode(52...53)(),
         nil,
         LESS(53...54)("<"),
         nil,
         ArgumentsNode(54...63)([IntegerNode(54...63)()]),
         nil,
         nil,
         "<"
       ),
       CallNode(66...76)(
         StringNode(67...76)(
           STRING_BEGIN(67...68)("\""),
           STRING_CONTENT(68...75)("yippeee"),
           STRING_END(75...76)("\""),
           "yippeee"
         ),
         nil,
         UPLUS(66...67)("+"),
         nil,
         nil,
         nil,
         nil,
         "+@"
       ),
       KEYWORD_AND(63...66)("and")
     )]
  )
)
