ProgramNode(72...1516)(
  ScopeNode(0...0)([IDENTIFIER(1251...1252)("s")]),
  StatementsNode(72...1516)(
    [DefNode(72...99)(
       IDENTIFIER(76...80)("toss"),
       nil,
       nil,
       StatementsNode(82...95)(
         [CallNode(82...95)(
            CallNode(82...89)(
              nil,
              nil,
              IDENTIFIER(82...86)("rand"),
              PARENTHESIS_LEFT(86...87)("("),
              ArgumentsNode(87...88)([IntegerNode(87...88)()]),
              PARENTHESIS_RIGHT(88...89)(")"),
              nil,
              "rand"
            ),
            DOT(89...90)("."),
            IDENTIFIER(90...95)("zero?"),
            nil,
            nil,
            nil,
            nil,
            "zero?"
          )]
       ),
       ScopeNode(72...75)([]),
       (72...75),
       nil,
       nil,
       nil,
       nil,
       (96...99)
     ),
     ClassNode(101...203)(
       ScopeNode(101...106)([]),
       KEYWORD_CLASS(101...106)("class"),
       ConstantReadNode(107...113)(),
       nil,
       nil,
       StatementsNode(115...199)(
         [DefNode(115...199)(
            IDENTIFIER(119...133)("randomize_case"),
            nil,
            nil,
            StatementsNode(136...194)(
              [CallNode(136...194)(
                 CallNode(136...189)(
                   CallNode(136...145)(
                     nil,
                     nil,
                     IDENTIFIER(136...141)("split"),
                     PARENTHESIS_LEFT(141...142)("("),
                     ArgumentsNode(142...144)(
                       [StringNode(142...144)(
                          STRING_BEGIN(142...143)("'"),
                          STRING_CONTENT(143...143)(""),
                          STRING_END(143...144)("'"),
                          ""
                        )]
                     ),
                     PARENTHESIS_RIGHT(144...145)(")"),
                     nil,
                     "split"
                   ),
                   DOT(145...146)("."),
                   IDENTIFIER(146...149)("map"),
                   nil,
                   nil,
                   nil,
                   BlockNode(150...189)(
                     ScopeNode(150...152)([IDENTIFIER(154...155)("c")]),
                     BlockParametersNode(153...156)(
                       ParametersNode(154...155)(
                         [RequiredParameterNode(154...155)()],
                         [],
                         [],
                         nil,
                         [],
                         nil,
                         nil
                       ),
                       [],
                       (153...154),
                       (155...156)
                     ),
                     StatementsNode(162...185)(
                       [IfNode(162...185)(
                          QUESTION_MARK(162...163)("?"),
                          CallNode(157...161)(
                            nil,
                            nil,
                            IDENTIFIER(157...161)("toss"),
                            nil,
                            nil,
                            nil,
                            nil,
                            "toss"
                          ),
                          StatementsNode(164...172)(
                            [CallNode(164...172)(
                               LocalVariableReadNode(164...165)(0),
                               DOT(165...166)("."),
                               IDENTIFIER(166...172)("upcase"),
                               nil,
                               nil,
                               nil,
                               nil,
                               "upcase"
                             )]
                          ),
                          ElseNode(173...185)(
                            COLON(173...174)(":"),
                            StatementsNode(175...185)(
                              [CallNode(175...185)(
                                 LocalVariableReadNode(175...176)(0),
                                 DOT(176...177)("."),
                                 IDENTIFIER(177...185)("downcase"),
                                 nil,
                                 nil,
                                 nil,
                                 nil,
                                 "downcase"
                               )]
                            ),
                            nil
                          ),
                          nil
                        )]
                     ),
                     (150...152),
                     (186...189)
                   ),
                   "map"
                 ),
                 DOT(189...190)("."),
                 IDENTIFIER(190...194)("join"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "join"
               )]
            ),
            ScopeNode(115...118)([]),
            (115...118),
            nil,
            nil,
            nil,
            nil,
            (196...199)
          )]
       ),
       KEYWORD_END(200...203)("end")
     ),
     ModuleNode(205...892)(
       ScopeNode(205...211)([]),
       KEYWORD_MODULE(205...211)("module"),
       ConstantReadNode(212...218)(),
       StatementsNode(220...888)(
         [ConstantPathWriteNode(220...282)(
            ConstantReadNode(220...233)(),
            EQUAL(234...235)("="),
            ArrayNode(236...282)(
              [StringNode(239...244)(
                 nil,
                 STRING_CONTENT(239...244)("serif"),
                 nil,
                 "serif"
               ),
               StringNode(245...255)(
                 nil,
                 STRING_CONTENT(245...255)("sans-serif"),
                 nil,
                 "sans-serif"
               ),
               StringNode(256...263)(
                 nil,
                 STRING_CONTENT(256...263)("cursive"),
                 nil,
                 "cursive"
               ),
               StringNode(264...271)(
                 nil,
                 STRING_CONTENT(264...271)("fantasy"),
                 nil,
                 "fantasy"
               ),
               StringNode(272...281)(
                 nil,
                 STRING_CONTENT(272...281)("monospace"),
                 nil,
                 "monospace"
               )],
              PERCENT_LOWER_W(236...239)("%w("),
              STRING_END(281...282)(")")
            )
          ),
          DefNode(286...339)(
            IDENTIFIER(295...305)("rand_color"),
            SelfNode(290...294)(),
            nil,
            StatementsNode(308...334)(
              [CallNode(308...334)(
                 StringNode(308...313)(
                   STRING_BEGIN(308...309)("'"),
                   STRING_CONTENT(309...312)("#%x"),
                   STRING_END(312...313)("'"),
                   "#%x"
                 ),
                 nil,
                 PERCENT(314...315)("%"),
                 nil,
                 ArgumentsNode(316...334)(
                   [CallNode(316...334)(
                      nil,
                      nil,
                      IDENTIFIER(316...320)("rand"),
                      PARENTHESIS_LEFT(320...321)("("),
                      ArgumentsNode(321...333)([IntegerNode(321...333)()]),
                      PARENTHESIS_RIGHT(333...334)(")"),
                      nil,
                      "rand"
                    )]
                 ),
                 nil,
                 nil,
                 "%"
               )]
            ),
            ScopeNode(286...289)([]),
            (286...289),
            (294...295),
            nil,
            nil,
            nil,
            (336...339)
          ),
          DefNode(343...888)(
            IDENTIFIER(352...357)("bacon"),
            SelfNode(347...351)(),
            ParametersNode(358...359)(
              [RequiredParameterNode(358...359)()],
              [],
              [],
              nil,
              [],
              nil,
              nil
            ),
            StatementsNode(362...878)(
              [LocalVariableWriteNode(362...772)(
                 (362...374),
                 CallNode(377...772)(
                   CallNode(377...762)(
                     ConstantReadNode(377...382)(),
                     DOT(382...383)("."),
                     IDENTIFIER(383...386)("new"),
                     nil,
                     ArgumentsNode(387...388)(
                       [LocalVariableReadNode(387...388)(0)]
                     ),
                     nil,
                     BlockNode(389...762)(
                       ScopeNode(389...391)([]),
                       nil,
                       StatementsNode(395...756)(
                         [CallNode(395...756)(
                            StringNode(395...540)(
                              STRING_BEGIN(395...396)("'"),
                              STRING_CONTENT(396...539)(
                                "<span style=\"position: fixed; top: %dpx; left: %dpx; color: %s; font-size: %d%%; font-weight: %d00; font-sytle: %s; font-family: %s;\">%s</span>"
                              ),
                              STRING_END(539...540)("'"),
                              "<span style=\"position: fixed; top: %dpx; left: %dpx; color: %s; font-size: %d%%; font-weight: %d00; font-sytle: %s; font-family: %s;\">%s</span>"
                            ),
                            nil,
                            PERCENT(541...542)("%"),
                            nil,
                            ArgumentsNode(543...756)(
                              [ArrayNode(543...756)(
                                 [CallNode(549...563)(
                                    CallNode(549...558)(
                                      nil,
                                      nil,
                                      IDENTIFIER(549...553)("rand"),
                                      PARENTHESIS_LEFT(553...554)("("),
                                      ArgumentsNode(554...557)(
                                        [IntegerNode(554...557)()]
                                      ),
                                      PARENTHESIS_RIGHT(557...558)(")"),
                                      nil,
                                      "rand"
                                    ),
                                    nil,
                                    MINUS(559...560)("-"),
                                    nil,
                                    ArgumentsNode(561...563)(
                                      [IntegerNode(561...563)()]
                                    ),
                                    nil,
                                    nil,
                                    "-"
                                  ),
                                  CallNode(569...585)(
                                    CallNode(569...579)(
                                      nil,
                                      nil,
                                      IDENTIFIER(569...573)("rand"),
                                      PARENTHESIS_LEFT(573...574)("("),
                                      ArgumentsNode(574...578)(
                                        [IntegerNode(574...578)()]
                                      ),
                                      PARENTHESIS_RIGHT(578...579)(")"),
                                      nil,
                                      "rand"
                                    ),
                                    nil,
                                    MINUS(580...581)("-"),
                                    nil,
                                    ArgumentsNode(582...585)(
                                      [IntegerNode(582...585)()]
                                    ),
                                    nil,
                                    nil,
                                    "-"
                                  ),
                                  CallNode(591...601)(
                                    nil,
                                    nil,
                                    IDENTIFIER(591...601)("rand_color"),
                                    nil,
                                    nil,
                                    nil,
                                    nil,
                                    "rand_color"
                                  ),
                                  CallNode(607...621)(
                                    CallNode(607...616)(
                                      nil,
                                      nil,
                                      IDENTIFIER(607...611)("rand"),
                                      PARENTHESIS_LEFT(611...612)("("),
                                      ArgumentsNode(612...615)(
                                        [IntegerNode(612...615)()]
                                      ),
                                      PARENTHESIS_RIGHT(615...616)(")"),
                                      nil,
                                      "rand"
                                    ),
                                    nil,
                                    PLUS(617...618)("+"),
                                    nil,
                                    ArgumentsNode(619...621)(
                                      [IntegerNode(619...621)()]
                                    ),
                                    nil,
                                    nil,
                                    "+"
                                  ),
                                  CallNode(627...638)(
                                    CallNode(627...634)(
                                      nil,
                                      nil,
                                      IDENTIFIER(627...631)("rand"),
                                      PARENTHESIS_LEFT(631...632)("("),
                                      ArgumentsNode(632...633)(
                                        [IntegerNode(632...633)()]
                                      ),
                                      PARENTHESIS_RIGHT(633...634)(")"),
                                      nil,
                                      "rand"
                                    ),
                                    nil,
                                    PLUS(635...636)("+"),
                                    nil,
                                    ArgumentsNode(637...638)(
                                      [IntegerNode(637...638)()]
                                    ),
                                    nil,
                                    nil,
                                    "+"
                                  ),
                                  IfNode(649...670)(
                                    QUESTION_MARK(649...650)("?"),
                                    CallNode(644...648)(
                                      nil,
                                      nil,
                                      IDENTIFIER(644...648)("toss"),
                                      nil,
                                      nil,
                                      nil,
                                      nil,
                                      "toss"
                                    ),
                                    StatementsNode(651...659)(
                                      [StringNode(651...659)(
                                         STRING_BEGIN(651...652)("'"),
                                         STRING_CONTENT(652...658)("italic"),
                                         STRING_END(658...659)("'"),
                                         "italic"
                                       )]
                                    ),
                                    ElseNode(660...670)(
                                      COLON(660...661)(":"),
                                      StatementsNode(662...670)(
                                        [StringNode(662...670)(
                                           STRING_BEGIN(662...663)("'"),
                                           STRING_CONTENT(663...669)("normal"),
                                           STRING_END(669...670)("'"),
                                           "normal"
                                         )]
                                      ),
                                      nil
                                    ),
                                    nil
                                  ),
                                  CallNode(676...715)(
                                    ConstantReadNode(676...689)(),
                                    nil,
                                    BRACKET_LEFT_RIGHT(689...690)("["),
                                    BRACKET_LEFT(689...690)("["),
                                    ArgumentsNode(690...714)(
                                      [CallNode(690...714)(
                                         nil,
                                         nil,
                                         IDENTIFIER(690...694)("rand"),
                                         PARENTHESIS_LEFT(694...695)("("),
                                         ArgumentsNode(695...713)(
                                           [CallNode(695...713)(
                                              ConstantReadNode(695...708)(),
                                              DOT(708...709)("."),
                                              IDENTIFIER(709...713)("size"),
                                              nil,
                                              nil,
                                              nil,
                                              nil,
                                              "size"
                                            )]
                                         ),
                                         PARENTHESIS_RIGHT(713...714)(")"),
                                         nil,
                                         "rand"
                                       )]
                                    ),
                                    BRACKET_RIGHT(714...715)("]"),
                                    nil,
                                    "[]"
                                  ),
                                  CallNode(721...750)(
                                    StringNode(721...735)(
                                      STRING_BEGIN(721...722)("'"),
                                      STRING_CONTENT(722...734)(
                                        "Chunky Bacon"
                                      ),
                                      STRING_END(734...735)("'"),
                                      "Chunky Bacon"
                                    ),
                                    DOT(735...736)("."),
                                    IDENTIFIER(736...750)("randomize_case"),
                                    nil,
                                    nil,
                                    nil,
                                    nil,
                                    "randomize_case"
                                  )],
                                 BRACKET_LEFT_ARRAY(543...544)("["),
                                 BRACKET_RIGHT(755...756)("]")
                               )]
                            ),
                            nil,
                            nil,
                            "%"
                          )]
                       ),
                       (389...391),
                       (759...762)
                     ),
                     "new"
                   ),
                   DOT(762...763)("."),
                   IDENTIFIER(763...767)("join"),
                   nil,
                   ArgumentsNode(768...772)(
                     [StringNode(768...772)(
                        STRING_BEGIN(768...769)("\""),
                        STRING_CONTENT(769...771)("\\n"),
                        STRING_END(771...772)("\""),
                        "\n"
                      )]
                   ),
                   nil,
                   nil,
                   "join"
                 ),
                 (375...376),
                 0
               ),
               InterpolatedStringNode(783...878)(
                 HEREDOC_START(776...782)("<<-OUT"),
                 [StringNode(783...825)(
                    nil,
                    STRING_CONTENT(783...825)(
                      "\t\t<html>\n" + "\t\t<body style=\"background-color: "
                    ),
                    nil,
                    "\t\t<html>\n" + "\t\t<body style=\"background-color: "
                  ),
                  StringInterpolatedNode(825...838)(
                    EMBEXPR_BEGIN(825...827)("\#{"),
                    StatementsNode(827...837)(
                      [CallNode(827...837)(
                         nil,
                         nil,
                         IDENTIFIER(827...837)("rand_color"),
                         nil,
                         nil,
                         nil,
                         nil,
                         "rand_color"
                       )]
                    ),
                    EMBEXPR_END(837...838)("}")
                  ),
                  StringNode(838...842)(
                    nil,
                    STRING_CONTENT(838...842)(";\">\n"),
                    nil,
                    ";\">\n"
                  ),
                  StringInterpolatedNode(842...857)(
                    EMBEXPR_BEGIN(842...844)("\#{"),
                    StatementsNode(844...856)(
                      [LocalVariableReadNode(844...856)(0)]
                    ),
                    EMBEXPR_END(856...857)("}")
                  ),
                  StringNode(857...878)(
                    nil,
                    STRING_CONTENT(857...878)(
                      "\n" + "\t\t</body>\n" + "\t\t</html>\n"
                    ),
                    nil,
                    "\n" + "\t\t</body>\n" + "\t\t</html>\n"
                  )],
                 HEREDOC_END(878...884)("\t\tOUT\n")
               )]
            ),
            ScopeNode(343...346)(
              [IDENTIFIER(358...359)("n"),
               IDENTIFIER(362...374)("chunky_bacon")]
            ),
            (343...346),
            (351...352),
            nil,
            nil,
            nil,
            (885...888)
          )]
       ),
       KEYWORD_END(889...892)("end")
     ),
     CallNode(894...901)(
       nil,
       nil,
       IDENTIFIER(894...901)("require"),
       nil,
       ArgumentsNode(902...911)(
         [StringNode(902...911)(
            STRING_BEGIN(902...903)("'"),
            STRING_CONTENT(903...910)("webrick"),
            STRING_END(910...911)("'"),
            "webrick"
          )]
       ),
       nil,
       nil,
       "require"
     ),
     ClassNode(912...1220)(
       ScopeNode(912...917)([]),
       KEYWORD_CLASS(912...917)("class"),
       ConstantReadNode(918...935)(),
       LESS(936...937)("<"),
       ConstantPathNode(938...975)(
         ConstantPathNode(938...958)(
           ConstantReadNode(938...945)(),
           ConstantReadNode(947...958)(),
           (945...947)
         ),
         ConstantReadNode(960...975)(),
         (958...960)
       ),
       StatementsNode(977...1216)(
         [DefNode(977...1216)(
            IDENTIFIER(981...987)("do_GET"),
            nil,
            ParametersNode(988...996)(
              [RequiredParameterNode(988...991)(),
               RequiredParameterNode(993...996)()],
              [],
              [],
              nil,
              [],
              nil,
              nil
            ),
            StatementsNode(999...1211)(
              [LocalVariableWriteNode(999...1011)(
                 (999...1000),
                 CallNode(1003...1011)(
                   LocalVariableReadNode(1003...1006)(0),
                   DOT(1006...1007)("."),
                   IDENTIFIER(1007...1011)("path"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "path"
                 ),
                 (1001...1002),
                 0
               ),
               CallNode(1014...1022)(
                 LocalVariableReadNode(1014...1017)(0),
                 DOT(1017...1018)("."),
                 IDENTIFIER(1018...1022)("body"),
                 nil,
                 ArgumentsNode(1028...1172)(
                   [CaseNode(1028...1172)(
                      LocalVariableReadNode(1033...1034)(0),
                      [WhenNode(1038...1072)(
                         KEYWORD_WHEN(1038...1042)("when"),
                         [NilNode(1043...1046)(),
                          StringNode(1048...1051)(
                            STRING_BEGIN(1048...1049)("'"),
                            STRING_CONTENT(1049...1050)("/"),
                            STRING_END(1050...1051)("'"),
                            "/"
                          )],
                         StatementsNode(1056...1072)(
                           [CallNode(1056...1072)(
                              ConstantReadNode(1056...1062)(),
                              DOT(1062...1063)("."),
                              IDENTIFIER(1063...1068)("bacon"),
                              nil,
                              ArgumentsNode(1069...1072)(
                                [IntegerNode(1069...1072)()]
                              ),
                              nil,
                              nil,
                              "bacon"
                            )]
                         )
                       ),
                       WhenNode(1076...1102)(
                         KEYWORD_WHEN(1076...1080)("when"),
                         [RegularExpressionNode(1081...1095)(
                            REGEXP_BEGIN(1081...1082)("/"),
                            STRING_CONTENT(1082...1094)("favicon.ico$"),
                            REGEXP_END(1094...1095)("/"),
                            "favicon.ico$"
                          )],
                         StatementsNode(1100...1102)(
                           [StringNode(1100...1102)(
                              STRING_BEGIN(1100...1101)("'"),
                              STRING_CONTENT(1101...1101)(""),
                              STRING_END(1101...1102)("'"),
                              ""
                            )]
                         )
                       ),
                       WhenNode(1106...1145)(
                         KEYWORD_WHEN(1106...1110)("when"),
                         [RegularExpressionNode(1111...1120)(
                            REGEXP_BEGIN(1111...1112)("/"),
                            STRING_CONTENT(1112...1119)("\\/(\\d+)"),
                            REGEXP_END(1119...1120)("/"),
                            "/(d+)"
                          )],
                         StatementsNode(1125...1145)(
                           [CallNode(1125...1145)(
                              ConstantReadNode(1125...1131)(),
                              DOT(1131...1132)("."),
                              IDENTIFIER(1132...1137)("bacon"),
                              nil,
                              ArgumentsNode(1138...1145)(
                                [CallNode(1138...1145)(
                                   GlobalVariableReadNode(1138...1140)(
                                     NTH_REFERENCE(1138...1140)("$1")
                                   ),
                                   DOT(1140...1141)("."),
                                   IDENTIFIER(1141...1145)("to_i"),
                                   nil,
                                   nil,
                                   nil,
                                   nil,
                                   "to_i"
                                 )]
                              ),
                              nil,
                              nil,
                              "bacon"
                            )]
                         )
                       )],
                      ElseNode(1149...1172)(
                        KEYWORD_ELSE(1149...1153)("else"),
                        StatementsNode(1158...1165)(
                          [StringNode(1158...1165)(
                             STRING_BEGIN(1158...1159)("'"),
                             STRING_CONTENT(1159...1164)("what?"),
                             STRING_END(1164...1165)("'"),
                             "what?"
                           )]
                        ),
                        KEYWORD_END(1169...1172)("end")
                      ),
                      (1028...1032),
                      (1169...1172)
                    )]
                 ),
                 nil,
                 nil,
                 "body="
               ),
               CallNode(1178...1211)(
                 LocalVariableReadNode(1178...1181)(0),
                 nil,
                 BRACKET_LEFT_RIGHT_EQUAL(1181...1182)("["),
                 BRACKET_LEFT(1181...1182)("["),
                 ArgumentsNode(1182...1211)(
                   [StringNode(1182...1196)(
                      STRING_BEGIN(1182...1183)("'"),
                      STRING_CONTENT(1183...1195)("Content-Type"),
                      STRING_END(1195...1196)("'"),
                      "Content-Type"
                    ),
                    StringNode(1200...1211)(
                      STRING_BEGIN(1200...1201)("'"),
                      STRING_CONTENT(1201...1210)("text/html"),
                      STRING_END(1210...1211)("'"),
                      "text/html"
                    )]
                 ),
                 BRACKET_RIGHT(1196...1197)("]"),
                 nil,
                 "[]="
               )]
            ),
            ScopeNode(977...980)(
              [IDENTIFIER(988...991)("req"),
               IDENTIFIER(993...996)("res"),
               IDENTIFIER(999...1000)("q")]
            ),
            (977...980),
            nil,
            nil,
            nil,
            nil,
            (1213...1216)
          )]
       ),
       KEYWORD_END(1217...1220)("end")
     ),
     LocalVariableWriteNode(1251...1291)(
       (1251...1252),
       CallNode(1255...1291)(
         ConstantPathNode(1255...1274)(
           ConstantReadNode(1255...1262)(),
           ConstantReadNode(1264...1274)(),
           (1262...1264)
         ),
         DOT(1274...1275)("."),
         IDENTIFIER(1275...1278)("new"),
         nil,
         ArgumentsNode(1279...1291)(
           [HashNode(1279...1291)(
              nil,
              [AssocNode(1279...1291)(
                 SymbolNode(1279...1284)(
                   SYMBOL_BEGIN(1279...1280)(":"),
                   CONSTANT(1280...1284)("Port"),
                   nil,
                   "Port"
                 ),
                 IntegerNode(1288...1291)(),
                 EQUAL_GREATER(1285...1287)("=>")
               )],
              nil
            )]
         ),
         nil,
         nil,
         "new"
       ),
       (1253...1254),
       0
     ),
     CallNode(1293...1323)(
       LocalVariableReadNode(1293...1294)(0),
       DOT(1294...1295)("."),
       IDENTIFIER(1295...1300)("mount"),
       nil,
       ArgumentsNode(1301...1323)(
         [StringNode(1301...1304)(
            STRING_BEGIN(1301...1302)("'"),
            STRING_CONTENT(1302...1303)("/"),
            STRING_END(1303...1304)("'"),
            "/"
          ),
          ConstantReadNode(1306...1323)()]
       ),
       nil,
       nil,
       "mount"
     ),
     CallNode(1325...1480)(
       LocalVariableReadNode(1325...1326)(0),
       DOT(1326...1327)("."),
       IDENTIFIER(1327...1337)("mount_proc"),
       nil,
       ArgumentsNode(1338...1346)(
         [StringNode(1338...1346)(
            STRING_BEGIN(1338...1339)("'"),
            STRING_CONTENT(1339...1345)("/comic"),
            STRING_END(1345...1346)("'"),
            "/comic"
          )]
       ),
       nil,
       BlockNode(1347...1480)(
         ScopeNode(1347...1349)(
           [IDENTIFIER(1351...1354)("req"), IDENTIFIER(1356...1359)("res")]
         ),
         BlockParametersNode(1350...1360)(
           ParametersNode(1351...1359)(
             [RequiredParameterNode(1351...1354)(),
              RequiredParameterNode(1356...1359)()],
             [],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (1350...1351),
           (1359...1360)
         ),
         StatementsNode(1362...1476)(
           [CallNode(1362...1370)(
              LocalVariableReadNode(1362...1365)(0),
              DOT(1365...1366)("."),
              IDENTIFIER(1366...1370)("body"),
              nil,
              ArgumentsNode(1373...1441)(
                [StringNode(1373...1441)(
                   STRING_BEGIN(1373...1374)("'"),
                   STRING_CONTENT(1374...1440)(
                     "<img src=\"http://www.poignantguide.net/ruby/i/the.foxes-4e.png\" />"
                   ),
                   STRING_END(1440...1441)("'"),
                   "<img src=\"http://www.poignantguide.net/ruby/i/the.foxes-4e.png\" />"
                 )]
              ),
              nil,
              nil,
              "body="
            ),
            CallNode(1443...1476)(
              LocalVariableReadNode(1443...1446)(0),
              nil,
              BRACKET_LEFT_RIGHT_EQUAL(1446...1447)("["),
              BRACKET_LEFT(1446...1447)("["),
              ArgumentsNode(1447...1476)(
                [StringNode(1447...1461)(
                   STRING_BEGIN(1447...1448)("'"),
                   STRING_CONTENT(1448...1460)("Content-Type"),
                   STRING_END(1460...1461)("'"),
                   "Content-Type"
                 ),
                 StringNode(1465...1476)(
                   STRING_BEGIN(1465...1466)("\""),
                   STRING_CONTENT(1466...1475)("text/html"),
                   STRING_END(1475...1476)("\""),
                   "text/html"
                 )]
              ),
              BRACKET_RIGHT(1461...1462)("]"),
              nil,
              "[]="
            )]
         ),
         (1347...1349),
         (1477...1480)
       ),
       "mount_proc"
     ),
     CallNode(1482...1508)(
       nil,
       nil,
       IDENTIFIER(1482...1486)("trap"),
       PARENTHESIS_LEFT(1486...1487)("("),
       ArgumentsNode(1487...1492)(
         [StringNode(1487...1492)(
            STRING_BEGIN(1487...1488)("\""),
            STRING_CONTENT(1488...1491)("INT"),
            STRING_END(1491...1492)("\""),
            "INT"
          )]
       ),
       PARENTHESIS_RIGHT(1492...1493)(")"),
       BlockNode(1494...1508)(
         ScopeNode(1494...1495)([]),
         nil,
         StatementsNode(1496...1506)(
           [CallNode(1496...1506)(
              LocalVariableReadNode(1496...1497)(1),
              DOT(1497...1498)("."),
              IDENTIFIER(1498...1506)("shutdown"),
              nil,
              nil,
              nil,
              nil,
              "shutdown"
            )]
         ),
         (1494...1495),
         (1507...1508)
       ),
       "trap"
     ),
     CallNode(1509...1516)(
       LocalVariableReadNode(1509...1510)(0),
       DOT(1510...1511)("."),
       IDENTIFIER(1511...1516)("start"),
       nil,
       nil,
       nil,
       nil,
       "start"
     )]
  )
)
