ProgramNode(0...340)(
  ScopeNode(0...0)([]),
  StatementsNode(0...340)(
    [CallNode(0...340)(
       ConstantReadNode(0...4)(),
       DOT(4...5)("."),
       IDENTIFIER(5...9)("open"),
       PARENTHESIS_LEFT(9...10)("("),
       ArgumentsNode(10...20)(
         [CallNode(10...20)(
            ConstantReadNode(10...14)(),
            DOT(14...15)("."),
            IDENTIFIER(15...20)("first"),
            nil,
            nil,
            nil,
            nil,
            "first"
          )]
       ),
       PARENTHESIS_RIGHT(20...21)(")"),
       BlockNode(21...340)(
         ScopeNode(21...22)(
           [IDENTIFIER(23...24)("f"),
            IDENTIFIER(28...35)("deficit"),
            IDENTIFIER(46...49)("buf")]
         ),
         BlockParametersNode(22...25)(
           ParametersNode(23...24)(
             [RequiredParameterNode(23...24)()],
             [],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (22...23),
           (24...25)
         ),
         StatementsNode(28...332)(
           [LocalVariableWriteNode(28...37)(
              (28...35),
              IntegerNode(36...37)(),
              (35...36),
              0
            ),
            WhileNode(40...332)(
              KEYWORD_WHILE(40...45)("while"),
              LocalVariableWriteNode(46...70)(
                (46...49),
                CallNode(50...70)(
                  LocalVariableReadNode(50...51)(0),
                  DOT(51...52)("."),
                  IDENTIFIER(52...56)("read"),
                  PARENTHESIS_LEFT(56...57)("("),
                  ArgumentsNode(57...69)(
                    [CallNode(57...69)(
                       IntegerNode(57...61)(),
                       nil,
                       PLUS(61...62)("+"),
                       nil,
                       ArgumentsNode(62...69)(
                         [LocalVariableReadNode(62...69)(0)]
                       ),
                       nil,
                       nil,
                       "+"
                     )]
                  ),
                  PARENTHESIS_RIGHT(69...70)(")"),
                  nil,
                  "read"
                ),
                (49...50),
                0
              ),
              StatementsNode(124...332)(
                [IfNode(124...219)(
                   KEYWORD_IF(124...126)("if"),
                   CallNode(127...149)(
                     RegularExpressionNode(127...143)(
                       REGEXP_BEGIN(127...128)("/"),
                       STRING_CONTENT(128...142)("\\\\[0-7]{0,2}\\Z"),
                       REGEXP_END(142...143)("/"),
                       "\\[0-7]{0,2}Z"
                     ),
                     nil,
                     EQUAL_EQUAL_EQUAL(143...146)("==="),
                     nil,
                     ArgumentsNode(146...149)(
                       [LocalVariableReadNode(146...149)(0)]
                     ),
                     nil,
                     nil,
                     "==="
                   ),
                   StatementsNode(156...219)(
                     [LocalVariableWriteNode(156...171)(
                        (156...163),
                        CallNode(164...171)(
                          GlobalVariableReadNode(164...166)(
                            BACK_REFERENCE(164...166)("$&")
                          ),
                          DOT(166...167)("."),
                          IDENTIFIER(167...171)("size"),
                          nil,
                          nil,
                          nil,
                          nil,
                          "size"
                        ),
                        (163...164),
                        0
                      ),
                      CallNode(178...198)(
                        LocalVariableReadNode(178...181)(0),
                        nil,
                        BRACKET_LEFT_RIGHT_EQUAL(181...182)("["),
                        BRACKET_LEFT(181...182)("["),
                        ArgumentsNode(182...198)(
                          [RangeNode(182...194)(
                             CallNode(182...190)(
                               LocalVariableReadNode(183...190)(0),
                               nil,
                               UMINUS(182...183)("-"),
                               nil,
                               nil,
                               nil,
                               nil,
                               "-@"
                             ),
                             CallNode(192...194)(
                               IntegerNode(193...194)(),
                               nil,
                               UMINUS_NUM(192...193)("-"),
                               nil,
                               nil,
                               nil,
                               nil,
                               "-@"
                             ),
                             (190...192)
                           ),
                           StringNode(196...198)(
                             STRING_BEGIN(196...197)("'"),
                             STRING_CONTENT(197...197)(""),
                             STRING_END(197...198)("'"),
                             ""
                           )]
                        ),
                        BRACKET_RIGHT(194...195)("]"),
                        nil,
                        "[]="
                      ),
                      OperatorAssignmentNode(205...219)(
                        CallNode(205...210)(
                          LocalVariableReadNode(205...206)(0),
                          DOT(206...207)("."),
                          IDENTIFIER(207...210)("pos"),
                          nil,
                          nil,
                          nil,
                          nil,
                          "pos="
                        ),
                        MINUS_EQUAL(210...212)("-="),
                        LocalVariableReadNode(212...219)(0)
                      )]
                   ),
                   ElseNode(224...253)(
                     KEYWORD_ELSE(224...228)("else"),
                     StatementsNode(236...245)(
                       [LocalVariableWriteNode(236...245)(
                          (236...243),
                          IntegerNode(244...245)(),
                          (243...244),
                          0
                        )]
                     ),
                     KEYWORD_END(250...253)("end")
                   ),
                   KEYWORD_END(250...253)("end")
                 ),
                 CallNode(259...332)(
                   GlobalVariableReadNode(259...266)(
                     GLOBAL_VARIABLE(259...266)("$stdout")
                   ),
                   DOT(266...267)("."),
                   IDENTIFIER(267...272)("write"),
                   nil,
                   ArgumentsNode(273...332)(
                     [CallNode(273...332)(
                        LocalVariableReadNode(273...276)(0),
                        DOT(276...277)("."),
                        IDENTIFIER(277...281)("gsub"),
                        PARENTHESIS_LEFT(281...282)("("),
                        ArgumentsNode(282...298)(
                          [RegularExpressionNode(282...298)(
                             REGEXP_BEGIN(282...283)("/"),
                             STRING_CONTENT(283...297)("\\\\([0-7]{1,3})"),
                             REGEXP_END(297...298)("/"),
                             "\\([0-7]{1,3})"
                           )]
                        ),
                        PARENTHESIS_RIGHT(298...299)(")"),
                        BlockNode(299...332)(
                          ScopeNode(299...300)([]),
                          nil,
                          StatementsNode(307...325)(
                            [CallNode(307...325)(
                               CallNode(307...321)(
                                 CallNode(307...313)(
                                   GlobalVariableReadNode(307...309)(
                                     NTH_REFERENCE(307...309)("$1")
                                   ),
                                   DOT(309...310)("."),
                                   IDENTIFIER(310...313)("oct"),
                                   nil,
                                   nil,
                                   nil,
                                   nil,
                                   "oct"
                                 ),
                                 DOT(313...314)("."),
                                 AMPERSAND(314...315)("&"),
                                 PARENTHESIS_LEFT(315...316)("("),
                                 ArgumentsNode(316...320)(
                                   [IntegerNode(316...320)()]
                                 ),
                                 PARENTHESIS_RIGHT(320...321)(")"),
                                 nil,
                                 "&"
                               ),
                               DOT(321...322)("."),
                               IDENTIFIER(322...325)("chr"),
                               nil,
                               nil,
                               nil,
                               nil,
                               "chr"
                             )]
                          ),
                          (299...300),
                          (331...332)
                        ),
                        "gsub"
                      )]
                   ),
                   nil,
                   nil,
                   "write"
                 )]
              )
            )]
         ),
         (21...22),
         (339...340)
       ),
       "open"
     )]
  )
)
