ProgramNode(1...167)(
  ScopeNode(0...0)([]),
  StatementsNode(1...167)(
    [OperatorAssignmentNode(1...13)(
       CallNode(1...7)(
         CallNode(1...2)(
           nil,
           nil,
           IDENTIFIER(1...2)("e"),
           nil,
           nil,
           nil,
           nil,
           "e"
         ),
         DOT(2...3)("."),
         IDENTIFIER(3...7)("hour"),
         nil,
         nil,
         nil,
         nil,
         "hour="
       ),
       PERCENT_EQUAL(8...10)("%="),
       IntegerNode(11...13)()
     ),
     ParenthesesNode(15...33)(
       StatementsNode(17...32)(
         [CallNode(17...32)(
            CallNode(17...25)(
              nil,
              nil,
              IDENTIFIER(17...25)("downcase"),
              nil,
              nil,
              nil,
              nil,
              "downcase"
            ),
            nil,
            EQUAL_EQUAL(26...28)("=="),
            nil,
            ArgumentsNode(29...32)(
              [StringNode(29...32)(
                 STRING_BEGIN(29...30)("'"),
                 STRING_CONTENT(30...31)("p"),
                 STRING_END(31...32)("'"),
                 "p"
               )]
            ),
            nil,
            nil,
            "=="
          )]
       ),
       (15...16),
       (32...33)
     ),
     OperatorAssignmentNode(35...47)(
       CallNode(35...41)(
         CallNode(35...36)(
           nil,
           nil,
           IDENTIFIER(35...36)("e"),
           nil,
           nil,
           nil,
           nil,
           "e"
         ),
         DOT(36...37)("."),
         IDENTIFIER(37...41)("hour"),
         nil,
         nil,
         nil,
         nil,
         "hour="
       ),
       PERCENT_EQUAL(42...44)("%="),
       IntegerNode(45...47)()
     ),
     BeginNode(49...75)(
       KEYWORD_BEGIN(49...54)("begin"),
       StatementsNode(55...70)(
         [CallNode(55...70)(
            CallNode(55...63)(
              nil,
              nil,
              IDENTIFIER(55...63)("downcase"),
              nil,
              nil,
              nil,
              nil,
              "downcase"
            ),
            nil,
            EQUAL_EQUAL(64...66)("=="),
            nil,
            ArgumentsNode(67...70)(
              [StringNode(67...70)(
                 STRING_BEGIN(67...68)("'"),
                 STRING_CONTENT(68...69)("p"),
                 STRING_END(69...70)("'"),
                 "p"
               )]
            ),
            nil,
            nil,
            "=="
          )]
       ),
       nil,
       nil,
       nil,
       KEYWORD_END(72...75)("end")
     ),
     OperatorAssignmentNode(77...89)(
       CallNode(77...83)(
         CallNode(77...78)(
           nil,
           nil,
           IDENTIFIER(77...78)("e"),
           nil,
           nil,
           nil,
           nil,
           "e"
         ),
         DOT(78...79)("."),
         IDENTIFIER(79...83)("hour"),
         nil,
         nil,
         nil,
         nil,
         "hour="
       ),
       PERCENT_EQUAL(84...86)("%="),
       IntegerNode(87...89)()
     ),
     IfNode(91...109)(
       KEYWORD_IF(91...93)("if"),
       CallNode(94...109)(
         CallNode(94...102)(
           nil,
           nil,
           IDENTIFIER(94...102)("downcase"),
           nil,
           nil,
           nil,
           nil,
           "downcase"
         ),
         nil,
         EQUAL_EQUAL(103...105)("=="),
         nil,
         ArgumentsNode(106...109)(
           [StringNode(106...109)(
              STRING_BEGIN(106...107)("'"),
              STRING_CONTENT(107...108)("p"),
              STRING_END(108...109)("'"),
              "p"
            )]
         ),
         nil,
         nil,
         "=="
       ),
       nil,
       nil,
       KEYWORD_END(111...114)("end")
     ),
     OperatorAssignmentNode(116...128)(
       CallNode(116...122)(
         CallNode(116...117)(
           nil,
           nil,
           IDENTIFIER(116...117)("e"),
           nil,
           nil,
           nil,
           nil,
           "e"
         ),
         DOT(117...118)("."),
         IDENTIFIER(118...122)("hour"),
         nil,
         nil,
         nil,
         nil,
         "hour="
       ),
       PERCENT_EQUAL(123...125)("%="),
       IntegerNode(126...128)()
     ),
     ParenthesesNode(130...140)(
       StatementsNode(131...139)(
         [CallNode(131...139)(
            nil,
            nil,
            IDENTIFIER(131...139)("downcase"),
            nil,
            nil,
            nil,
            nil,
            "downcase"
          )]
       ),
       (130...131),
       (139...140)
     ),
     OperatorAssignmentNode(142...154)(
       CallNode(142...148)(
         CallNode(142...143)(
           nil,
           nil,
           IDENTIFIER(142...143)("e"),
           nil,
           nil,
           nil,
           nil,
           "e"
         ),
         DOT(143...144)("."),
         IDENTIFIER(144...148)("hour"),
         nil,
         nil,
         nil,
         nil,
         "hour="
       ),
       PERCENT_EQUAL(149...151)("%="),
       IntegerNode(152...154)()
     ),
     IfNode(156...167)(
       KEYWORD_IF(156...158)("if"),
       CallNode(159...167)(
         nil,
         nil,
         IDENTIFIER(159...167)("downcase"),
         nil,
         nil,
         nil,
         nil,
         "downcase"
       ),
       nil,
       nil,
       KEYWORD_END(169...172)("end")
     )]
  )
)
