ProgramNode(0...171)(
  ScopeNode(0...0)([IDENTIFIER(0...1)("j"), IDENTIFIER(120...121)("g")]),
  StatementsNode(0...171)(
    [LocalVariableWriteNode(0...3)((0...1), IntegerNode(2...3)(), (1...2), 0),
     DefNode(4...35)(
       IDENTIFIER(8...9)("i"),
       nil,
       ParametersNode(10...11)(
         [RequiredParameterNode(10...11)()],
         [],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode(13...31)(
         [ArrayNode(13...31)(
            [IfNode(16...26)(
               QUESTION_MARK(16...17)("?"),
               LocalVariableReadNode(14...15)(0),
               StatementsNode(17...20)(
                 [StringNode(17...20)(
                    STRING_BEGIN(17...18)("\""),
                    STRING_CONTENT(18...19)("d"),
                    STRING_END(19...20)("\""),
                    "d"
                  )]
               ),
               ElseNode(21...26)(
                 COLON(21...22)(":"),
                 StatementsNode(23...26)(
                   [StringNode(23...26)(
                      STRING_BEGIN(23...24)("\""),
                      STRING_CONTENT(24...25)("e"),
                      STRING_END(25...26)("\""),
                      "e"
                    )]
                 ),
                 nil
               ),
               nil
             ),
             LocalVariableReadNode(29...30)(0)],
            BRACKET_LEFT_ARRAY(13...14)("["),
            BRACKET_RIGHT(30...31)("]")
          )]
       ),
       ScopeNode(4...7)([IDENTIFIER(10...11)("n")]),
       (4...7),
       nil,
       (9...10),
       (11...12),
       nil,
       (32...35)
     ),
     CallNode(37...44)(
       nil,
       nil,
       IDENTIFIER(37...38)("p"),
       PARENTHESIS_LEFT(38...39)("("),
       ArgumentsNode(39...40)(
         [CallNode(39...40)(
            nil,
            nil,
            IDENTIFIER(39...40)("i"),
            nil,
            ArgumentsNode(41...43)(
              [StringNode(41...43)(
                 STRING_BEGIN(41...42)("?"),
                 STRING_CONTENT(42...43)("\""),
                 nil,
                 "\""
               )]
            ),
            nil,
            nil,
            "i"
          )]
       ),
       PARENTHESIS_RIGHT(43...44)(")"),
       nil,
       "p"
     ),
     CallNode(45...60)(
       nil,
       nil,
       IDENTIFIER(45...46)("p"),
       PARENTHESIS_LEFT(46...47)("("),
       ArgumentsNode(49...59)(
         [IfNode(49...59)(
            QUESTION_MARK(49...50)("?"),
            LocalVariableReadNode(47...48)(0),
            StatementsNode(50...53)(
              [StringNode(50...53)(
                 STRING_BEGIN(50...51)("\""),
                 STRING_CONTENT(51...52)("d"),
                 STRING_END(52...53)("\""),
                 "d"
               )]
            ),
            ElseNode(54...59)(
              COLON(54...55)(":"),
              StatementsNode(56...59)(
                [StringNode(56...59)(
                   STRING_BEGIN(56...57)("\""),
                   STRING_CONTENT(57...58)("e"),
                   STRING_END(58...59)("\""),
                   "e"
                 )]
              ),
              nil
            ),
            nil
          )]
       ),
       PARENTHESIS_RIGHT(59...60)(")"),
       nil,
       "p"
     ),
     DefNode(62...80)(
       IDENTIFIER(66...67)("g"),
       nil,
       ParametersNode(68...73)(
         [],
         [OptionalParameterNode(68...73)(
            IDENTIFIER(68...69)("x"),
            EQUAL(69...70)("="),
            NilNode(70...73)()
          )],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode(75...76)([LocalVariableReadNode(75...76)(0)]),
       ScopeNode(62...65)([IDENTIFIER(68...69)("x")]),
       (62...65),
       nil,
       (67...68),
       (73...74),
       nil,
       (77...80)
     ),
     DefNode(81...102)(
       IDENTIFIER(85...87)("gg"),
       nil,
       ParametersNode(88...93)(
         [],
         [OptionalParameterNode(88...93)(
            IDENTIFIER(88...89)("x"),
            EQUAL(89...90)("="),
            NilNode(90...93)()
          )],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode(95...96)(
         [CallNode(95...96)(
            nil,
            nil,
            IDENTIFIER(95...96)("g"),
            nil,
            ArgumentsNode(97...98)([LocalVariableReadNode(97...98)(0)]),
            nil,
            nil,
            "g"
          )]
       ),
       ScopeNode(81...84)([IDENTIFIER(88...89)("x")]),
       (81...84),
       nil,
       (87...88),
       (93...94),
       nil,
       (99...102)
     ),
     CallNode(103...111)(
       nil,
       nil,
       IDENTIFIER(103...104)("p"),
       PARENTHESIS_LEFT(104...105)("("),
       ArgumentsNode(105...107)(
         [CallNode(105...107)(
            nil,
            nil,
            IDENTIFIER(105...107)("gg"),
            nil,
            ArgumentsNode(108...110)(
              [SymbolNode(108...110)(
                 SYMBOL_BEGIN(108...109)(":"),
                 IDENTIFIER(109...110)("x"),
                 nil,
                 "x"
               )]
            ),
            nil,
            nil,
            "gg"
          )]
       ),
       PARENTHESIS_RIGHT(110...111)(")"),
       nil,
       "p"
     ),
     CallNode(112...119)(
       nil,
       nil,
       IDENTIFIER(112...113)("p"),
       PARENTHESIS_LEFT(113...114)("("),
       ArgumentsNode(114...115)(
         [CallNode(114...115)(
            nil,
            nil,
            IDENTIFIER(114...115)("g"),
            nil,
            ArgumentsNode(116...118)(
              [SymbolNode(116...118)(
                 SYMBOL_BEGIN(116...117)(":"),
                 IDENTIFIER(117...118)("y"),
                 nil,
                 "y"
               )]
            ),
            nil,
            nil,
            "g"
          )]
       ),
       PARENTHESIS_RIGHT(118...119)(")"),
       nil,
       "p"
     ),
     LocalVariableWriteNode(120...123)(
       (120...121),
       IntegerNode(122...123)(),
       (121...122),
       0
     ),
     CallNode(124...132)(
       nil,
       nil,
       IDENTIFIER(124...125)("p"),
       PARENTHESIS_LEFT(125...126)("("),
       ArgumentsNode(126...128)(
         [CallNode(126...128)(
            nil,
            nil,
            IDENTIFIER(126...128)("gg"),
            nil,
            ArgumentsNode(129...131)(
              [SymbolNode(129...131)(
                 SYMBOL_BEGIN(129...130)(":"),
                 IDENTIFIER(130...131)("z"),
                 nil,
                 "z"
               )]
            ),
            nil,
            nil,
            "gg"
          )]
       ),
       PARENTHESIS_RIGHT(131...132)(")"),
       nil,
       "p"
     ),
     BeginNode(149...171)(
       KEYWORD_BEGIN(149...154)("begin"),
       StatementsNode(155...156)(
         [CallNode(155...156)(
            nil,
            nil,
            IDENTIFIER(155...156)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(157...167)(
         KEYWORD_RESCUE(157...163)("rescue"),
         [],
         nil,
         nil,
         StatementsNode(164...167)(
           [CallNode(164...165)(
              nil,
              nil,
              IDENTIFIER(164...165)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            ),
            CallNode(166...167)(
              nil,
              nil,
              IDENTIFIER(166...167)("c"),
              nil,
              nil,
              nil,
              nil,
              "c"
            )]
         ),
         nil
       ),
       nil,
       nil,
       KEYWORD_END(168...171)("end")
     )]
  )
)
