ProgramNode(56...693)(
  ScopeNode(0...0)([]),
  StatementsNode(56...693)(
    [CallNode(56...57)(
       nil,
       nil,
       IDENTIFIER(56...57)("p"),
       nil,
       ArgumentsNode(71...99)(
         [CallNode(71...99)(
            CallNode(71...92)(
              InterpolatedStringNode(71...79)(
                HEREDOC_START(58...64)("<<-foo"),
                [StringNode(71...79)(
                   nil,
                   STRING_CONTENT(71...79)("  abcd\r\n"),
                   nil,
                   "  abcd\r\n"
                 )],
                HEREDOC_END(79...86)("  foo\r\n")
              ),
              nil,
              PLUS(64...65)("+"),
              nil,
              ArgumentsNode(65...92)(
                [InterpolatedStringNode(65...92)(
                   STRING_BEGIN(65...66)("'"),
                   [StringNode(66...71)(
                      nil,
                      STRING_CONTENT(66...71)("123\r\n"),
                      nil,
                      "123\r\n"
                    ),
                    StringNode(86...91)(
                      nil,
                      STRING_CONTENT(86...91)("  456"),
                      nil,
                      "  456"
                    )],
                   STRING_END(91...92)("'")
                 )]
              ),
              nil,
              nil,
              "+"
            ),
            nil,
            PLUS(92...93)("+"),
            nil,
            ArgumentsNode(93...99)(
              [StringNode(93...99)(
                 STRING_BEGIN(93...94)("\""),
                 STRING_CONTENT(94...98)("8910"),
                 STRING_END(98...99)("\""),
                 "8910"
               )]
            ),
            nil,
            nil,
            "+"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(101...102)(
       nil,
       nil,
       IDENTIFIER(101...102)("p"),
       nil,
       ArgumentsNode(103...106)(
         [CallNode(103...106)(
            nil,
            nil,
            IDENTIFIER(103...106)("heh"),
            nil,
            nil,
            nil,
            nil,
            "heh"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(110...111)(
       nil,
       nil,
       IDENTIFIER(110...111)("p"),
       nil,
       ArgumentsNode(139...180)(
         [CallNode(139...180)(
            CallNode(139...173)(
              InterpolatedStringNode(139...147)(
                HEREDOC_START(112...118)("<<-foo"),
                [StringNode(139...147)(
                   nil,
                   STRING_CONTENT(139...147)("  abcd\r\n"),
                   nil,
                   "  abcd\r\n"
                 )],
                HEREDOC_END(147...154)("  foo\r\n")
              ),
              nil,
              PLUS(118...119)("+"),
              nil,
              ArgumentsNode(119...173)(
                [InterpolatedStringNode(119...173)(
                   STRING_BEGIN(119...120)("\""),
                   [StringNode(120...123)(
                      nil,
                      STRING_CONTENT(120...123)("123"),
                      nil,
                      "123"
                    ),
                    StringInterpolatedNode(123...137)(
                      EMBEXPR_BEGIN(123...125)("\#{"),
                      StatementsNode(125...136)([FloatNode(125...136)()]),
                      EMBEXPR_END(136...137)("}")
                    ),
                    StringNode(137...139)(
                      nil,
                      STRING_CONTENT(137...139)("\r\n"),
                      nil,
                      "\r\n"
                    ),
                    StringNode(154...159)(
                      nil,
                      STRING_CONTENT(154...159)("  456"),
                      nil,
                      "  456"
                    ),
                    StringInterpolatedNode(159...172)(
                      EMBEXPR_BEGIN(159...161)("\#{"),
                      StatementsNode(161...171)([FloatNode(161...171)()]),
                      EMBEXPR_END(171...172)("}")
                    )],
                   STRING_END(172...173)("\"")
                 )]
              ),
              nil,
              nil,
              "+"
            ),
            nil,
            PLUS(173...174)("+"),
            nil,
            ArgumentsNode(174...180)(
              [StringNode(174...180)(
                 STRING_BEGIN(174...175)("\""),
                 STRING_CONTENT(175...179)("8910"),
                 STRING_END(179...180)("\""),
                 "8910"
               )]
            ),
            nil,
            nil,
            "+"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(182...183)(
       nil,
       nil,
       IDENTIFIER(182...183)("p"),
       nil,
       ArgumentsNode(184...200)(
         [CallNode(184...200)(
            nil,
            nil,
            IDENTIFIER(184...200)("hurhurhurhurhur!"),
            nil,
            nil,
            nil,
            nil,
            "hurhurhurhurhur!"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(204...205)(
       nil,
       nil,
       IDENTIFIER(204...205)("p"),
       nil,
       ArgumentsNode(233...267)(
         [CallNode(233...267)(
            InterpolatedStringNode(233...241)(
              HEREDOC_START(206...212)("<<-foo"),
              [StringNode(233...241)(
                 nil,
                 STRING_CONTENT(233...241)("  abcd\r\n"),
                 nil,
                 "  abcd\r\n"
               )],
              HEREDOC_END(241...248)("  foo\r\n")
            ),
            nil,
            PLUS(212...213)("+"),
            nil,
            ArgumentsNode(213...267)(
              [InterpolatedStringNode(213...267)(
                 STRING_BEGIN(213...214)("\""),
                 [StringNode(214...217)(
                    nil,
                    STRING_CONTENT(214...217)("123"),
                    nil,
                    "123"
                  ),
                  StringInterpolatedNode(217...231)(
                    EMBEXPR_BEGIN(217...219)("\#{"),
                    StatementsNode(219...230)([FloatNode(219...230)()]),
                    EMBEXPR_END(230...231)("}")
                  ),
                  StringNode(231...233)(
                    nil,
                    STRING_CONTENT(231...233)("\r\n"),
                    nil,
                    "\r\n"
                  ),
                  StringNode(248...253)(
                    nil,
                    STRING_CONTENT(248...253)("  456"),
                    nil,
                    "  456"
                  ),
                  StringInterpolatedNode(253...266)(
                    EMBEXPR_BEGIN(253...255)("\#{"),
                    StatementsNode(255...265)([FloatNode(255...265)()]),
                    EMBEXPR_END(265...266)("}")
                  )],
                 STRING_END(266...267)("\"")
               )]
            ),
            nil,
            nil,
            "+"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(269...270)(
       nil,
       nil,
       IDENTIFIER(269...270)("p"),
       nil,
       ArgumentsNode(271...287)(
         [CallNode(271...287)(
            nil,
            nil,
            IDENTIFIER(271...287)("hurhurhurhurhur!"),
            nil,
            nil,
            nil,
            nil,
            "hurhurhurhurhur!"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(293...294)(
       nil,
       nil,
       IDENTIFIER(293...294)("p"),
       nil,
       ArgumentsNode(308...330)(
         [CallNode(308...330)(
            InterpolatedStringNode(308...320)(
              HEREDOC_START(295...301)("<<here"),
              [StringNode(308...320)(
                 nil,
                 STRING_CONTENT(308...320)("456\r\n" + "there\r\n"),
                 nil,
                 "456\r\n" + "there\r\n"
               )],
              HEREDOC_END(320...326)("here\r\n")
            ),
            nil,
            PLUS(301...302)("+"),
            nil,
            ArgumentsNode(302...330)(
              [InterpolatedStringNode(302...330)(
                 STRING_BEGIN(302...303)("'"),
                 [StringNode(303...308)(
                    nil,
                    STRING_CONTENT(303...308)("123\r\n"),
                    nil,
                    "123\r\n"
                  ),
                  StringNode(326...329)(
                    nil,
                    STRING_CONTENT(326...329)("789"),
                    nil,
                    "789"
                  )],
                 STRING_END(329...330)("'")
               )]
            ),
            nil,
            nil,
            "+"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(332...333)(
       nil,
       nil,
       IDENTIFIER(332...333)("p"),
       nil,
       ArgumentsNode(334...340)(
         [CallNode(334...340)(
            nil,
            nil,
            IDENTIFIER(334...340)("snort!"),
            nil,
            nil,
            nil,
            nil,
            "snort!"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(344...345)(
       nil,
       nil,
       IDENTIFIER(344...345)("p"),
       nil,
       ArgumentsNode(360...382)(
         [CallNode(360...382)(
            InterpolatedStringNode(360...372)(
              HEREDOC_START(346...352)("<<here"),
              [StringNode(360...372)(
                 nil,
                 STRING_CONTENT(360...372)("456\r\n" + "there\r\n"),
                 nil,
                 "456\r\n" + "there\r\n"
               )],
              HEREDOC_END(372...378)("here\r\n")
            ),
            nil,
            PLUS(352...353)("+"),
            nil,
            ArgumentsNode(353...382)(
              [InterpolatedStringNode(353...382)(
                 STRING_BEGIN(353...354)("'"),
                 [StringNode(354...360)(
                    nil,
                    STRING_CONTENT(354...360)("123\\\r\n"),
                    nil,
                    "123\\\r\n"
                  ),
                  StringNode(378...381)(
                    nil,
                    STRING_CONTENT(378...381)("789"),
                    nil,
                    "789"
                  )],
                 STRING_END(381...382)("'")
               )]
            ),
            nil,
            nil,
            "+"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(384...385)(
       nil,
       nil,
       IDENTIFIER(384...385)("p"),
       nil,
       ArgumentsNode(386...392)(
         [CallNode(386...392)(
            nil,
            nil,
            IDENTIFIER(386...392)("snort!"),
            nil,
            nil,
            nil,
            nil,
            "snort!"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(396...397)(
       nil,
       nil,
       IDENTIFIER(396...397)("p"),
       nil,
       ArgumentsNode(412...434)(
         [CallNode(412...434)(
            InterpolatedStringNode(412...424)(
              HEREDOC_START(398...404)("<<here"),
              [StringNode(412...424)(
                 nil,
                 STRING_CONTENT(412...424)("456\r\n" + "there\r\n"),
                 nil,
                 "456\r\n" + "there\r\n"
               )],
              HEREDOC_END(424...430)("here\r\n")
            ),
            nil,
            PLUS(404...405)("+"),
            nil,
            ArgumentsNode(405...434)(
              [InterpolatedStringNode(405...434)(
                 STRING_BEGIN(405...406)("'"),
                 [StringNode(406...412)(
                    nil,
                    STRING_CONTENT(406...412)("123\\\r\n"),
                    nil,
                    "123\\\r\n"
                  ),
                  StringNode(430...433)(
                    nil,
                    STRING_CONTENT(430...433)("789"),
                    nil,
                    "789"
                  )],
                 STRING_END(433...434)("'")
               )]
            ),
            nil,
            nil,
            "+"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(438...439)(
       nil,
       nil,
       IDENTIFIER(438...439)("p"),
       nil,
       ArgumentsNode(453...474)(
         [CallNode(453...474)(
            InterpolatedStringNode(453...461)(
              HEREDOC_START(440...446)("<<-foo"),
              [StringNode(453...461)(
                 nil,
                 STRING_CONTENT(453...461)("  abcd\r\n"),
                 nil,
                 "  abcd\r\n"
               )],
              HEREDOC_END(461...468)("  foo\r\n")
            ),
            nil,
            PLUS(446...447)("+"),
            nil,
            ArgumentsNode(447...474)(
              [InterpolatedStringNode(447...474)(
                 STRING_BEGIN(447...448)("'"),
                 [StringNode(448...453)(
                    nil,
                    STRING_CONTENT(448...453)("123\r\n"),
                    nil,
                    "123\r\n"
                  ),
                  StringNode(468...473)(
                    nil,
                    STRING_CONTENT(468...473)("  456"),
                    nil,
                    "  456"
                  )],
                 STRING_END(473...474)("'")
               )]
            ),
            nil,
            nil,
            "+"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(476...477)(
       nil,
       nil,
       IDENTIFIER(476...477)("p"),
       nil,
       ArgumentsNode(478...483)(
         [CallNode(478...483)(
            CallNode(478...480)(
              nil,
              nil,
              IDENTIFIER(478...480)("ha"),
              nil,
              nil,
              nil,
              nil,
              "ha"
            ),
            nil,
            MINUS(480...481)("-"),
            nil,
            ArgumentsNode(481...483)(
              [CallNode(481...483)(
                 nil,
                 nil,
                 IDENTIFIER(481...483)("ha"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "ha"
               )]
            ),
            nil,
            nil,
            "-"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(487...488)(
       nil,
       nil,
       IDENTIFIER(487...488)("p"),
       nil,
       ArgumentsNode(508...542)(
         [CallNode(508...542)(
            InterpolatedStringNode(508...523)(
              HEREDOC_START(489...495)("<<-foo"),
              [StringNode(508...523)(
                 nil,
                 STRING_CONTENT(508...523)("  abcdCWECWWE\r\n"),
                 nil,
                 "  abcdCWECWWE\r\n"
               )],
              HEREDOC_END(523...530)("  foo\r\n")
            ),
            nil,
            PLUS(495...496)("+"),
            nil,
            ArgumentsNode(496...542)(
              [InterpolatedStringNode(496...542)(
                 STRING_BEGIN(496...497)("'"),
                 [StringNode(497...508)(
                    nil,
                    STRING_CONTENT(497...508)("123tyurui\r\n"),
                    nil,
                    "123tyurui\r\n"
                  ),
                  StringNode(530...541)(
                    nil,
                    STRING_CONTENT(530...541)("  456rtjmnj"),
                    nil,
                    "  456rtjmnj"
                  )],
                 STRING_END(541...542)("'")
               )]
            ),
            nil,
            nil,
            "+"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(544...545)(
       nil,
       nil,
       IDENTIFIER(544...545)("p"),
       nil,
       ArgumentsNode(546...551)(
         [CallNode(546...551)(
            CallNode(546...548)(
              nil,
              nil,
              IDENTIFIER(546...548)("ha"),
              nil,
              nil,
              nil,
              nil,
              "ha"
            ),
            nil,
            MINUS(548...549)("-"),
            nil,
            ArgumentsNode(549...551)(
              [CallNode(549...551)(
                 nil,
                 nil,
                 IDENTIFIER(549...551)("ha"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "ha"
               )]
            ),
            nil,
            nil,
            "-"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(557...558)(
       nil,
       nil,
       IDENTIFIER(557...558)("p"),
       nil,
       ArgumentsNode(559...686)(
         [InterpolatedStringNode(559...686)(
            STRING_BEGIN(559...560)("\""),
            [StringInterpolatedNode(560...685)(
               EMBEXPR_BEGIN(560...562)("\#{"),
               StatementsNode(602...600)(
                 [CallNode(602...600)(
                    InterpolatedStringNode(602...675)(
                      HEREDOC_START(562...571)("<<foobar1"),
                      [StringNode(602...675)(
                         nil,
                         STRING_CONTENT(602...675)(
                           "jbvd|g4543ghb|!@G$dfsd|fafr|e\r\n" +
                           "|s4e5rrwware|BBBBB|*&^(*&^>\"PMK:njs;d|\r\n" +
                           "\r\n"
                         ),
                         nil,
                         "jbvd|g4543ghb|!@G$dfsd|fafr|e\r\n" +
                         "|s4e5rrwware|BBBBB|*&^(*&^>\"PMK:njs;d|\r\n" +
                         "\r\n"
                       )],
                      HEREDOC_END(675...684)("foobar1\r\n")
                    ),
                    DOT(571...572)("."),
                    IDENTIFIER(572...576)("each"),
                    PARENTHESIS_LEFT(576...577)("("),
                    ArgumentsNode(577...580)(
                      [StringNode(577...580)(
                         STRING_BEGIN(577...578)("'"),
                         STRING_CONTENT(578...579)("|"),
                         STRING_END(579...580)("'"),
                         "|"
                       )]
                    ),
                    PARENTHESIS_RIGHT(580...581)(")"),
                    BlockNode(581...600)(
                      ScopeNode(581...582)([IDENTIFIER(583...584)("s")]),
                      BlockParametersNode(582...585)(
                        ParametersNode(583...584)(
                          [RequiredParameterNode(583...584)()],
                          [],
                          [],
                          nil,
                          [],
                          nil,
                          nil
                        ),
                        [],
                        (582...583),
                        (584...585)
                      ),
                      StatementsNode(586...599)(
                        [CallNode(586...599)(
                           StringNode(586...597)(
                             STRING_BEGIN(586...587)("'"),
                             STRING_CONTENT(587...596)("\\nthort: "),
                             STRING_END(596...597)("'"),
                             "\\nthort: "
                           ),
                           nil,
                           PLUS(597...598)("+"),
                           nil,
                           ArgumentsNode(598...599)(
                             [LocalVariableReadNode(598...599)(0)]
                           ),
                           nil,
                           nil,
                           "+"
                         )]
                      ),
                      (581...582),
                      (599...600)
                    ),
                    "each"
                  )]
               ),
               EMBEXPR_END(684...685)("}")
             )],
            STRING_END(685...686)("\"")
          )]
       ),
       nil,
       nil,
       "p"
     ),
     CallNode(692...693)(
       nil,
       nil,
       IDENTIFIER(692...693)("p"),
       nil,
       ArgumentsNode(709...760)(
         [CallNode(709...760)(
            InterpolatedStringNode(709...743)(
              HEREDOC_START(694...703)("<<bazquux"),
              [StringNode(709...743)(
                 nil,
                 STRING_CONTENT(709...743)(
                   "dfgnb\r\n" + "t 67sevrgvase\r\n" + "234vjvj7ui\r\n"
                 ),
                 nil,
                 "dfgnb\r\n" + "t 67sevrgvase\r\n" + "234vjvj7ui\r\n"
               )],
              HEREDOC_END(743...752)("bazquux\r\n")
            ),
            nil,
            PLUS(703...704)("+"),
            nil,
            ArgumentsNode(704...760)(
              [InterpolatedStringNode(704...760)(
                 STRING_BEGIN(704...705)("\""),
                 [StringInterpolatedNode(705...753)(
                    EMBEXPR_BEGIN(705...707)("\#{"),
                    nil,
                    EMBEXPR_END(752...753)("}")
                  ),
                  StringNode(753...759)(
                    nil,
                    STRING_CONTENT(753...759)("foobar"),
                    nil,
                    "foobar"
                  )],
                 STRING_END(759...760)("\"")
               )]
            ),
            nil,
            nil,
            "+"
          )]
       ),
       nil,
       nil,
       "p"
     )]
  )
)
