ProgramNode(0...45)(
  ScopeNode(0...0)([]),
  StatementsNode(0...45)(
    [IfNode(0...14)(
       KEYWORD_IF(0...2)("if"),
       TrueNode(3...7)(),
       StatementsNode(10...14)(
         [CallNode(10...14)(
            nil,
            nil,
            IDENTIFIER(10...14)("puts"),
            nil,
            ArgumentsNode(15...19)([IntegerNode(15...19)()]),
            nil,
            nil,
            "puts"
          )]
       ),
       nil,
       KEYWORD_END(20...23)("end")
     ),
     IfNode(26...45)(
       KEYWORD_IF_MODIFIER(38...40)("if"),
       TrueNode(41...45)(),
       StatementsNode(26...30)(
         [CallNode(26...30)(
            nil,
            nil,
            IDENTIFIER(26...30)("puts"),
            nil,
            ArgumentsNode(31...37)(
              [StringNode(31...37)(
                 STRING_BEGIN(31...32)("\""),
                 STRING_CONTENT(32...36)("1234"),
                 STRING_END(36...37)("\""),
                 "1234"
               )]
            ),
            nil,
            nil,
            "puts"
          )]
       ),
       nil,
       nil
     )]
  )
)
