ProgramNode(0...30)(
  ScopeNode(0...0)([]),
  StatementsNode(0...30)(
    [CallNode(0...30)(
       nil,
       nil,
       IDENTIFIER(0...1)("p"),
       PARENTHESIS_LEFT(1...2)("("),
       ArgumentsNode(3...12)(
         [HashNode(3...12)(
            BRACE_LEFT(2...3)("{"),
            [AssocNode(3...7)(
               IntegerNode(3...4)(),
               IntegerNode(6...7)(),
               EQUAL_GREATER(4...6)("=>")
             ),
             AssocNode(8...12)(
               IntegerNode(8...9)(),
               IntegerNode(11...12)(),
               EQUAL_GREATER(9...11)("=>")
             )],
            BRACE_RIGHT(12...13)("}")
          )]
       ),
       PARENTHESIS_RIGHT(13...14)(")"),
       BlockNode(15...30)(
         ScopeNode(15...16)([]),
         nil,
         StatementsNode(17...20)(
           [CallNode(17...20)(
              nil,
              nil,
              IDENTIFIER(17...20)("foo"),
              nil,
              ArgumentsNode(21...24)(
                [CallNode(21...24)(
                   nil,
                   nil,
                   IDENTIFIER(21...24)("bar"),
                   nil,
                   ArgumentsNode(25...28)(
                     [CallNode(25...28)(
                        nil,
                        nil,
                        IDENTIFIER(25...28)("baz"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "baz"
                      )]
                   ),
                   nil,
                   nil,
                   "bar"
                 )]
              ),
              nil,
              nil,
              "foo"
            )]
         ),
         (15...16),
         (29...30)
       ),
       "p"
     )]
  )
)
