ProgramNode(0...34)(
  ScopeNode(0...0)([]),
  StatementsNode(0...34)(
    [CallNode(0...1)(
       nil,
       nil,
       IDENTIFIER(0...1)("p"),
       nil,
       ArgumentsNode(2...12)(
         [CallNode(2...12)(
            ArrayNode(2...9)(
              [IntegerNode(3...4)(),
               IntegerNode(5...6)(),
               IntegerNode(7...8)()],
              BRACKET_LEFT_ARRAY(2...3)("["),
              BRACKET_RIGHT(8...9)("]")
            ),
            nil,
            BRACKET_LEFT_RIGHT(9...10)("["),
            BRACKET_LEFT(9...10)("["),
            ArgumentsNode(10...11)([IntegerNode(10...11)()]),
            BRACKET_RIGHT(11...12)("]"),
            nil,
            "[]"
          )]
       ),
       nil,
       nil,
       "p"
     ),
     BeginNode(13...34)(
       KEYWORD_BEGIN(13...18)("begin"),
       StatementsNode(19...23)(
         [CallNode(19...23)(
            CallNode(19...20)(
              nil,
              nil,
              IDENTIFIER(19...20)("p"),
              nil,
              nil,
              nil,
              nil,
              "p"
            ),
            nil,
            BRACKET_LEFT_RIGHT(20...21)("["),
            BRACKET_LEFT(20...21)("["),
            ArgumentsNode(21...22)([IntegerNode(21...22)()]),
            BRACKET_RIGHT(22...23)("]"),
            nil,
            "[]"
          )]
       ),
       RescueNode(24...30)(
         KEYWORD_RESCUE(24...30)("rescue"),
         [],
         nil,
         nil,
         nil,
         nil
       ),
       nil,
       nil,
       KEYWORD_END(31...34)("end")
     )]
  )
)
