ProgramNode(7...10)(
  ScopeNode(0...0)([]),
  StatementsNode(7...10)(
    [InterpolatedStringNode(7...10)(
       HEREDOC_START(0...5)("<<'E'"),
       [StringNode(7...10)(
          nil,
          STRING_CONTENT(7...10)("1\r\n"),
          nil,
          "1\r\n"
        )],
       HEREDOC_END(10...13)("E\r\n")
     )]
  )
)
