ProgramNode(0...4)(
  ScopeNode(0...0)([]),
  StatementsNode(0...4)(
    [CallNode(0...4)(
       nil,
       nil,
       IDENTIFIER(0...4)("exit"),
       nil,
       nil,
       nil,
       nil,
       "exit"
     )]
  )
)
