ProgramNode(0...49)(
  ScopeNode(0...0)([]),
  StatementsNode(0...49)(
    [IfNode(0...49)(
       KEYWORD_IF(0...2)("if"),
       FalseNode(3...8)(),
       StatementsNode(11...49)(
         [CallNode(11...14)(
            CallNode(11...12)(
              nil,
              nil,
              IDENTIFIER(11...12)("p"),
              nil,
              nil,
              nil,
              nil,
              "p"
            ),
            nil,
            PLUS(12...13)("+"),
            nil,
            ArgumentsNode(13...14)([IntegerNode(13...14)()]),
            nil,
            nil,
            "+"
          ),
          CallNode(17...20)(
            CallNode(17...18)(
              nil,
              nil,
              IDENTIFIER(17...18)("p"),
              nil,
              nil,
              nil,
              nil,
              "p"
            ),
            nil,
            AMPERSAND(18...19)("&"),
            nil,
            ArgumentsNode(19...20)([IntegerNode(19...20)()]),
            nil,
            nil,
            "&"
          ),
          CallNode(23...26)(
            CallNode(23...24)(
              nil,
              nil,
              IDENTIFIER(23...24)("p"),
              nil,
              nil,
              nil,
              nil,
              "p"
            ),
            nil,
            PIPE(24...25)("|"),
            nil,
            ArgumentsNode(25...26)([IntegerNode(25...26)()]),
            nil,
            nil,
            "|"
          ),
          CallNode(29...32)(
            CallNode(29...30)(
              nil,
              nil,
              IDENTIFIER(29...30)("p"),
              nil,
              nil,
              nil,
              nil,
              "p"
            ),
            nil,
            CARET(30...31)("^"),
            nil,
            ArgumentsNode(31...32)([IntegerNode(31...32)()]),
            nil,
            nil,
            "^"
          ),
          CallNode(35...38)(
            CallNode(35...36)(
              nil,
              nil,
              IDENTIFIER(35...36)("p"),
              nil,
              nil,
              nil,
              nil,
              "p"
            ),
            nil,
            PERCENT(36...37)("%"),
            nil,
            ArgumentsNode(37...38)([IntegerNode(37...38)()]),
            nil,
            nil,
            "%"
          ),
          CallNode(41...44)(
            CallNode(41...42)(
              nil,
              nil,
              IDENTIFIER(41...42)("p"),
              nil,
              nil,
              nil,
              nil,
              "p"
            ),
            nil,
            STAR(42...43)("*"),
            nil,
            ArgumentsNode(43...44)([IntegerNode(43...44)()]),
            nil,
            nil,
            "*"
          ),
          CallNode(48...49)(
            nil,
            nil,
            IDENTIFIER(48...49)("p"),
            nil,
            ArgumentsNode(50...53)(
              [HashNode(50...53)(
                 nil,
                 [AssocNode(50...53)(
                    SymbolNode(50...52)(
                      nil,
                      LABEL(50...51)("A"),
                      LABEL_END(51...52)(":"),
                      "A"
                    ),
                    ConstantReadNode(52...53)(),
                    nil
                  )],
                 nil
               )]
            ),
            nil,
            nil,
            "p"
          )]
       ),
       nil,
       KEYWORD_END(54...57)("end")
     )]
  )
)
