ProgramNode(2...918)(
  ScopeNode(0...0)([]),
  StatementsNode(2...918)(
    [ConstantPathWriteNode(2...47)(
       ConstantReadNode(2...21)(),
       EQUAL(22...23)("="),
       StringNode(24...47)(
         STRING_BEGIN(24...25)("'"),
         STRING_CONTENT(25...46)("<WIDGET_DESTROY_HOOK>"),
         STRING_END(46...47)("'"),
         "<WIDGET_DESTROY_HOOK>"
       )
     ),
     CallNode(50...163)(
       ConstantReadNode(50...56)(),
       DOT(56...57)("."),
       IDENTIFIER(57...76)("_invoke_without_enc"),
       PARENTHESIS_LEFT(76...77)("("),
       ArgumentsNode(77...162)(
         [StringNode(77...84)(
            STRING_BEGIN(77...78)("'"),
            STRING_CONTENT(78...83)("event"),
            STRING_END(83...84)("'"),
            "event"
          ),
          StringNode(86...91)(
            STRING_BEGIN(86...87)("'"),
            STRING_CONTENT(87...90)("add"),
            STRING_END(90...91)("'"),
            "add"
          ),
          InterpolatedStringNode(123...149)(
            STRING_BEGIN(123...124)("\""),
            [StringNode(124...125)(
               nil,
               STRING_CONTENT(124...125)("<"),
               nil,
               "<"
             ),
             StringInterpolatedNode(125...147)(
               EMBEXPR_BEGIN(125...127)("\#{"),
               StatementsNode(127...146)([ConstantReadNode(127...146)()]),
               EMBEXPR_END(146...147)("}")
             ),
             StringNode(147...148)(
               nil,
               STRING_CONTENT(147...148)(">"),
               nil,
               ">"
             )],
            STRING_END(148...149)("\"")
          ),
          StringNode(151...162)(
            STRING_BEGIN(151...152)("'"),
            STRING_CONTENT(152...161)("<Destroy>"),
            STRING_END(161...162)("'"),
            "<Destroy>"
          )]
       ),
       PARENTHESIS_RIGHT(162...163)(")"),
       nil,
       "_invoke_without_enc"
     ),
     CallNode(166...918)(
       ConstantReadNode(166...172)(),
       DOT(172...173)("."),
       IDENTIFIER(173...192)("_invoke_without_enc"),
       PARENTHESIS_LEFT(192...193)("("),
       ArgumentsNode(193...917)(
         [StringNode(193...199)(
            STRING_BEGIN(193...194)("'"),
            STRING_CONTENT(194...198)("bind"),
            STRING_END(198...199)("'"),
            "bind"
          ),
          StringNode(201...206)(
            STRING_BEGIN(201...202)("'"),
            STRING_CONTENT(202...205)("all"),
            STRING_END(205...206)("'"),
            "all"
          ),
          InterpolatedStringNode(208...234)(
            STRING_BEGIN(208...209)("\""),
            [StringNode(209...210)(
               nil,
               STRING_CONTENT(209...210)("<"),
               nil,
               "<"
             ),
             StringInterpolatedNode(210...232)(
               EMBEXPR_BEGIN(210...212)("\#{"),
               StatementsNode(212...231)([ConstantReadNode(212...231)()]),
               EMBEXPR_END(231...232)("}")
             ),
             StringNode(232...233)(
               nil,
               STRING_CONTENT(232...233)(">"),
               nil,
               ">"
             )],
            STRING_END(233...234)("\"")
          ),
          CallNode(265...917)(
            CallNode(265...908)(
              nil,
              nil,
              IDENTIFIER(265...276)("install_cmd"),
              PARENTHESIS_LEFT(276...277)("("),
              ArgumentsNode(277...907)(
                [CallNode(277...907)(
                   nil,
                   nil,
                   IDENTIFIER(277...281)("proc"),
                   nil,
                   nil,
                   nil,
                   BlockNode(281...907)(
                     ScopeNode(281...282)(
                       [IDENTIFIER(283...287)("path"),
                        IDENTIFIER(432...438)("widget"),
                        IDENTIFIER(749...750)("e")]
                     ),
                     BlockParametersNode(282...288)(
                       ParametersNode(283...287)(
                         [RequiredParameterNode(283...287)()],
                         [],
                         [],
                         nil,
                         [],
                         nil,
                         nil
                       ),
                       [],
                       (282...283),
                       (287...288)
                     ),
                     StatementsNode(321...840)(
                       [UnlessNode(321...840)(
                          KEYWORD_UNLESS(321...327)("unless"),
                          CallNode(328...351)(
                            ConstantPathNode(328...342)(
                              ConstantReadNode(328...334)(),
                              ConstantReadNode(336...342)(),
                              (334...336)
                            ),
                            DOT(342...343)("."),
                            IDENTIFIER(343...351)("deleted?"),
                            nil,
                            nil,
                            nil,
                            nil,
                            "deleted?"
                          ),
                          StatementsNode(386...840)(
                            [BeginNode(386...840)(
                               KEYWORD_BEGIN(386...391)("begin"),
                               StatementsNode(428...614)(
                                 [IfNode(428...614)(
                                    KEYWORD_IF(428...430)("if"),
                                    ParenthesesNode(431...471)(
                                      StatementsNode(432...470)(
                                        [LocalVariableWriteNode(432...470)(
                                           (432...438),
                                           CallNode(439...470)(
                                             CallNode(439...464)(
                                               ConstantPathNode(439...453)(
                                                 ConstantReadNode(439...445)(),
                                                 ConstantReadNode(447...453)(),
                                                 (445...447)
                                               ),
                                               DOT(453...454)("."),
                                               IDENTIFIER(454...464)(
                                                 "tk_windows"
                                               ),
                                               nil,
                                               nil,
                                               nil,
                                               nil,
                                               "tk_windows"
                                             ),
                                             nil,
                                             BRACKET_LEFT_RIGHT(464...465)(
                                               "["
                                             ),
                                             BRACKET_LEFT(464...465)("["),
                                             ArgumentsNode(465...469)(
                                               [LocalVariableReadNode(465...469)(
                                                  0
                                                )]
                                             ),
                                             BRACKET_RIGHT(469...470)("]"),
                                             nil,
                                             "[]"
                                           ),
                                           (438...439),
                                           0
                                         )]
                                      ),
                                      (431...432),
                                      (470...471)
                                    ),
                                    StatementsNode(510...614)(
                                      [IfNode(510...614)(
                                         KEYWORD_IF(510...512)("if"),
                                         CallNode(513...550)(
                                           LocalVariableReadNode(513...519)(0),
                                           DOT(519...520)("."),
                                           IDENTIFIER(520...531)(
                                             "respond_to?"
                                           ),
                                           PARENTHESIS_LEFT(531...532)("("),
                                           ArgumentsNode(532...549)(
                                             [SymbolNode(532...549)(
                                                SYMBOL_BEGIN(532...533)(":"),
                                                IDENTIFIER(533...549)(
                                                  "__destroy_hook__"
                                                ),
                                                nil,
                                                "__destroy_hook__"
                                              )]
                                           ),
                                           PARENTHESIS_RIGHT(549...550)(")"),
                                           nil,
                                           "respond_to?"
                                         ),
                                         StatementsNode(591...614)(
                                           [CallNode(591...614)(
                                              LocalVariableReadNode(591...597)(
                                                0
                                              ),
                                              DOT(597...598)("."),
                                              IDENTIFIER(598...614)(
                                                "__destroy_hook__"
                                              ),
                                              nil,
                                              nil,
                                              nil,
                                              nil,
                                              "__destroy_hook__"
                                            )]
                                         ),
                                         nil,
                                         KEYWORD_END(653...656)("end")
                                       )]
                                    ),
                                    nil,
                                    KEYWORD_END(693...696)("end")
                                  )]
                               ),
                               RescueNode(731...802)(
                                 KEYWORD_RESCUE(731...737)("rescue"),
                                 [ConstantReadNode(738...747)()],
                                 EQUAL_GREATER(747...749)("=>"),
                                 LocalVariableWriteNode(749...750)(
                                   (749...750),
                                   nil,
                                   nil,
                                   0
                                 ),
                                 StatementsNode(789...802)(
                                   [IfNode(789...802)(
                                      KEYWORD_IF_MODIFIER(793...795)("if"),
                                      GlobalVariableReadNode(796...802)(
                                        GLOBAL_VARIABLE(796...802)("$DEBUG")
                                      ),
                                      StatementsNode(789...790)(
                                        [CallNode(789...790)(
                                           nil,
                                           nil,
                                           IDENTIFIER(789...790)("p"),
                                           nil,
                                           ArgumentsNode(791...792)(
                                             [LocalVariableReadNode(791...792)(
                                                0
                                              )]
                                           ),
                                           nil,
                                           nil,
                                           "p"
                                         )]
                                      ),
                                      nil,
                                      nil
                                    )]
                                 ),
                                 nil
                               ),
                               nil,
                               nil,
                               KEYWORD_END(837...840)("end")
                             )]
                          ),
                          nil,
                          KEYWORD_END(873...876)("end")
                        )]
                     ),
                     (281...282),
                     (906...907)
                   ),
                   "proc"
                 )]
              ),
              PARENTHESIS_RIGHT(907...908)(")"),
              nil,
              "install_cmd"
            ),
            nil,
            LESS_LESS(909...911)("<<"),
            nil,
            ArgumentsNode(912...917)(
              [StringNode(912...917)(
                 STRING_BEGIN(912...913)("'"),
                 STRING_CONTENT(913...916)(" %W"),
                 STRING_END(916...917)("'"),
                 " %W"
               )]
            ),
            nil,
            nil,
            "<<"
          )]
       ),
       PARENTHESIS_RIGHT(917...918)(")"),
       nil,
       "_invoke_without_enc"
     )]
  )
)
