# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.4.2", engine: "jruby", engine_version: "~> 10.0.0.0"

gemspec path: "../.."

gem "parser"
gem "rake"
gem "rake-compiler"
gem "test-unit"
