# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.1.4", engine: "jruby", engine_version: "~> 9.4.5"

gemspec path: "../.."

gem "parser"
gem "rake"
gem "rake-compiler"
gem "test-unit"
