CallNode(
  CallNode(
    nil,
    nil,
    IDENTIFIER("foo"),
    nil,
    nil,
    nil,
    BlockNode(
      BlockParametersNode(
        ParametersNode(
          [RequiredParameterNode(IDENTIFIER("a"))],
          [],
          nil,
          [],
          nil,
          nil
        ),
        []
      ),
      StatementsNode([BreakNode(nil, (10..15))]),
      (4..5),
      (16..17)
    ),
    "foo"
  ),
  nil,
  EQUAL_EQUAL("=="),
  nil,
  ArgumentsNode([IntegerNode()]),
  nil,
  nil,
  "=="
)
