CallNode(
  CallNode(nil, nil, IDENTIFIER("x"), nil, nil, nil, nil, "x"),
  DOT("."),
  IDENTIFIER("reduce"),
  PARENTHESIS_LEFT("("),
  ArgumentsNode([IntegerNode()]),
  PARENTHESIS_RIGHT(")"),
  BlockNode(
    BlockParametersNode(
      ParametersNode(
        [RequiredParameterNode(IDENTIFIER("x")),
         RequiredParameterNode(IDENTIFIER("memo"))],
        [],
        nil,
        [],
        nil,
        nil
      ),
      []
    ),
    StatementsNode(
      [OperatorAssignmentNode(
         LocalVariableWriteNode(IDENTIFIER("memo"), nil, nil),
         PLUS_EQUAL("+="),
         LocalVariableReadNode(IDENTIFIER("x"))
       )]
    ),
    (12..13),
    (34..35)
  ),
  "reduce"
)
