CallNode(
  nil,
  nil,
  IDENTIFIER("foo"),
  nil,
  nil,
  nil,
  BlockNode(
    BlockParametersNode(
      ParametersNode(
        [],
        [OptionalParameterNode(
           IDENTIFIER("a"),
           EQUAL("="),
           CallNode(
             CallNode(nil, nil, IDENTIFIER("b"), nil, nil, nil, nil, "b"),
             nil,
             BRACKET_LEFT_RIGHT("["),
             BRACKET_LEFT("["),
             ArgumentsNode([IntegerNode()]),
             BRACKET_RIGHT("]"),
             nil,
             "[]"
           )
         )],
        nil,
        [],
        nil,
        nil
      ),
      []
    ),
    nil,
    (4..6),
    (18..21)
  ),
  "foo"
)
