CallNode(
  nil,
  nil,
  IDENTIFIER("foo"),
  nil,
  nil,
  nil,
  BlockNode(
    nil,
    StatementsNode(
      [CallNode(
         nil,
         nil,
         IDENTIFIER("bar"),
         nil,
         nil,
         nil,
         BlockNode(
           nil,
           StatementsNode(
             [CallNode(
                nil,
                nil,
                IDENTIFIER("baz"),
                nil,
                nil,
                nil,
                BlockNode(nil, nil, (24..26), (31..34)),
                "baz"
              )]
           ),
           (13..15),
           (37..40)
         ),
         "bar"
       )]
    ),
    (4..6),
    (41..44)
  ),
  "foo"
)
