CaseNode(
  TrueNode(),
  [WhenNode(
     KEYWORD_WHEN("when"),
     [TrueNode()],
     StatementsNode(
       [CallNode(
          nil,
          nil,
          IDENTIFIER("puts"),
          nil,
          ArgumentsNode(
            [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("hi"), nil, "hi")]
          ),
          nil,
          nil,
          "puts"
        )]
     )
   ),
   WhenNode(
     KEYWORD_WHEN("when"),
     [FalseNode()],
     StatementsNode(
       [CallNode(
          nil,
          nil,
          IDENTIFIER("puts"),
          nil,
          ArgumentsNode(
            [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("bye"), nil, "bye")]
          ),
          nil,
          nil,
          "puts"
        )]
     )
   )],
  nil,
  (0..4),
  (55..58)
)
