ClassNode(
  Scope([]),
  KEYWORD_CLASS("class"),
  ConstantReadNode(),
  nil,
  nil,
  BeginNode(
    nil,
    StatementsNode([]),
    nil,
    nil,
    EnsureNode(
      KEYWORD_ENSURE("ensure"),
      StatementsNode([]),
      KEYWORD_END("end")
    ),
    KEYWORD_END("end")
  ),
  KEYWORD_END("end")
)
