CallNode(
  nil,
  nil,
  IDENTIFIER("private"),
  nil,
  ArgumentsNode(
    [DefNode(
       IDENTIFIER("foo"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode(
         [CallNode(
            nil,
            nil,
            IDENTIFIER("bar"),
            nil,
            nil,
            nil,
            BlockNode(nil, nil, (22..24), (27..30)),
            "bar"
          )]
       ),
       Scope([]),
       (8..11),
       nil,
       nil,
       nil,
       nil,
       (31..34)
     )]
  ),
  nil,
  nil,
  "private"
)
