DefNode(
  IDENTIFIER("a"),
  nil,
  ParametersNode(
    [RequiredParameterNode(IDENTIFIER("b")),
     RequiredParameterNode(IDENTIFIER("c")),
     RequiredParameterNode(IDENTIFIER("d"))],
    [],
    nil,
    [],
    nil,
    nil
  ),
  StatementsNode([]),
  Scope([IDENTIFIER("b"), IDENTIFIER("c"), IDENTIFIER("d")]),
  (0..3),
  nil,
  nil,
  nil,
  nil,
  (14..17)
)
