IfNode(
  KEYWORD_IF("if"),
  TrueNode(),
  StatementsNode([IntegerNode()]),
  ElseNode(
    KEYWORD_ELSE("else"),
    StatementsNode([IntegerNode()]),
    KEYWORD_END("end")
  ),
  KEYWORD_END("end")
)
