CallNode(
  nil,
  nil,
  IDENTIFIER("foo"),
  nil,
  ArgumentsNode(
    [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("a"), nil, "a"),
     HashNode(
       nil,
       [AssocNode(
          SymbolNode(nil, LABEL("b"), LABEL_END(":"), "b"),
          TrueNode(),
          nil
        )],
       nil
     )]
  ),
  nil,
  BlockNode(
    BlockParametersNode(
      ParametersNode(
        [RequiredParameterNode(IDENTIFIER("a")),
         RequiredParameterNode(IDENTIFIER("b"))],
        [],
        nil,
        [],
        nil,
        nil
      ),
      []
    ),
    StatementsNode(
      [CallNode(
         nil,
         nil,
         IDENTIFIER("puts"),
         nil,
         ArgumentsNode([LocalVariableReadNode(IDENTIFIER("a"))]),
         nil,
         nil,
         "puts"
       )]
    ),
    (16..18),
    (33..36)
  ),
  "foo"
)
