DefNode(
  IDENTIFIER("a"),
  nil,
  ParametersNode([], [], nil, [], ForwardingParameterNode(), nil),
  StatementsNode(
    [InterpolatedStringNode(
       STRING_BEGIN("\""),
       [StringNode(nil, STRING_CONTENT("foo"), nil, "foo"),
        StringInterpolatedNode(
          EMBEXPR_BEGIN("\#{"),
          StatementsNode(
            [CallNode(
               nil,
               nil,
               IDENTIFIER("b"),
               PARENTHESIS_LEFT("("),
               ArgumentsNode([ForwardingArgumentsNode()]),
               PARENTHESIS_RIGHT(")"),
               nil,
               "b"
             )]
          ),
          EMBEXPR_END("}")
        )],
       STRING_END("\"")
     )]
  ),
  Scope([UDOT_DOT_DOT("...")]),
  (0..3),
  nil,
  (5..6),
  (9..10),
  nil,
  (28..31)
)
