ModuleNode(
  Scope([IDENTIFIER("x")]),
  KEYWORD_MODULE("module"),
  ConstantReadNode(),
  BeginNode(
    nil,
    StatementsNode(
      [LocalVariableWriteNode(IDENTIFIER("x"), EQUAL("="), IntegerNode())]
    ),
    RescueNode(
      KEYWORD_RESCUE("rescue"),
      [],
      nil,
      nil,
      StatementsNode([]),
      nil
    ),
    nil,
    nil,
    KEYWORD_END("end")
  ),
  KEYWORD_END("end")
)
