ArrayNode(
  [CallNode(
     RegularExpressionNode(
       REGEXP_BEGIN("/"),
       STRING_CONTENT("(?<foo>bar)"),
       REGEXP_END("/"),
       "(?<foo>bar)"
     ),
     nil,
     EQUAL_TILDE("=~"),
     nil,
     ArgumentsNode(
       [CallNode(nil, nil, IDENTIFIER("baz"), nil, nil, nil, nil, "baz")]
     ),
     nil,
     nil,
     "=~"
   ),
   LocalVariableReadNode(IDENTIFIER("foo"))],
  BRACKET_LEFT_ARRAY("["),
  BRACKET_RIGHT("]")
)
