ClassNode(
  Scope([]),
  KEYWORD_CLASS("class"),
  ConstantReadNode(),
  nil,
  nil,
  StatementsNode(
    [SingletonClassNode(
       Scope([]),
       KEYWORD_CLASS("class"),
       LESS_LESS("<<"),
       SelfNode(),
       BeginNode(
         nil,
         StatementsNode([]),
         nil,
         nil,
         EnsureNode(
           KEYWORD_ENSURE("ensure"),
           StatementsNode([]),
           KEYWORD_END("end")
         ),
         KEYWORD_END("end")
       ),
       KEYWORD_END("end")
     )]
  ),
  KEYWORD_END("end")
)
