AliasNode(
  SymbolNode(
    SYMBOL_BEGIN("%s["),
    STRING_CONTENT("abc"),
    STRING_END("]"),
    "abc"
  ),
  SymbolNode(
    SYMBOL_BEGIN("%s["),
    STRING_CONTENT("def"),
    STRING_END("]"),
    "def"
  ),
  (0..5)
)
