ProgramNode(0...578)(
  [IDENTIFIER(207...209)("ex")],
  StatementsNode(0...578)(
    [BeginNode(0...33)(
       (0...5),
       StatementsNode(7...8)(
         [CallNode(7...8)(
            nil,
            nil,
            IDENTIFIER(7...8)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(10...19)(
         (10...16),
         [],
         nil,
         nil,
         StatementsNode(18...19)(
           [CallNode(18...19)(
              nil,
              nil,
              IDENTIFIER(18...19)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         nil
       ),
       ElseNode(21...33)(
         (21...25),
         StatementsNode(27...28)(
           [CallNode(27...28)(
              nil,
              nil,
              IDENTIFIER(27...28)("c"),
              nil,
              nil,
              nil,
              nil,
              "c"
            )]
         ),
         (30...33)
       ),
       nil,
       (30...33)
     ),
     BeginNode(35...79)(
       (35...40),
       StatementsNode(42...43)(
         [CallNode(42...43)(
            nil,
            nil,
            IDENTIFIER(42...43)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(45...54)(
         (45...51),
         [],
         nil,
         nil,
         StatementsNode(53...54)(
           [CallNode(53...54)(
              nil,
              nil,
              IDENTIFIER(53...54)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         nil
       ),
       ElseNode(56...71)(
         (56...60),
         StatementsNode(62...63)(
           [CallNode(62...63)(
              nil,
              nil,
              IDENTIFIER(62...63)("c"),
              nil,
              nil,
              nil,
              nil,
              "c"
            )]
         ),
         (65...71)
       ),
       EnsureNode(65...79)(
         (65...71),
         StatementsNode(73...74)(
           [CallNode(73...74)(
              nil,
              nil,
              IDENTIFIER(73...74)("d"),
              nil,
              nil,
              nil,
              nil,
              "d"
            )]
         ),
         (76...79)
       ),
       (76...79)
     ),
     BeginNode(81...92)(
       (81...86),
       StatementsNode(87...88)(
         [CallNode(87...88)(
            nil,
            nil,
            IDENTIFIER(87...88)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       nil,
       nil,
       nil,
       (89...92)
     ),
     BeginNode(94...107)(
       (94...99),
       StatementsNode(101...102)(
         [CallNode(101...102)(
            nil,
            nil,
            IDENTIFIER(101...102)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       nil,
       nil,
       nil,
       (104...107)
     ),
     BeginNode(109...121)(
       (109...114),
       StatementsNode(115...116)(
         [CallNode(115...116)(
            nil,
            nil,
            IDENTIFIER(115...116)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       nil,
       nil,
       nil,
       (118...121)
     ),
     BeginNode(123...135)(
       (123...128),
       StatementsNode(129...130)(
         [CallNode(129...130)(
            nil,
            nil,
            IDENTIFIER(129...130)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       nil,
       nil,
       nil,
       (132...135)
     ),
     BeginNode(137...175)(
       (137...142),
       StatementsNode(143...144)(
         [CallNode(143...144)(
            nil,
            nil,
            IDENTIFIER(143...144)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(145...162)(
         (145...151),
         [],
         nil,
         nil,
         StatementsNode(152...153)(
           [CallNode(152...153)(
              nil,
              nil,
              IDENTIFIER(152...153)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         RescueNode(154...171)(
           (154...160),
           [],
           nil,
           nil,
           StatementsNode(161...162)(
             [CallNode(161...162)(
                nil,
                nil,
                IDENTIFIER(161...162)("c"),
                nil,
                nil,
                nil,
                nil,
                "c"
              )]
           ),
           RescueNode(163...171)(
             (163...169),
             [],
             nil,
             nil,
             StatementsNode(170...171)(
               [CallNode(170...171)(
                  nil,
                  nil,
                  IDENTIFIER(170...171)("d"),
                  nil,
                  nil,
                  nil,
                  nil,
                  "d"
                )]
             ),
             nil
           )
         )
       ),
       nil,
       nil,
       (172...175)
     ),
     BeginNode(177...269)(
       (177...182),
       StatementsNode(185...186)(
         [CallNode(185...186)(
            nil,
            nil,
            IDENTIFIER(185...186)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(187...265)(
         (187...193),
         [ConstantReadNode(194...203)()],
         (204...206),
         LocalVariableWriteNode(207...209)((207...209), nil, nil, 0),
         StatementsNode(212...213)(
           [CallNode(212...213)(
              nil,
              nil,
              IDENTIFIER(212...213)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         RescueNode(214...265)(
           (214...220),
           [ConstantReadNode(221...237)(), ConstantReadNode(239...255)()],
           (256...258),
           LocalVariableWriteNode(259...261)((259...261), nil, nil, 0),
           StatementsNode(264...265)(
             [CallNode(264...265)(
                nil,
                nil,
                IDENTIFIER(264...265)("c"),
                nil,
                nil,
                nil,
                nil,
                "c"
              )]
           ),
           nil
         )
       ),
       nil,
       nil,
       (266...269)
     ),
     BeginNode(271...322)(
       (271...276),
       StatementsNode(279...280)(
         [CallNode(279...280)(
            nil,
            nil,
            IDENTIFIER(279...280)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(281...307)(
         (281...287),
         [ConstantReadNode(288...297)()],
         (298...300),
         LocalVariableWriteNode(301...303)((301...303), nil, nil, 0),
         StatementsNode(306...307)(
           [CallNode(306...307)(
              nil,
              nil,
              IDENTIFIER(306...307)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         nil
       ),
       nil,
       EnsureNode(308...322)(
         (308...314),
         StatementsNode(317...318)(
           [CallNode(317...318)(
              nil,
              nil,
              IDENTIFIER(317...318)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         (319...322)
       ),
       (319...322)
     ),
     StringNode(324...330)((324...326), (326...329), (329...330), "abc"),
     BeginNode(332...352)(
       (332...337),
       StatementsNode(338...339)(
         [CallNode(338...339)(
            nil,
            nil,
            IDENTIFIER(338...339)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(340...348)(
         (340...346),
         [],
         nil,
         nil,
         StatementsNode(347...348)(
           [CallNode(347...348)(
              nil,
              nil,
              IDENTIFIER(347...348)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         nil
       ),
       nil,
       nil,
       (349...352)
     ),
     BeginNode(354...374)(
       (354...359),
       StatementsNode(360...361)(
         [CallNode(360...361)(
            nil,
            nil,
            IDENTIFIER(360...361)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(362...370)(
         (362...368),
         [],
         nil,
         nil,
         StatementsNode(369...370)(
           [CallNode(369...370)(
              nil,
              nil,
              IDENTIFIER(369...370)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         nil
       ),
       nil,
       nil,
       (371...374)
     ),
     BeginNode(376...396)(
       (376...381),
       StatementsNode(382...383)(
         [CallNode(382...383)(
            nil,
            nil,
            IDENTIFIER(382...383)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(384...392)(
         (384...390),
         [],
         nil,
         nil,
         StatementsNode(391...392)(
           [CallNode(391...392)(
              nil,
              nil,
              IDENTIFIER(391...392)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         nil
       ),
       nil,
       nil,
       (393...396)
     ),
     BeginNode(398...428)(
       (398...403),
       StatementsNode(404...405)(
         [CallNode(404...405)(
            nil,
            nil,
            IDENTIFIER(404...405)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(406...424)(
         (406...412),
         [ConstantReadNode(413...422)()],
         nil,
         nil,
         StatementsNode(423...424)(
           [CallNode(423...424)(
              nil,
              nil,
              IDENTIFIER(423...424)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         nil
       ),
       nil,
       nil,
       (425...428)
     ),
     BeginNode(430...477)(
       (430...435),
       StatementsNode(436...437)(
         [CallNode(436...437)(
            nil,
            nil,
            IDENTIFIER(436...437)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(438...473)(
         (438...444),
         [ConstantReadNode(445...454)(), ConstantReadNode(456...471)()],
         nil,
         nil,
         StatementsNode(472...473)(
           [CallNode(472...473)(
              nil,
              nil,
              IDENTIFIER(472...473)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         nil
       ),
       nil,
       nil,
       (474...477)
     ),
     BeginNode(479...536)(
       (479...484),
       StatementsNode(487...488)(
         [CallNode(487...488)(
            nil,
            nil,
            IDENTIFIER(487...488)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(489...532)(
         (489...495),
         [ConstantReadNode(496...505)(), ConstantReadNode(507...522)()],
         (523...525),
         LocalVariableWriteNode(526...528)((526...528), nil, nil, 0),
         StatementsNode(531...532)(
           [CallNode(531...532)(
              nil,
              nil,
              IDENTIFIER(531...532)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         nil
       ),
       nil,
       nil,
       (533...536)
     ),
     BeginNode(538...578)(
       (538...543),
       StatementsNode(546...547)(
         [CallNode(546...547)(
            nil,
            nil,
            IDENTIFIER(546...547)("a"),
            nil,
            nil,
            nil,
            nil,
            "a"
          )]
       ),
       RescueNode(548...574)(
         (548...554),
         [ConstantReadNode(555...564)()],
         (565...567),
         LocalVariableWriteNode(568...570)((568...570), nil, nil, 0),
         StatementsNode(573...574)(
           [CallNode(573...574)(
              nil,
              nil,
              IDENTIFIER(573...574)("b"),
              nil,
              nil,
              nil,
              nil,
              "b"
            )]
         ),
         nil
       ),
       nil,
       nil,
       (575...578)
     )]
  )
)
