ProgramNode(
  Scope([IDENTIFIER("fork")]),
  StatementsNode(
    [CallNode(
       CallNode(nil, nil, IDENTIFIER("foo"), nil, nil, nil, nil, "foo"),
       nil,
       BRACKET_LEFT_RIGHT("["),
       BRACKET_LEFT("["),
       ArgumentsNode(
         [CallNode(nil, nil, IDENTIFIER("bar"), nil, nil, nil, nil, "bar")]
       ),
       BRACKET_RIGHT("]"),
       BlockNode(
         Scope([]),
         nil,
         StatementsNode(
           [CallNode(nil, nil, IDENTIFIER("baz"), nil, nil, nil, nil, "baz")]
         ),
         (9..10),
         (15..16)
       ),
       "[]"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("foo"), nil, nil, nil, nil, "foo"),
       nil,
       BRACKET_LEFT_RIGHT("["),
       BRACKET_LEFT("["),
       ArgumentsNode(
         [CallNode(nil, nil, IDENTIFIER("bar"), nil, nil, nil, nil, "bar")]
       ),
       BRACKET_RIGHT("]"),
       BlockNode(
         Scope([]),
         nil,
         StatementsNode(
           [CallNode(nil, nil, IDENTIFIER("baz"), nil, nil, nil, nil, "baz")]
         ),
         (27..29),
         (34..37)
       ),
       "[]"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("x"), nil, nil, nil, nil, "x"),
       DOT("."),
       IDENTIFIER("reduce"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode([IntegerNode()]),
       PARENTHESIS_RIGHT(")"),
       BlockNode(
         Scope([IDENTIFIER("x"), IDENTIFIER("memo")]),
         BlockParametersNode(
           ParametersNode(
             [RequiredParameterNode(IDENTIFIER("x")),
              RequiredParameterNode(IDENTIFIER("memo"))],
             [],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         StatementsNode(
           [OperatorAssignmentNode(
              LocalVariableWriteNode(IDENTIFIER("memo"), nil, nil, 0),
              PLUS_EQUAL("+="),
              LocalVariableReadNode(IDENTIFIER("x"), 0)
            )]
         ),
         (51..52),
         (73..74)
       ),
       "reduce"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       nil,
       nil,
       BlockNode(Scope([]), nil, nil, (80..82), (83..86)),
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       ArgumentsNode(
         [CallNode(nil, nil, IDENTIFIER("bar"), nil, nil, nil, nil, "bar"),
          ParenthesesNode(
            StatementsNode(
              [CallNode(
                 nil,
                 nil,
                 IDENTIFIER("baz"),
                 nil,
                 nil,
                 nil,
                 BlockNode(Scope([]), nil, nil, (102..104), (105..108)),
                 "baz"
               )]
            ),
            (97..98),
            (108..109)
          )]
       ),
       nil,
       nil,
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       ArgumentsNode(
         [CallNode(nil, nil, IDENTIFIER("bar"), nil, nil, nil, nil, "bar")]
       ),
       nil,
       BlockNode(Scope([]), nil, nil, (119..121), (122..125)),
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       ArgumentsNode(
         [CallNode(
            nil,
            nil,
            IDENTIFIER("bar"),
            nil,
            ArgumentsNode(
              [CallNode(
                 nil,
                 nil,
                 IDENTIFIER("baz"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "baz"
               )]
            ),
            nil,
            nil,
            "bar"
          )]
       ),
       nil,
       BlockNode(Scope([]), nil, nil, (139..141), (142..145)),
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       nil,
       nil,
       BlockNode(
         Scope([IDENTIFIER("a")]),
         BlockParametersNode(
           ParametersNode(
             [],
             [OptionalParameterNode(
                IDENTIFIER("a"),
                EQUAL("="),
                CallNode(
                  CallNode(nil, nil, IDENTIFIER("b"), nil, nil, nil, nil, "b"),
                  nil,
                  BRACKET_LEFT_RIGHT("["),
                  BRACKET_LEFT("["),
                  ArgumentsNode([IntegerNode()]),
                  BRACKET_RIGHT("]"),
                  nil,
                  "[]"
                )
              )],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         nil,
         (151..153),
         (165..168)
       ),
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       nil,
       nil,
       BlockNode(
         Scope([]),
         nil,
         BeginNode(
           nil,
           StatementsNode([]),
           RescueNode(
             KEYWORD_RESCUE("rescue"),
             [],
             nil,
             nil,
             StatementsNode([]),
             nil
           ),
           nil,
           nil,
           KEYWORD_END("end")
         ),
         (174..176),
         (184..187)
       ),
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       nil,
       nil,
       BlockNode(
         Scope([]),
         nil,
         StatementsNode(
           [CallNode(
              nil,
              nil,
              IDENTIFIER("bar"),
              nil,
              nil,
              nil,
              BlockNode(
                Scope([]),
                nil,
                StatementsNode(
                  [CallNode(
                     nil,
                     nil,
                     IDENTIFIER("baz"),
                     nil,
                     nil,
                     nil,
                     BlockNode(Scope([]), nil, nil, (213..215), (220..223)),
                     "baz"
                   )]
                ),
                (202..204),
                (226..229)
              ),
              "bar"
            )]
         ),
         (193..195),
         (230..233)
       ),
       "foo"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("foo"), nil, nil, nil, nil, "foo"),
       nil,
       BRACKET_LEFT_RIGHT("["),
       BRACKET_LEFT("["),
       ArgumentsNode(
         [CallNode(nil, nil, IDENTIFIER("bar"), nil, nil, nil, nil, "bar")]
       ),
       BRACKET_RIGHT("]"),
       BlockNode(
         Scope([]),
         nil,
         StatementsNode(
           [CallNode(nil, nil, IDENTIFIER("baz"), nil, nil, nil, nil, "baz")]
         ),
         (244..245),
         (250..251)
       ),
       "[]"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       nil,
       nil,
       BlockNode(
         Scope([IDENTIFIER("x"), IDENTIFIER("y"), LABEL("z")]),
         BlockParametersNode(
           ParametersNode(
             [RequiredParameterNode(IDENTIFIER("x"))],
             [OptionalParameterNode(
                IDENTIFIER("y"),
                EQUAL("="),
                IntegerNode()
              )],
             nil,
             [KeywordParameterNode(LABEL("z:"), nil)],
             nil,
             nil
           ),
           []
         ),
         StatementsNode([LocalVariableReadNode(IDENTIFIER("x"), 0)]),
         (257..258),
         (276..277)
       ),
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       nil,
       nil,
       BlockNode(
         Scope([IDENTIFIER("x")]),
         BlockParametersNode(
           ParametersNode(
             [RequiredParameterNode(IDENTIFIER("x"))],
             [],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         nil,
         (283..284),
         (289..290)
       ),
       "foo"
     ),
     LocalVariableWriteNode(IDENTIFIER("fork"), EQUAL("="), IntegerNode(), 0),
     CallNode(
       nil,
       nil,
       IDENTIFIER("fork"),
       nil,
       nil,
       nil,
       BlockNode(
         Scope([IDENTIFIER("a")]),
         BlockParametersNode(
           ParametersNode(
             [RequiredParameterNode(IDENTIFIER("a"))],
             [],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         nil,
         (306..308),
         (313..316)
       ),
       "fork"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("fork"),
       nil,
       nil,
       nil,
       BlockNode(
         Scope([IDENTIFIER("a")]),
         BlockParametersNode(
           ParametersNode(
             [RequiredParameterNode(IDENTIFIER("a"))],
             [],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         nil,
         (323..324),
         (329..330)
       ),
       "fork"
     ),
     CallNode(
       nil,
       nil,
       CONSTANT("C"),
       nil,
       nil,
       nil,
       BlockNode(Scope([]), nil, nil, (334..336), (337..340)),
       "C"
     ),
     CallNode(
       nil,
       nil,
       CONSTANT("C"),
       nil,
       nil,
       nil,
       BlockNode(Scope([]), nil, nil, (344..345), (345..346)),
       "C"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       ArgumentsNode(
         [CallNode(
            nil,
            nil,
            IDENTIFIER("lambda"),
            nil,
            nil,
            nil,
            BlockNode(
              Scope([LABEL("a"), LABEL("b")]),
              BlockParametersNode(
                ParametersNode(
                  [],
                  [],
                  nil,
                  [KeywordParameterNode(LABEL("a:"), IntegerNode()),
                   KeywordParameterNode(LABEL("b:"), IntegerNode())],
                  nil,
                  nil
                ),
                []
              ),
              nil,
              (359..360),
              (382..383)
            ),
            "lambda"
          )]
       ),
       nil,
       nil,
       "foo"
     )]
  )
)
