ProgramNode(0...6)(
  ScopeNode(0...0)([]),
  StatementsNode(0...6)(
    [InterpolatedStringNode(0...6)(
       HEREDOC_START(0...6)("<<-END"),
       [],
       HEREDOC_END(7...10)("END")
     )]
  )
)
