ProgramNode(0...51)(
  ScopeNode(0...0)([]),
  StatementsNode(0...51)(
    [RedoNode(0...4)(),
     RetryNode(6...11)(),
     SelfNode(13...17)(),
     SourceEncodingNode(19...31)(),
     SourceFileNode(33...41)(
       KEYWORD___FILE__(33...41)("__FILE__"),
       "/fixtures/keywords.rb"
     ),
     SourceLineNode(43...51)()]
  )
)
