ProgramNode(
  Scope([]),
  StatementsNode(
    [DefNode(
       KEYWORD_DEF("def"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (0..3),
       nil,
       nil,
       nil,
       nil,
       (8..11)
     ),
     DefNode(
       KEYWORD_ENSURE("ensure"),
       SelfNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (13..16),
       (21..22),
       nil,
       nil,
       nil,
       (29..32)
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("private"),
       nil,
       ArgumentsNode(
         [DefNode(
            IDENTIFIER("foo"),
            nil,
            ParametersNode([], [], nil, [], nil, nil),
            StatementsNode(
              [CallNode(
                 nil,
                 nil,
                 IDENTIFIER("bar"),
                 nil,
                 nil,
                 nil,
                 BlockNode(Scope([]), nil, nil, (56..58), (61..64)),
                 "bar"
               )]
            ),
            Scope([]),
            (42..45),
            nil,
            nil,
            nil,
            nil,
            (65..68)
          )]
       ),
       nil,
       nil,
       "private"
     ),
     DefNode(
       IDENTIFIER("m"),
       nil,
       ParametersNode(
         [RequiredParameterNode(IDENTIFIER("a"))],
         [],
         nil,
         [],
         NoKeywordsParameterNode((79..81), (81..84)),
         nil
       ),
       StatementsNode([]),
       Scope([IDENTIFIER("a")]),
       (70..73),
       nil,
       (75..76),
       (84..85),
       nil,
       (86..89)
     ),
     DefNode(
       IDENTIFIER("a"),
       SourceEncodingNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (91..94),
       (107..108),
       nil,
       nil,
       nil,
       (110..113)
     ),
     StringNode(
       STRING_BEGIN("%{"),
       STRING_CONTENT("abc"),
       STRING_END("}"),
       "abc"
     ),
     StringNode(
       STRING_BEGIN("%\""),
       STRING_CONTENT("abc"),
       STRING_END("\""),
       "abc"
     ),
     DefNode(
       IDENTIFIER("a"),
       SourceFileNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (131..134),
       (143..144),
       nil,
       nil,
       nil,
       (146..149)
     ),
     DefNode(
       IDENTIFIER("a"),
       SourceLineNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (151..154),
       (163..164),
       nil,
       nil,
       nil,
       (166..169)
     ),
     DefNode(
       IDENTIFIER("a"),
       NilNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (171..174),
       (178..180),
       nil,
       nil,
       nil,
       (182..185)
     )]
  )
)
