ProgramNode(0...0)(
  Scope(0...0)([]),
  StatementsNode(0...0)(
    [LambdaNode(0...0)(
       Scope(0...2)([IDENTIFIER(6...9)("foo")]),
       MINUS_GREATER(0...2)("->"),
       PARENTHESIS_LEFT(2...3)("("),
       BlockParametersNode(6...9)(
         ParametersNode(6...9)(
           [RequiredParameterNode(6...9)(IDENTIFIER(6...9)("foo"))],
           [],
           nil,
           [],
           nil,
           nil
         ),
         []
       ),
       PARENTHESIS_RIGHT(10...11)(")"),
       StatementsNode(0...0)([])
     ),
     LambdaNode(16...0)(
       Scope(16...18)([LABEL(19...20)("x")]),
       MINUS_GREATER(16...18)("->"),
       PARENTHESIS_LEFT(18...19)("("),
       BlockParametersNode(19...29)(
         ParametersNode(19...29)(
           [],
           [],
           nil,
           [KeywordParameterNode(19...29)(
              LABEL(19...21)("x:"),
              InterpolatedStringNode(22...29)(
                STRING_BEGIN(22...23)("\""),
                [StringNode(23...24)(
                   nil,
                   STRING_CONTENT(23...24)("b"),
                   nil,
                   "b"
                 ),
                 StringInterpolatedNode(24...28)(
                   EMBEXPR_BEGIN(24...26)("\#{"),
                   StatementsNode(26...27)(
                     [CallNode(26...27)(
                        nil,
                        nil,
                        IDENTIFIER(26...27)("a"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "a"
                      )]
                   ),
                   EMBEXPR_END(27...28)("}")
                 )],
                STRING_END(28...29)("\"")
              )
            )],
           nil,
           nil
         ),
         []
       ),
       PARENTHESIS_RIGHT(29...30)(")"),
       StatementsNode(0...0)([])
     )]
  )
)
