ProgramNode(
  Scope([IDENTIFIER("a"), IDENTIFIER("c")]),
  StatementsNode(
    [DefNode(
       IDENTIFIER("foo"),
       nil,
       ParametersNode(
         [RequiredDestructuredParameterNode(
            [RequiredParameterNode(IDENTIFIER("bar")),
             RequiredParameterNode(IDENTIFIER("baz"))],
            PARENTHESIS_LEFT("("),
            PARENTHESIS_RIGHT(")")
          )],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([IDENTIFIER("bar"), IDENTIFIER("baz")]),
       (0..3),
       nil,
       (7..8),
       (18..19),
       nil,
       (20..23)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       BeginNode(
         nil,
         StatementsNode([]),
         nil,
         nil,
         EnsureNode(
           KEYWORD_ENSURE("ensure"),
           StatementsNode([]),
           KEYWORD_END("end")
         ),
         KEYWORD_END("end")
       ),
       Scope([]),
       (25..28),
       nil,
       nil,
       nil,
       nil,
       (40..43)
     ),
     DefNode(
       IDENTIFIER("a"),
       ParenthesesNode(
         CallNode(nil, nil, IDENTIFIER("b"), nil, nil, nil, nil, "b"),
         (49..50),
         (51..52)
       ),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (45..48),
       (52..53),
       nil,
       nil,
       nil,
       (55..58)
     ),
     DefNode(
       IDENTIFIER("b"),
       ParenthesesNode(
         CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
         (64..65),
         (66..67)
       ),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (60..63),
       (67..69),
       nil,
       nil,
       nil,
       (71..74)
     ),
     DefNode(
       IDENTIFIER("a"),
       FalseNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (76..79),
       (85..86),
       nil,
       nil,
       nil,
       (88..91)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode([], [], nil, [], ForwardingParameterNode(), nil),
       StatementsNode([]),
       Scope([UDOT_DOT_DOT("...")]),
       (93..96),
       nil,
       (98..99),
       (102..103),
       nil,
       (104..107)
     ),
     DefNode(
       IDENTIFIER("a"),
       GlobalVariableReadNode(GLOBAL_VARIABLE("$var")),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (109..112),
       (117..118),
       nil,
       nil,
       nil,
       (120..123)
     ),
     DefNode(
       IDENTIFIER("b"),
       CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (125..128),
       (130..131),
       nil,
       nil,
       nil,
       (133..136)
     ),
     DefNode(
       IDENTIFIER("a"),
       InstanceVariableReadNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (138..141),
       (146..147),
       nil,
       nil,
       nil,
       (149..152)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         nil,
         [KeywordParameterNode(LABEL("b:"), nil)],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([LABEL("b")]),
       (154..157),
       nil,
       nil,
       nil,
       nil,
       (164..167)
     ),
     StringNode(
       STRING_BEGIN("%,"),
       STRING_CONTENT("abc"),
       STRING_END(","),
       "abc"
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         nil,
         [KeywordParameterNode(LABEL("b:"), nil)],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([LABEL("b")]),
       (177..180),
       nil,
       (182..183),
       (185..186),
       nil,
       (187..190)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         nil,
         [],
         KeywordRestParameterNode(STAR_STAR("**"), IDENTIFIER("b")),
         nil
       ),
       StatementsNode([]),
       Scope([IDENTIFIER("b")]),
       (192..195),
       nil,
       (197..198),
       (201..202),
       nil,
       (203..206)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         nil,
         [],
         KeywordRestParameterNode(STAR_STAR("**"), nil),
         nil
       ),
       StatementsNode([]),
       Scope([]),
       (208..211),
       nil,
       (213..214),
       (216..217),
       nil,
       (218..221)
     ),
     DefNode(
       IDENTIFIER("a"),
       ParenthesesNode(IntegerNode(), (227..228), (229..230)),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (223..226),
       (230..231),
       nil,
       nil,
       nil,
       (233..236)
     ),
     LocalVariableWriteNode(IDENTIFIER("a"), EQUAL("="), IntegerNode(), 0),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (245..248),
       nil,
       nil,
       nil,
       nil,
       (251..254)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [RequiredParameterNode(IDENTIFIER("b")),
          RequiredParameterNode(IDENTIFIER("c")),
          RequiredParameterNode(IDENTIFIER("d"))],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([IDENTIFIER("b"), IDENTIFIER("c"), IDENTIFIER("d")]),
       (256..259),
       nil,
       nil,
       nil,
       nil,
       (270..273)
     ),
     DefNode(
       IDENTIFIER("a"),
       NilNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (275..278),
       (282..283),
       nil,
       nil,
       nil,
       (285..288)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         nil,
         [KeywordParameterNode(LABEL("b:"), nil),
          KeywordParameterNode(LABEL("c:"), IntegerNode())],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([LABEL("b"), LABEL("c")]),
       (290..293),
       nil,
       nil,
       nil,
       nil,
       (305..308)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         nil,
         [KeywordParameterNode(LABEL("b:"), nil),
          KeywordParameterNode(LABEL("c:"), IntegerNode())],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([LABEL("b"), LABEL("c")]),
       (310..313),
       nil,
       (315..316),
       (324..325),
       nil,
       (326..329)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         nil,
         [KeywordParameterNode(LABEL("b:"), IntegerNode()),
          KeywordParameterNode(LABEL("c:"), nil)],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([LABEL("b"), LABEL("c")]),
       (331..334),
       nil,
       (336..337),
       (347..348),
       nil,
       (349..352)
     ),
     StringNode(
       STRING_BEGIN("%."),
       STRING_CONTENT("abc"),
       STRING_END("."),
       "abc"
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [OptionalParameterNode(IDENTIFIER("b"), EQUAL("="), IntegerNode()),
          OptionalParameterNode(IDENTIFIER("c"), EQUAL("="), IntegerNode())],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([IDENTIFIER("b"), IDENTIFIER("c")]),
       (362..365),
       nil,
       nil,
       nil,
       nil,
       (381..384)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (386..389),
       nil,
       (391..392),
       (392..393),
       nil,
       (394..397)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [RequiredParameterNode(IDENTIFIER("b"))],
         [OptionalParameterNode(IDENTIFIER("c"), EQUAL("="), IntegerNode())],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([IDENTIFIER("b"), IDENTIFIER("c")]),
       (399..402),
       nil,
       nil,
       nil,
       nil,
       (414..417)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [RequiredParameterNode(IDENTIFIER("b"))],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([IDENTIFIER("b")]),
       (419..422),
       nil,
       nil,
       nil,
       nil,
       (427..430)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       BeginNode(
         nil,
         StatementsNode([]),
         RescueNode(
           KEYWORD_RESCUE("rescue"),
           [],
           nil,
           nil,
           StatementsNode([]),
           nil
         ),
         ElseNode(KEYWORD_ELSE("else"), StatementsNode([]), SEMICOLON(";")),
         EnsureNode(
           KEYWORD_ENSURE("ensure"),
           StatementsNode([]),
           KEYWORD_END("end")
         ),
         KEYWORD_END("end")
       ),
       Scope([]),
       (432..435),
       nil,
       nil,
       nil,
       nil,
       (461..464)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         RestParameterNode(STAR("*"), IDENTIFIER("b")),
         [],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([IDENTIFIER("b")]),
       (466..469),
       nil,
       nil,
       nil,
       nil,
       (475..478)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         RestParameterNode(USTAR("*"), nil),
         [],
         nil,
         nil
       ),
       StatementsNode([]),
       Scope([USTAR("*")]),
       (480..483),
       nil,
       (485..486),
       (487..488),
       nil,
       (489..492)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode(
         [LocalVariableWriteNode(
            IDENTIFIER("b"),
            EQUAL("="),
            IntegerNode(),
            0
          )]
       ),
       Scope([IDENTIFIER("b")]),
       (494..497),
       nil,
       nil,
       nil,
       nil,
       (506..509)
     ),
     DefNode(
       IDENTIFIER("a"),
       SelfNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (511..514),
       (519..520),
       nil,
       nil,
       nil,
       (522..525)
     ),
     DefNode(
       IDENTIFIER("a"),
       TrueNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (527..530),
       (535..536),
       nil,
       nil,
       nil,
       (538..541)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (543..546),
       nil,
       nil,
       nil,
       nil,
       (549..552)
     ),
     DefNode(
       IDENTIFIER("hi"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode(
         [IfNode(
            KEYWORD_IF_MODIFIER("if"),
            TrueNode(),
            StatementsNode(
              [ReturnNode(
                 KEYWORD_RETURN("return"),
                 ArgumentsNode(
                   [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("hi"), nil, "hi")]
                 )
               )]
            ),
            nil,
            nil
          ),
          SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("bye"), nil, "bye")]
       ),
       Scope([]),
       (554..557),
       nil,
       nil,
       nil,
       nil,
       (585..588)
     ),
     DefNode(
       IDENTIFIER("foo"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([IntegerNode()]),
       Scope([]),
       (590..593),
       nil,
       nil,
       nil,
       (598..599),
       nil
     ),
     DefNode(
       IDENTIFIER("bar"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([IntegerNode()]),
       Scope([]),
       (602..605),
       nil,
       nil,
       nil,
       (610..611),
       nil
     ),
     DefNode(
       IDENTIFIER("foo"),
       nil,
       ParametersNode(
         [RequiredParameterNode(IDENTIFIER("bar"))],
         [],
         nil,
         [],
         nil,
         nil
       ),
       StatementsNode([IntegerNode()]),
       Scope([IDENTIFIER("bar")]),
       (615..618),
       nil,
       (622..623),
       (626..627),
       (628..629),
       nil
     ),
     DefNode(
       IDENTIFIER("foo"),
       nil,
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([IntegerNode()]),
       Scope([]),
       (635..638),
       nil,
       nil,
       nil,
       (643..644),
       nil
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         RestParameterNode(USTAR("*"), nil),
         [],
         nil,
         nil
       ),
       StatementsNode(
         [CallNode(
            nil,
            nil,
            IDENTIFIER("b"),
            PARENTHESIS_LEFT("("),
            ArgumentsNode([SplatNode(USTAR("*"), nil)]),
            PARENTHESIS_RIGHT(")"),
            nil,
            "b"
          )]
       ),
       Scope([USTAR("*")]),
       (650..653),
       nil,
       (655..656),
       (657..658),
       nil,
       (666..669)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode([], [], nil, [], ForwardingParameterNode(), nil),
       StatementsNode(
         [CallNode(
            nil,
            nil,
            IDENTIFIER("b"),
            PARENTHESIS_LEFT("("),
            ArgumentsNode([ForwardingArgumentsNode()]),
            PARENTHESIS_RIGHT(")"),
            nil,
            "b"
          )]
       ),
       Scope([UDOT_DOT_DOT("...")]),
       (671..674),
       nil,
       (676..677),
       (680..681),
       nil,
       (691..694)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode([], [], nil, [], ForwardingParameterNode(), nil),
       StatementsNode(
         [CallNode(
            nil,
            nil,
            IDENTIFIER("b"),
            PARENTHESIS_LEFT("("),
            ArgumentsNode(
              [IntegerNode(), IntegerNode(), ForwardingArgumentsNode()]
            ),
            PARENTHESIS_RIGHT(")"),
            nil,
            "b"
          )]
       ),
       Scope([UDOT_DOT_DOT("...")]),
       (696..699),
       nil,
       (701..702),
       (705..706),
       nil,
       (722..725)
     ),
     DefNode(
       IDENTIFIER("a"),
       ParenthesesNode(
         LocalVariableWriteNode(
           IDENTIFIER("c"),
           EQUAL("="),
           CallNode(nil, nil, IDENTIFIER("b"), nil, nil, nil, nil, "b"),
           0
         ),
         (731..732),
         (737..738)
       ),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (727..730),
       (738..739),
       nil,
       nil,
       nil,
       (741..744)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         nil,
         [],
         nil,
         BlockParameterNode(IDENTIFIER("b"), (752..753))
       ),
       StatementsNode([]),
       Scope([IDENTIFIER("b")]),
       (746..749),
       nil,
       nil,
       nil,
       nil,
       (755..758)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode(
         [],
         [],
         nil,
         [],
         nil,
         BlockParameterNode(nil, (766..767))
       ),
       StatementsNode([]),
       Scope([]),
       (760..763),
       nil,
       (765..766),
       (767..768),
       nil,
       (769..772)
     ),
     DefNode(
       IDENTIFIER("a"),
       ClassVariableReadNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (774..777),
       (783..784),
       nil,
       nil,
       nil,
       (786..789)
     ),
     DefNode(
       CONSTANT("C"),
       ParenthesesNode(
         LocalVariableWriteNode(
           IDENTIFIER("a"),
           EQUAL("="),
           CallNode(nil, nil, IDENTIFIER("b"), nil, nil, nil, nil, "b"),
           0
         ),
         (795..796),
         (801..802)
       ),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (791..794),
       (802..803),
       nil,
       nil,
       nil,
       (805..808)
     ),
     DefNode(
       CONSTANT("Array_function"),
       SelfNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (810..813),
       (818..819),
       nil,
       nil,
       nil,
       (835..838)
     ),
     ConstantPathWriteNode(ConstantReadNode(), EQUAL("="), IntegerNode()),
     DefNode(
       IDENTIFIER("a"),
       ConstantReadNode(),
       ParametersNode([], [], nil, [], nil, nil),
       StatementsNode([]),
       Scope([]),
       (851..854),
       (860..861),
       nil,
       nil,
       nil,
       (863..866)
     ),
     DefNode(
       IDENTIFIER("a"),
       nil,
       ParametersNode([], [], nil, [], ForwardingParameterNode(), nil),
       StatementsNode(
         [InterpolatedStringNode(
            STRING_BEGIN("\""),
            [StringNode(nil, STRING_CONTENT("foo"), nil, "foo"),
             StringInterpolatedNode(
               EMBEXPR_BEGIN("\#{"),
               StatementsNode(
                 [CallNode(
                    nil,
                    nil,
                    IDENTIFIER("b"),
                    PARENTHESIS_LEFT("("),
                    ArgumentsNode([ForwardingArgumentsNode()]),
                    PARENTHESIS_RIGHT(")"),
                    nil,
                    "b"
                  )]
               ),
               EMBEXPR_END("}")
             )],
            STRING_END("\"")
          )]
       ),
       Scope([UDOT_DOT_DOT("...")]),
       (868..871),
       nil,
       (873..874),
       (877..878),
       nil,
       (896..899)
     )]
  )
)
