ProgramNode(
  Scope([]),
  StatementsNode(
    [CallNode(
       CallNode(nil, nil, IDENTIFIER("foo"), nil, nil, nil, nil, "foo"),
       DOT("."),
       IDENTIFIER("bar"),
       nil,
       ArgumentsNode(
         [StringNode(
            STRING_BEGIN("%{"),
            STRING_CONTENT("baz"),
            STRING_END("}"),
            "baz"
          )]
       ),
       nil,
       nil,
       "bar"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
       DOT("."),
       IDENTIFIER("b"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [CallNode(nil, nil, IDENTIFIER("c"), nil, nil, nil, nil, "c"),
          CallNode(nil, nil, IDENTIFIER("d"), nil, nil, nil, nil, "d")]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "b"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
       DOT("."),
       IDENTIFIER("b"),
       PARENTHESIS_LEFT("("),
       nil,
       PARENTHESIS_RIGHT(")"),
       nil,
       "b"
     ),
     CallNode(
       CallNode(
         CallNode(nil, nil, IDENTIFIER("foo"), nil, nil, nil, nil, "foo"),
         DOT("."),
         IDENTIFIER("bar"),
         nil,
         nil,
         nil,
         nil,
         "bar"
       ),
       AMPERSAND_DOT("&."),
       IDENTIFIER("baz"),
       nil,
       nil,
       nil,
       nil,
       "baz"
     ),
     CallNode(nil, nil, IDENTIFIER("a!"), nil, nil, nil, nil, "a!"),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
       DOT("."),
       nil,
       PARENTHESIS_LEFT("("),
       nil,
       PARENTHESIS_RIGHT(")"),
       nil,
       "call"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
       DOT("."),
       nil,
       PARENTHESIS_LEFT("("),
       ArgumentsNode([IntegerNode(), IntegerNode(), IntegerNode()]),
       PARENTHESIS_RIGHT(")"),
       nil,
       "call"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
       COLON_COLON("::"),
       IDENTIFIER("b"),
       nil,
       nil,
       nil,
       nil,
       "b"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("foo"), nil, nil, nil, nil, "foo"),
       DOT("."),
       IDENTIFIER("bar"),
       nil,
       ArgumentsNode([IntegerNode()]),
       nil,
       nil,
       "bar="
     ),
     CallNode(nil, nil, IDENTIFIER("a?"), nil, nil, nil, nil, "a?"),
     CallNode(
       nil,
       nil,
       IDENTIFIER("a"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [BlockArgumentNode(
            CallNode(
              nil,
              nil,
              IDENTIFIER("block"),
              nil,
              nil,
              nil,
              nil,
              "block"
            ),
            (102..103)
          )]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "a"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("a"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [HashNode(
            nil,
            [AssocSplatNode(
               CallNode(
                 nil,
                 nil,
                 IDENTIFIER("kwargs"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "kwargs"
               ),
               (113..115)
             )],
            nil
          )]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "a"
     ),
     CallNode(
       CallNode(
         CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
         DOT("."),
         IDENTIFIER("b"),
         nil,
         nil,
         nil,
         nil,
         "b"
       ),
       DOT("."),
       IDENTIFIER("c"),
       nil,
       nil,
       nil,
       nil,
       "c"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("a"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [CallNode(nil, nil, IDENTIFIER("b"), nil, nil, nil, nil, "b"),
          CallNode(nil, nil, IDENTIFIER("c"), nil, nil, nil, nil, "c")]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "a"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("a"),
       PARENTHESIS_LEFT("("),
       nil,
       PARENTHESIS_RIGHT(")"),
       nil,
       "a"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("a"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [SplatNode(
            USTAR("*"),
            CallNode(nil, nil, IDENTIFIER("args"), nil, nil, nil, nil, "args")
          )]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "a"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("a"),
       nil,
       ArgumentsNode(
         [CallNode(nil, nil, IDENTIFIER("b"), nil, nil, nil, nil, "b"),
          CallNode(nil, nil, IDENTIFIER("c"), nil, nil, nil, nil, "c")]
       ),
       nil,
       nil,
       "a"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
       DOT("."),
       IDENTIFIER("b"),
       nil,
       ArgumentsNode(
         [CallNode(nil, nil, IDENTIFIER("c"), nil, nil, nil, nil, "c"),
          CallNode(nil, nil, IDENTIFIER("d"), nil, nil, nil, nil, "d")]
       ),
       nil,
       nil,
       "b"
     ),
     MultiWriteNode(
       [CallNode(
          CallNode(nil, nil, IDENTIFIER("foo"), nil, nil, nil, nil, "foo"),
          DOT("."),
          IDENTIFIER("foo"),
          nil,
          nil,
          nil,
          nil,
          "foo="
        ),
        CallNode(
          CallNode(nil, nil, IDENTIFIER("bar"), nil, nil, nil, nil, "bar"),
          DOT("."),
          IDENTIFIER("bar"),
          nil,
          nil,
          nil,
          nil,
          "bar="
        )],
       EQUAL("="),
       ArrayNode([IntegerNode(), IntegerNode()], nil, nil),
       nil,
       nil
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
       AMPERSAND_DOT("&."),
       IDENTIFIER("b"),
       nil,
       nil,
       nil,
       nil,
       "b"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
       AMPERSAND_DOT("&."),
       nil,
       PARENTHESIS_LEFT("("),
       nil,
       PARENTHESIS_RIGHT(")"),
       nil,
       "call"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
       AMPERSAND_DOT("&."),
       IDENTIFIER("b"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [CallNode(nil, nil, IDENTIFIER("c"), nil, nil, nil, nil, "c")]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "b"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("a"), nil, nil, nil, nil, "a"),
       AMPERSAND_DOT("&."),
       IDENTIFIER("b"),
       PARENTHESIS_LEFT("("),
       nil,
       PARENTHESIS_RIGHT(")"),
       nil,
       "b"
     ),
     IfNode(
       KEYWORD_IF_MODIFIER("if"),
       AndNode(
         OrNode(
           CallNode(nil, nil, IDENTIFIER("bar?"), nil, nil, nil, nil, "bar?"),
           CallNode(nil, nil, IDENTIFIER("baz"), nil, nil, nil, nil, "baz"),
           (247..249)
         ),
         CallNode(nil, nil, IDENTIFIER("qux"), nil, nil, nil, nil, "qux"),
         KEYWORD_AND("and")
       ),
       StatementsNode(
         [CallNode(
            nil,
            nil,
            IDENTIFIER("foo"),
            nil,
            ArgumentsNode(
              [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("a"), nil, "a"),
               SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("b"), nil, "b")]
            ),
            nil,
            nil,
            "foo"
          )]
       ),
       nil,
       nil
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("a"), nil, "a"),
          SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("b"), nil, "b")]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [SplatNode(
            USTAR("*"),
            CallNode(nil, nil, IDENTIFIER("rest"), nil, nil, nil, nil, "rest")
          )]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("a"), nil, "a"),
          HashNode(
            nil,
            [AssocNode(
               SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("h"), nil, "h"),
               ArrayNode(
                 [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("x"), nil, "x"),
                  SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("y"), nil, "y")],
                 BRACKET_LEFT_ARRAY("["),
                 BRACKET_RIGHT("]")
               ),
               EQUAL_GREATER("=>")
             ),
             AssocNode(
               SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("a"), nil, "a"),
               SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("b"), nil, "b"),
               EQUAL_GREATER("=>")
             )],
            nil
          ),
          BlockArgumentNode(
            SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("bar"), nil, "bar"),
            (326..327)
          )]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("hi"),
       nil,
       ArgumentsNode(
         [IntegerNode(),
          HashNode(
            BRACE_LEFT("{"),
            [AssocNode(
               SymbolNode(
                 SYMBOL_BEGIN(":"),
                 IDENTIFIER("there"),
                 nil,
                 "there"
               ),
               SymbolNode(
                 SYMBOL_BEGIN(":"),
                 IDENTIFIER("friend"),
                 nil,
                 "friend"
               ),
               EQUAL_GREATER("=>")
             ),
             AssocSplatNode(
               HashNode(BRACE_LEFT("{"), [], BRACE_RIGHT("}")),
               (363..365)
             ),
             AssocNode(
               SymbolNode(nil, LABEL("whatup"), LABEL_END(":"), "whatup"),
               SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("dog"), nil, "dog"),
               nil
             )],
            BRACE_RIGHT("}")
          )]
       ),
       nil,
       nil,
       "hi"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       ArgumentsNode(
         [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("a"), nil, "a"),
          HashNode(
            nil,
            [AssocNode(
               SymbolNode(nil, LABEL("b"), LABEL_END(":"), "b"),
               TrueNode(),
               nil
             )],
            nil
          )]
       ),
       nil,
       BlockNode(
         Scope([IDENTIFIER("a"), IDENTIFIER("b")]),
         BlockParametersNode(
           ParametersNode(
             [RequiredParameterNode(IDENTIFIER("a")),
              RequiredParameterNode(IDENTIFIER("b"))],
             [],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         StatementsNode(
           [CallNode(
              nil,
              nil,
              IDENTIFIER("puts"),
              nil,
              ArgumentsNode([LocalVariableReadNode(IDENTIFIER("a"), 0)]),
              nil,
              nil,
              "puts"
            )]
         ),
         (401..403),
         (418..421)
       ),
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("hi"),
       nil,
       ArgumentsNode(
         [HashNode(
            nil,
            [AssocNode(
               SymbolNode(nil, LABEL("there"), LABEL_END(":"), "there"),
               SymbolNode(
                 SYMBOL_BEGIN(":"),
                 IDENTIFIER("friend"),
                 nil,
                 "friend"
               ),
               nil
             )],
            nil
          )]
       ),
       nil,
       nil,
       "hi"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("hi"),
       nil,
       ArgumentsNode(
         [HashNode(
            nil,
            [AssocNode(
               SymbolNode(
                 SYMBOL_BEGIN(":"),
                 IDENTIFIER("there"),
                 nil,
                 "there"
               ),
               SymbolNode(
                 SYMBOL_BEGIN(":"),
                 IDENTIFIER("friend"),
                 nil,
                 "friend"
               ),
               EQUAL_GREATER("=>")
             ),
             AssocSplatNode(
               HashNode(BRACE_LEFT("{"), [], BRACE_RIGHT("}")),
               (464..466)
             ),
             AssocNode(
               SymbolNode(nil, LABEL("whatup"), LABEL_END(":"), "whatup"),
               SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("dog"), nil, "dog"),
               nil
             )],
            nil
          )]
       ),
       nil,
       nil,
       "hi"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("hi"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [HashNode(
            nil,
            [AssocNode(
               SymbolNode(
                 SYMBOL_BEGIN(":"),
                 IDENTIFIER("there"),
                 nil,
                 "there"
               ),
               SymbolNode(
                 SYMBOL_BEGIN(":"),
                 IDENTIFIER("friend"),
                 nil,
                 "friend"
               ),
               EQUAL_GREATER("=>")
             ),
             AssocSplatNode(
               HashNode(BRACE_LEFT("{"), [], BRACE_RIGHT("}")),
               (506..508)
             ),
             AssocNode(
               SymbolNode(nil, LABEL("whatup"), LABEL_END(":"), "whatup"),
               SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("dog"), nil, "dog"),
               nil
             )],
            nil
          )]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "hi"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [HashNode(
            BRACE_LEFT("{"),
            [AssocNode(
               SymbolNode(nil, LABEL("a"), LABEL_END(":"), "a"),
               TrueNode(),
               nil
             ),
             AssocNode(
               SymbolNode(nil, LABEL("b"), LABEL_END(":"), "b"),
               FalseNode(),
               nil
             )],
            BRACE_RIGHT("}")
          ),
          BlockArgumentNode(
            SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("block"), nil, "block"),
            (555..556)
          )]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("hi"),
       nil,
       ArgumentsNode(
         [HashNode(
            nil,
            [AssocNode(
               SymbolNode(
                 SYMBOL_BEGIN(":"),
                 IDENTIFIER("there"),
                 nil,
                 "there"
               ),
               SymbolNode(
                 SYMBOL_BEGIN(":"),
                 IDENTIFIER("friend"),
                 nil,
                 "friend"
               ),
               EQUAL_GREATER("=>")
             )],
            nil
          )]
       ),
       nil,
       nil,
       "hi"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("a"), nil, "a"),
          SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("b"), nil, "b")]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("a"), nil, "a"),
          HashNode(
            nil,
            [AssocNode(
               SymbolNode(nil, LABEL("b"), LABEL_END(":"), "b"),
               SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("c"), nil, "c"),
               nil
             )],
            nil
          )]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       nil,
       ArgumentsNode(
         [HashNode(
            nil,
            [AssocNode(
               SymbolNode(nil, LABEL("a"), LABEL_END(":"), "a"),
               TrueNode(),
               nil
             ),
             AssocNode(
               SymbolNode(nil, LABEL("b"), LABEL_END(":"), "b"),
               FalseNode(),
               nil
             )],
            nil
          ),
          BlockArgumentNode(
            SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("block"), nil, "block"),
            (644..645)
          )]
       ),
       nil,
       nil,
       "foo"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("some_func"),
       nil,
       ArgumentsNode(
         [IntegerNode(),
          HashNode(
            nil,
            [AssocNode(
               SymbolNode(nil, LABEL("kwarg"), LABEL_END(":"), "kwarg"),
               IntegerNode(),
               nil
             )],
            nil
          )]
       ),
       nil,
       nil,
       "some_func"
     ),
     CallNode(
       ConstantReadNode(),
       DOT("."),
       CONSTANT("Integer"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode([IntegerNode()]),
       PARENTHESIS_RIGHT(")"),
       nil,
       "Integer"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("x"), nil, nil, nil, nil, "x"),
       DOT("."),
       IDENTIFIER("each"),
       nil,
       nil,
       nil,
       BlockNode(Scope([]), nil, nil, (703..704), (705..706)),
       "each"
     ),
     CallNode(
       CallNode(nil, nil, IDENTIFIER("foo"), nil, nil, nil, nil, "foo"),
       DOT("."),
       IDENTIFIER("map"),
       nil,
       nil,
       nil,
       BlockNode(
         Scope([]),
         nil,
         StatementsNode([GlobalVariableReadNode(BACK_REFERENCE("$&"))]),
         (716..717),
         (721..722)
       ),
       "map"
     ),
     CallNode(
       ConstantPathNode(
         ConstantReadNode(),
         COLON_COLON("::"),
         ConstantReadNode()
       ),
       COLON_COLON("::"),
       CONSTANT("C"),
       nil,
       ArgumentsNode(
         [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("foo"), nil, "foo")]
       ),
       nil,
       nil,
       "C"
     ),
     CallNode(
       ConstantPathNode(
         ConstantReadNode(),
         COLON_COLON("::"),
         ConstantReadNode()
       ),
       COLON_COLON("::"),
       CONSTANT("C"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [SymbolNode(SYMBOL_BEGIN(":"), IDENTIFIER("foo"), nil, "foo")]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "C"
     ),
     CallNode(
       nil,
       nil,
       IDENTIFIER("foo"),
       PARENTHESIS_LEFT("("),
       ArgumentsNode(
         [HashNode(
            nil,
            [AssocNode(
               SymbolNode(
                 STRING_BEGIN("\""),
                 STRING_CONTENT("a"),
                 LABEL_END("\":"),
                 "a"
               ),
               CallNode(
                 IntegerNode(),
                 nil,
                 UMINUS("-"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "-@"
               ),
               nil
             )],
            nil
          )]
       ),
       PARENTHESIS_RIGHT(")"),
       nil,
       "foo"
     )]
  )
)
