ProgramNode(0...101)(
  Scope(0...0)([]),
  StatementsNode(0...101)(
    [ModuleNode(0...18)(
       Scope(0...6)([IDENTIFIER(9...10)("a")]),
       KEYWORD_MODULE(0...6)("module"),
       ConstantReadNode(7...8)(),
       StatementsNode(9...14)(
         [LocalVariableWriteNode(9...14)(
            IDENTIFIER(9...10)("a"),
            EQUAL(11...12)("="),
            IntegerNode(13...14)()
          )]
       ),
       KEYWORD_END(15...18)("end")
     ),
     InterpolatedStringNode(20...38)(
       STRING_BEGIN(20...23)("%Q{"),
       [StringNode(23...27)(nil, STRING_CONTENT(23...27)("aaa "), nil, "aaa "),
        StringInterpolatedNode(27...33)(
          EMBEXPR_BEGIN(27...29)("\#{"),
          StatementsNode(29...32)(
            [CallNode(29...32)(
               nil,
               nil,
               IDENTIFIER(29...32)("bbb"),
               nil,
               nil,
               nil,
               nil,
               "bbb"
             )]
          ),
          EMBEXPR_END(32...33)("}")
        ),
        StringNode(33...37)(
          nil,
          STRING_CONTENT(33...37)(" ccc"),
          nil,
          " ccc"
        )],
       STRING_END(37...38)("}")
     ),
     ModuleNode(40...55)(
       Scope(40...46)([]),
       KEYWORD_MODULE(40...46)("module"),
       ConstantPathNode(47...51)(
         CallNode(47...48)(
           nil,
           nil,
           IDENTIFIER(47...48)("m"),
           nil,
           nil,
           nil,
           nil,
           "m"
         ),
         ConstantReadNode(50...51)(),
         (48...50)
       ),
       StatementsNode(0...0)([]),
       KEYWORD_END(52...55)("end")
     ),
     ModuleNode(57...85)(
       Scope(57...63)([IDENTIFIER(67...68)("x")]),
       KEYWORD_MODULE(57...63)("module"),
       ConstantReadNode(64...65)(),
       BeginNode(0...85)(
         nil,
         StatementsNode(67...72)(
           [LocalVariableWriteNode(67...72)(
              IDENTIFIER(67...68)("x"),
              EQUAL(69...70)("="),
              IntegerNode(71...72)()
            )]
         ),
         RescueNode(74...0)(
           KEYWORD_RESCUE(74...80)("rescue"),
           [],
           nil,
           nil,
           StatementsNode(0...0)([]),
           nil
         ),
         nil,
         nil,
         KEYWORD_END(82...85)("end")
       ),
       KEYWORD_END(82...85)("end")
     ),
     ModuleNode(87...101)(
       Scope(87...93)([]),
       KEYWORD_MODULE(87...93)("module"),
       ConstantPathNode(94...97)(nil, ConstantReadNode(96...97)(), (94...96)),
       StatementsNode(0...0)([]),
       KEYWORD_END(98...101)("end")
     )]
  )
)
