<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.ruby-lang</groupId>
    <artifactId>prism-parser</artifactId>
    <version>0.0.4</version>
  </parent>

  <artifactId>prism-parser-wasm</artifactId>
  <name>Java Prism WASM</name>
  <description>Java WASM bindings for the Prism parser shared library</description>
  <url>https://github.com/ruby/prism</url>

  <properties>
    <endive.version>1.1.0</endive.version>
  </properties>

  <dependencyManagement>
    <dependencies>
          <dependency>
              <groupId>run.endive</groupId>
              <artifactId>bom</artifactId>
              <version>${endive.version}</version>
              <type>pom</type>
              <scope>import</scope>
          </dependency>
      </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.ruby-lang</groupId>
      <artifactId>prism-parser-api</artifactId>
      <version>0.0.4</version>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>runtime</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>log</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>wasi</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>wasm</artifactId>
    </dependency>
    <dependency>
      <groupId>run.endive</groupId>
      <artifactId>redline-runner-jffi-experimental</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jruby</groupId>
      <artifactId>jruby</artifactId>
      <version>10.1.1.0</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>run.endive</groupId>
        <artifactId>endive-compiler-maven-plugin</artifactId>
        <version>${endive.version}</version>
        <executions>
          <execution>
            <id>prism</id>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <name>org.ruby_lang.prism.wasm.PrismParser</name>
              <moduleInterface>org.ruby_lang.prism.wasm.Prism</moduleInterface>
              <wasmFile>src/main/wasm/prism.wasm</wasmFile>
              <redlineExperimental>true</redlineExperimental>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
