module Prism
  class DesugarCompiler < MutationCompiler
    def visit_class_variable_and_write_node: (ClassVariableAndWriteNode node) -> AndNode
    def visit_class_variable_or_write_node: (ClassVariableOrWriteNode node) -> IfNode
    def visit_class_variable_operator_write_node: (ClassVariableOperatorWriteNode node) -> ClassVariableWriteNode
    def visit_constant_and_write_node: (ConstantAndWriteNode node) -> AndNode
    def visit_constant_or_write_node: (ConstantOrWriteNode node) -> IfNode
    def visit_constant_operator_write_node: (ConstantOperatorWriteNode node) -> ConstantWriteNode
    def visit_global_variable_and_write_node: (GlobalVariableAndWriteNode node) -> AndNode
    def visit_global_variable_or_write_node: (GlobalVariableOrWriteNode node) -> IfNode
    def visit_global_variable_operator_write_node: (GlobalVariableOperatorWriteNode node) -> GlobalVariableWriteNode
    def visit_instance_variable_and_write_node: (InstanceVariableAndWriteNode node) -> AndNode
    def visit_instance_variable_or_write_node: (InstanceVariableOrWriteNode node) -> OrNode
    def visit_instance_variable_operator_write_node: (InstanceVariableOperatorWriteNode node) -> InstanceVariableWriteNode
    def visit_local_variable_and_write_node: (LocalVariableAndWriteNode node) -> AndNode
    def visit_local_variable_or_write_node: (LocalVariableOrWriteNode node) -> OrNode
    def visit_local_variable_operator_write_node: (LocalVariableOperatorWriteNode node) -> LocalVariableWriteNode

    private

    def desugar_and_write_node: (
      ClassVariableAndWriteNode | ConstantAndWriteNode | GlobalVariableAndWriteNode | InstanceVariableAndWriteNode | LocalVariableAndWriteNode,
      singleton(ClassVariableReadNode) | singleton(ConstantReadNode) | singleton(GlobalVariableReadNode) | singleton(InstanceVariableReadNode) | singleton(LocalVariableReadNode),
      singleton(ClassVariableWriteNode) | singleton(ConstantWriteNode) | singleton(GlobalVariableWriteNode) | singleton(InstanceVariableWriteNode) | singleton(LocalVariableWriteNode),
      *untyped
    ) -> AndNode

    def desugar_operator_write_node:
      (ClassVariableOperatorWriteNode, singleton(ClassVariableReadNode), singleton(ClassVariableWriteNode), *untyped) -> ClassVariableWriteNode
    | (ConstantOperatorWriteNode, singleton(ConstantReadNode), singleton(ConstantWriteNode), *untyped) -> ConstantWriteNode
    | (GlobalVariableOperatorWriteNode, singleton(GlobalVariableReadNode), singleton(GlobalVariableWriteNode), *untyped) -> GlobalVariableWriteNode
    | (InstanceVariableOperatorWriteNode, singleton(InstanceVariableReadNode), singleton(InstanceVariableWriteNode), *untyped) -> InstanceVariableWriteNode
    | (LocalVariableOperatorWriteNode, singleton(LocalVariableReadNode), singleton(LocalVariableWriteNode), *untyped) -> LocalVariableWriteNode

    def desugar_or_write_node: (
      InstanceVariableOrWriteNode | LocalVariableOrWriteNode,
      singleton(InstanceVariableReadNode) | singleton(LocalVariableReadNode),
      singleton(InstanceVariableWriteNode) | singleton(LocalVariableWriteNode),
      *untyped
    ) -> OrNode

    def desugar_or_write_defined_node: (
      ClassVariableOrWriteNode | ConstantOrWriteNode | GlobalVariableOrWriteNode,
      singleton(ClassVariableReadNode) | singleton(ConstantReadNode) | singleton(GlobalVariableReadNode),
      singleton(ClassVariableWriteNode) | singleton(ConstantWriteNode) | singleton(GlobalVariableWriteNode),
      *untyped
    ) -> IfNode
  end
end
