module Prism
  class NodeInspector
    attr_reader prefix: String
    attr_reader output: String

    def initialize: (?String) -> void

    def <<: (String) -> void
    def header: (Prism::node) -> String
    def list: (String, Array[Prism::node]) -> String
    def location: (Location?) -> String
    def child_node: (Prism::node, String) -> String
    def child_inspector: (String) -> NodeInspector

    def to_str: () -> String
  end
end
