# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 3.5.0.dev"

gemspec path: "../.."

gem "ffi"
gem "onigmo", platforms: :ruby
gem "parser"
gem "rake-compiler"
gem "rake"
gem "rbs"
gem "ruby_memcheck"
gem "test-unit"
