# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 4.1.0.dev"

gemspec path: "../.."

gem "ffi"
gem "onigmo", platforms: :ruby
gem "parser"
gem "rake-compiler"
gem "rake"
gem "ruby_memcheck"
gem "ruby_parser"
gem "test-unit"
