module Prism
  class RipperCompat < Visitor
    class SexpBuilder < RipperCompat
      def parse: () -> Array[untyped]
    end

    class SexpBuilderPP < SexpBuilder
    end

    attr_reader source: String
    attr_reader lineno: Integer?
    attr_reader column: Integer?

    def initialize: (String) -> void

    def error?: () -> bool
    def parse: () -> untyped

    def self.sexp_raw: (String) -> Array[untyped]
    def self.sexp: (String) -> Array[untyped]
  end
end
