ProgramNode(2...4)(
  ScopeNode(0...0)([]),
  StatementsNode(2...4)(
    [HashNode(2...4)(
       BRACE_LEFT(0...1)("{"),
       [AssocNode(2...4)(
          SymbolNode(2...4)(
            nil,
            LABEL(2...3)("y"),
            LABEL_END(3...4)(":"),
            "y"
          ),
          nil,
          nil
        )],
       BRACE_RIGHT(5...6)("}")
     )]
  )
)
