ProgramNode(0...32)(
  [],
  StatementsNode(0...32)(
    [BeginNode(0...32)(
       (0...5),
       nil,
       RescueNode(7...13)(
         KEYWORD_RESCUE(7...13)("rescue"),
         [],
         nil,
         nil,
         nil,
         nil
       ),
       ElseNode(15...27)((15...19), nil, (21...27)),
       EnsureNode(21...32)(
         KEYWORD_ENSURE(21...27)("ensure"),
         nil,
         KEYWORD_END(29...32)("end")
       ),
       (29...32)
     )]
  )
)
