ProgramNode(0...18)(
  ScopeNode(0...0)([]),
  StatementsNode(0...18)(
    [BeginNode(0...18)(
       KEYWORD_BEGIN(0...5)("begin"),
       StatementsNode(0...0)([]),
       nil,
       ElseNode(7...18)(
         KEYWORD_ELSE(7...11)("else"),
         StatementsNode(12...13)([IntegerNode(12...13)()]),
         KEYWORD_END(15...18)("end")
       ),
       nil,
       KEYWORD_END(15...18)("end")
     )]
  )
)
