ProgramNode(0...13)(
  [],
  StatementsNode(0...13)(
    [CallNode(0...13)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       BlockNode(2...13)(
         [:b, :c],
         BlockParametersNode(4...11)(
           ParametersNode(5...10)(
             [],
             [],
             [RequiredParameterNode(9...10)(:c)],
             RestParameterNode(5...7)((5...6), (6...7)),
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (10...11)
         ),
         nil,
         (2...3),
         (12...13)
       ),
       "a"
     )]
  )
)
