ProgramNode(0...17)(
  [],
  StatementsNode(0...17)(
    [CallNode(0...17)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       BlockNode(2...17)(
         [IDENTIFIER(5...6)("b"), IDENTIFIER(8...9)("c")],
         BlockParametersNode(4...15)(
           ParametersNode(5...14)(
             [RequiredParameterNode(5...6)()],
             [OptionalParameterNode(8...14)(
                (8...9),
                (10...11),
                SymbolNode(12...14)(
                  SYMBOL_BEGIN(12...13)(":"),
                  IDENTIFIER(13...14)("d"),
                  nil,
                  "d"
                )
              )],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (14...15)
         ),
         nil,
         (2...3),
         (16...17)
       ),
       "a"
     )]
  )
)
