ProgramNode(0...13)(
  ScopeNode(0...0)([]),
  StatementsNode(0...13)(
    [CallNode(0...13)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       BlockNode(2...13)(
         ScopeNode(2...3)([IDENTIFIER(5...6)("b")]),
         BlockParametersNode(5...10)(
           ParametersNode(5...10)(
             [],
             [OptionalParameterNode(5...10)(
                IDENTIFIER(5...6)("b"),
                EQUAL(7...8)("="),
                IntegerNode(9...10)()
              )],
             [],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         nil,
         (2...3),
         (12...13)
       ),
       "a"
     )]
  )
)
