ProgramNode(0...16)(
  [],
  StatementsNode(0...16)(
    [CallNode(0...16)(
       nil,
       nil,
       IDENTIFIER(0...4)("blah"),
       nil,
       nil,
       nil,
       BlockNode(5...16)(
         [LABEL(9...10)("k")],
         BlockParametersNode(8...12)(
           ParametersNode(9...11)(
             [],
             [],
             [],
             nil,
             [KeywordParameterNode(9...11)((9...11), nil)],
             nil,
             nil
           ),
           [],
           (8...9),
           (11...12)
         ),
         nil,
         (5...7),
         (13...16)
       ),
       "blah"
     )]
  )
)
