ProgramNode(0...13)(
  [],
  StatementsNode(0...13)(
    [CallNode(0...13)(
       nil,
       nil,
       IDENTIFIER(0...1)("a"),
       nil,
       nil,
       nil,
       BlockNode(2...13)(
         [IDENTIFIER(5...6)("b")],
         BlockParametersNode(4...11)(
           ParametersNode(5...10)(
             [],
             [OptionalParameterNode(5...10)(
                (5...6),
                (7...8),
                IntegerNode(9...10)()
              )],
             [],
             nil,
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (10...11)
         ),
         nil,
         (2...3),
         (12...13)
       ),
       "a"
     )]
  )
)
