ProgramNode(0...28)(
  [],
  StatementsNode(0...28)(
    [CallNode(0...28)(
       nil,
       nil,
       IDENTIFIER(0...7)("private"),
       nil,
       ArgumentsNode(8...28)(
         [DefNode(8...28)(
            (12...13),
            nil,
            nil,
            StatementsNode(14...24)(
              [CallNode(14...24)(
                 CallNode(14...15)(
                   nil,
                   nil,
                   IDENTIFIER(14...15)("a"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "a"
                 ),
                 DOT(15...16)("."),
                 IDENTIFIER(16...17)("b"),
                 nil,
                 nil,
                 nil,
                 BlockNode(18...24)([], nil, nil, (18...20), (21...24)),
                 "b"
               )]
            ),
            [],
            (8...11),
            nil,
            nil,
            nil,
            nil,
            (25...28)
          )]
       ),
       nil,
       nil,
       "private"
     )]
  )
)
