ProgramNode(0...20)(
  [],
  StatementsNode(0...20)(
    [CallNode(0...20)(
       nil,
       nil,
       IDENTIFIER(0...3)("foo"),
       PARENTHESIS_LEFT(3...4)("("),
       ArgumentsNode(4...18)(
         [SymbolNode(4...8)(
            SYMBOL_BEGIN(4...5)(":"),
            IDENTIFIER(5...8)("bar"),
            nil,
            "bar"
          ),
          KeywordHashNode(10...18)(
            [AssocNode(10...18)(
               SymbolNode(10...14)(
                 nil,
                 LABEL(10...13)("baz"),
                 LABEL_END(13...14)(":"),
                 "baz"
               ),
               NilNode(15...18)(),
               nil
             )]
          )]
       ),
       PARENTHESIS_RIGHT(19...20)(")"),
       nil,
       "foo"
     )]
  )
)
