ProgramNode(0...10)(
  [],
  StatementsNode(0...10)(
    [IfNode(0...10)(
       (0...2),
       CallNode(3...5)(
         IntegerNode(4...5)(),
         nil,
         UMINUS_NUM(3...4)("-"),
         nil,
         nil,
         nil,
         nil,
         "-@"
       ),
       nil,
       nil,
       (7...10)
     )]
  )
)
