ProgramNode(0...23)(
  [],
  StatementsNode(0...23)(
    [DefNode(0...23)(
       (4...5),
       nil,
       ParametersNode(6...18)(
         [RequiredParameterNode(6...7)()],
         [OptionalParameterNode(9...15)(
            (9...10),
            (11...12),
            SymbolNode(13...15)(
              SYMBOL_BEGIN(13...14)(":"),
              IDENTIFIER(14...15)("c"),
              nil,
              "c"
            )
          )],
         [RequiredParameterNode(17...18)()],
         nil,
         [],
         nil,
         nil
       ),
       nil,
       [IDENTIFIER(6...7)("a"),
        IDENTIFIER(9...10)("b"),
        IDENTIFIER(17...18)("d")],
       (0...3),
       nil,
       (5...6),
       (18...19),
       nil,
       (20...23)
     )]
  )
)
