ProgramNode(0...30)(
  ScopeNode(0...0)([]),
  StatementsNode(0...30)(
    [DefNode(0...30)(
       IDENTIFIER(4...15)("some_method"),
       nil,
       nil,
       StatementsNode(18...30)(
         [CallNode(18...30)(
            nil,
            nil,
            IDENTIFIER(18...30)("other_method"),
            nil,
            ArgumentsNode(31...43)(
              [RescueModifierNode(31...43)(
                 IntegerNode(31...33)(),
                 KEYWORD_RESCUE_MODIFIER(34...40)("rescue"),
                 IntegerNode(41...43)()
               )]
            ),
            nil,
            nil,
            "other_method"
          )]
       ),
       ScopeNode(0...3)([]),
       (0...3),
       nil,
       nil,
       nil,
       (16...17),
       nil
     )]
  )
)
