ProgramNode(0...35)(
  [],
  StatementsNode(0...35)(
    [DefNode(0...35)(
       (6...17),
       CallNode(4...5)(
         nil,
         nil,
         IDENTIFIER(4...5)("x"),
         nil,
         nil,
         nil,
         nil,
         "x"
       ),
       nil,
       StatementsNode(20...35)(
         [CallNode(20...35)(
            nil,
            nil,
            IDENTIFIER(20...32)("other_method"),
            nil,
            ArgumentsNode(33...35)([IntegerNode(33...35)()]),
            nil,
            nil,
            "other_method"
          )]
       ),
       [],
       (0...3),
       (5...6),
       nil,
       nil,
       (18...19),
       nil
     )]
  )
)
