ProgramNode(0...4)(
  ScopeNode(0...0)([]),
  StatementsNode(0...4)(
    [LambdaNode(0...4)(
       ScopeNode(0...2)([]),
       MINUS_GREATER(0...2)("->"),
       PARENTHESIS_LEFT(2...3)("("),
       nil,
       PARENTHESIS_RIGHT(3...4)(")"),
       nil
     )]
  )
)
