ProgramNode(0...12)(
  [],
  StatementsNode(0...12)(
    [InterpolatedStringNode(0...12)(
       (0...1),
       [StringInterpolatedNode(1...7)(
          (1...3),
          StatementsNode(3...6)(
            [StringNode(3...6)((3...4), (4...5), (5...6), "a")]
          ),
          (6...7)
        ),
        StringInterpolatedNode(7...11)(
          (7...9),
          StatementsNode(9...10)(
            [CallNode(9...10)(
               nil,
               nil,
               IDENTIFIER(9...10)("b"),
               nil,
               nil,
               nil,
               nil,
               "b"
             )]
          ),
          (10...11)
        )],
       (11...12)
     )]
  )
)
