ProgramNode(0...29)(
  [],
  StatementsNode(0...29)(
    [CallNode(0...29)(
       CallNode(0...1)(
         nil,
         nil,
         IDENTIFIER(0...1)("h"),
         nil,
         nil,
         nil,
         nil,
         "h"
       ),
       nil,
       BRACKET_LEFT_RIGHT_EQUAL(1...2)("["),
       BRACKET_LEFT(1...2)("["),
       ArgumentsNode(2...29)(
         [CallNode(2...3)(
            nil,
            nil,
            IDENTIFIER(2...3)("k"),
            nil,
            nil,
            nil,
            nil,
            "k"
          ),
          BeginNode(5...29)(
            (5...10),
            StatementsNode(18...20)([IntegerNode(18...20)()]),
            nil,
            nil,
            nil,
            (26...29)
          )]
       ),
       BRACKET_RIGHT(3...4)("]"),
       nil,
       "[]="
     )]
  )
)
