ProgramNode(0...10)(
  [],
  StatementsNode(0...10)(
    [InterpolatedStringNode(0...10)(
       (0...1),
       [StringInterpolatedNode(1...5)(
          (1...3),
          StatementsNode(3...4)(
            [CallNode(3...4)(
               nil,
               nil,
               IDENTIFIER(3...4)("a"),
               nil,
               nil,
               nil,
               nil,
               "a"
             )]
          ),
          (4...5)
        ),
        StringInterpolatedNode(5...9)(
          (5...7),
          StatementsNode(7...8)(
            [CallNode(7...8)(
               nil,
               nil,
               IDENTIFIER(7...8)("b"),
               nil,
               nil,
               nil,
               nil,
               "b"
             )]
          ),
          (8...9)
        )],
       (9...10)
     )]
  )
)
