ProgramNode(0...13)(
  [],
  StatementsNode(0...13)(
    [DefNode(0...13)(
       IDENTIFIER(4...5)("x"),
       nil,
       ParametersNode(6...8)(
         [],
         [],
         [],
         nil,
         [KeywordParameterNode(6...8)((6...8), nil)],
         nil,
         nil
       ),
       nil,
       [LABEL(6...7)("k")],
       (0...3),
       nil,
       nil,
       nil,
       nil,
       (10...13)
     )]
  )
)
