ProgramNode(0...20)(
  [IDENTIFIER(0...1)("a")],
  StatementsNode(0...20)(
    [LocalVariableWriteNode(0...20)(
       (0...1),
       CallNode(4...20)(
         nil,
         nil,
         IDENTIFIER(4...7)("foo"),
         PARENTHESIS_LEFT(7...8)("("),
         ArgumentsNode(8...19)(
           [CallNode(8...19)(
              InterpolatedStringNode(8...42)(
                (8...14),
                [StringNode(21...26)(nil, (21...26), nil, "\n"),
                 StringInterpolatedNode(26...32)(
                   (26...28),
                   StatementsNode(28...31)(
                     [CallNode(28...31)(
                        nil,
                        nil,
                        IDENTIFIER(28...31)("bar"),
                        nil,
                        nil,
                        nil,
                        nil,
                        "bar"
                      )]
                   ),
                   (31...32)
                 ),
                 StringNode(32...36)(nil, (32...36), nil, "baz\n")],
                (36...42)
              ),
              DOT(14...15)("."),
              IDENTIFIER(15...19)("chop"),
              nil,
              nil,
              nil,
              nil,
              "chop"
            )]
         ),
         PARENTHESIS_RIGHT(19...20)(")"),
         nil,
         "foo"
       ),
       (2...3),
       0
     )]
  )
)
