ProgramNode(0...19)(
  [],
  StatementsNode(0...19)(
    [InterpolatedStringNode(0...19)(
       (0...7),
       [StringNode(9...15)(
          nil,
          STRING_CONTENT(9...15)("body\r\n"),
          nil,
          "body\r\n"
        )],
       (15...19)
     )]
  )
)
