ProgramNode(0...24)(
  [],
  StatementsNode(0...24)(
    [InterpolatedStringNode(0...24)(
       (0...5),
       [StringNode(7...12)(
          nil,
          STRING_CONTENT(7...12)("foo\\r"),
          nil,
          "foo\r"
        ),
        InstanceVariableReadNode(13...17)(),
        StringNode(17...19)(
          nil,
          STRING_CONTENT(17...19)("\r\n"),
          nil,
          "\r\n"
        )],
       (19...24)
     )]
  )
)
