ProgramNode(0...22)(
  [],
  StatementsNode(0...22)(
    [CallNode(0...22)(
       InterpolatedStringNode(0...16)(
         (0...5),
         [StringNode(7...12)(nil, (7...12), nil, "blah\n")],
         (12...16)
       ),
       DOT(16...17)("."),
       IDENTIFIER(17...22)("strip"),
       nil,
       nil,
       nil,
       nil,
       "strip"
     )]
  )
)
