ProgramNode(0...23)(
  [],
  StatementsNode(0...23)(
    [InterpolatedStringNode(0...23)(
       (0...10),
       [StringNode(11...15)(
          nil,
          STRING_CONTENT(11...15)("\#${\n"),
          nil,
          "\#${\n"
        )],
       (15...23)
     )]
  )
)
