ProgramNode(0...49)(
  [IDENTIFIER(0...1)("a")],
  StatementsNode(0...49)(
    [LocalVariableWriteNode(0...49)(
       (0...1),
       InterpolatedStringNode(4...49)(
         (4...12),
         [StringNode(13...43)(
            nil,
            (13...43),
            nil,
            "blah blah\n" + " blah blah\n"
          )],
         (43...49)
       ),
       (2...3),
       0
     )]
  )
)
