ProgramNode(11...15)(
  ScopeNode(0...0)([]),
  StatementsNode(11...15)(
    [HeredocNode(11...15)(
       HEREDOC_START(0...10)("<<-HEREDOC"),
       [StringNode(11...15)(
          nil,
          STRING_CONTENT(11...15)("\#${\n"),
          nil,
          "\#${\n"
        )],
       HEREDOC_END(15...23)("HEREDOC\n"),
       0
     )]
  )
)
