ProgramNode(7...12)(
  ScopeNode(0...0)([]),
  StatementsNode(7...12)(
    [HeredocNode(7...12)(
       HEREDOC_START(0...5)("<<END"),
       [StringNode(7...12)(
          nil,
          STRING_CONTENT(7...12)("blah\n"),
          nil,
          "blah\n"
        )],
       HEREDOC_END(12...16)("END\n"),
       0
     )]
  )
)
