ProgramNode(0...43)(
  [IDENTIFIER(0...1)("a")],
  StatementsNode(0...43)(
    [LocalVariableWriteNode(0...43)(
       (0...1),
       InterpolatedStringNode(4...43)(
         (4...12),
         [StringNode(13...37)(
            nil,
            (13...37),
            nil,
            "blah blah\n" + "\tblah blah\n"
          )],
         (37...43)
       ),
       (2...3),
       0
     )]
  )
)
