ProgramNode(0...22)(
  [],
  StatementsNode(0...22)(
    [CallNode(0...22)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...22)(
         [IDENTIFIER(5...6)("a"),
          IDENTIFIER(14...15)("b"),
          IDENTIFIER(18...19)("c")],
         BlockParametersNode(4...20)(
           ParametersNode(5...19)(
             [],
             [OptionalParameterNode(5...11)(
                (5...6),
                (7...8),
                IntegerNode(9...11)()
              )],
             [],
             RestParameterNode(13...15)((13...14), (14...15)),
             [],
             nil,
             BlockParameterNode(17...19)((18...19), (17...18))
           ),
           [],
           (4...5),
           (19...20)
         ),
         nil,
         (2...3),
         (21...22)
       ),
       "f"
     )]
  )
)
