ProgramNode(0...21)(
  [],
  StatementsNode(0...21)(
    [CallNode(0...21)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...21)(
         [IDENTIFIER(5...6)("a"),
          IDENTIFIER(8...9)("b"),
          IDENTIFIER(17...18)("c")],
         BlockParametersNode(4...19)(
           ParametersNode(5...18)(
             [RequiredParameterNode(5...6)()],
             [OptionalParameterNode(8...14)(
                (8...9),
                (10...11),
                IntegerNode(12...14)()
              )],
             [],
             RestParameterNode(16...18)((16...17), (17...18)),
             [],
             nil,
             nil
           ),
           [],
           (4...5),
           (18...19)
         ),
         nil,
         (2...3),
         (20...21)
       ),
       "f"
     )]
  )
)
