ProgramNode(0...13)(
  [],
  StatementsNode(0...13)(
    [CallNode(0...13)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...13)(
         [IDENTIFIER(5...6)("a"), IDENTIFIER(9...10)("b")],
         BlockParametersNode(4...11)(
           ParametersNode(5...10)(
             [RequiredParameterNode(5...6)()],
             [],
             [],
             nil,
             [],
             nil,
             BlockParameterNode(8...10)((9...10), (8...9))
           ),
           [],
           (4...5),
           (10...11)
         ),
         nil,
         (2...3),
         (12...13)
       ),
       "f"
     )]
  )
)
