ProgramNode(0...18)(
  ScopeNode(0...0)([]),
  StatementsNode(0...18)(
    [CallNode(0...18)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...18)(
         ScopeNode(2...3)(
           [IDENTIFIER(5...6)("a"),
            IDENTIFIER(9...10)("b"),
            IDENTIFIER(13...14)("c")]
         ),
         BlockParametersNode(5...15)(
           ParametersNode(5...15)(
             [RequiredParameterNode(5...6)(),
              RequiredDestructuredParameterNode(9...15)(
                [RequiredParameterNode(9...10)(),
                 SplatNode(12...14)(
                   USTAR(12...13)("*"),
                   RequiredParameterNode(13...14)()
                 )],
                PARENTHESIS_LEFT(8...9)("("),
                PARENTHESIS_RIGHT(14...15)(")")
              )],
             [],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         nil,
         (2...3),
         (17...18)
       ),
       "f"
     )]
  )
)
