ProgramNode(0...17)(
  [],
  StatementsNode(0...17)(
    [CallNode(0...17)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...17)(
         [IDENTIFIER(6...7)("a"),
          IDENTIFIER(9...10)("b"),
          IDENTIFIER(13...14)("c")],
         BlockParametersNode(4...15)(
           ParametersNode(5...14)(
             [],
             [],
             [RequiredParameterNode(9...10)()],
             RestParameterNode(5...7)((5...6), (6...7)),
             [],
             nil,
             BlockParameterNode(12...14)((13...14), (12...13))
           ),
           [],
           (4...5),
           (14...15)
         ),
         nil,
         (2...3),
         (16...17)
       ),
       "f"
     )]
  )
)
