ProgramNode(0...21)(
  ScopeNode(0...0)([]),
  StatementsNode(0...21)(
    [CallNode(0...21)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...21)(
         ScopeNode(2...3)(
           [IDENTIFIER(5...6)("a"),
            IDENTIFIER(9...10)("b"),
            IDENTIFIER(13...14)("c"),
            IDENTIFIER(16...17)("d")]
         ),
         BlockParametersNode(5...18)(
           ParametersNode(5...18)(
             [RequiredParameterNode(5...6)(IDENTIFIER(5...6)("a")),
              RequiredDestructuredParameterNode(9...18)(
                [RequiredParameterNode(9...10)(IDENTIFIER(9...10)("b")),
                 SplatNode(12...14)(
                   USTAR(12...13)("*"),
                   RequiredParameterNode(13...14)(IDENTIFIER(13...14)("c"))
                 ),
                 RequiredParameterNode(16...17)(IDENTIFIER(16...17)("d"))],
                PARENTHESIS_LEFT(8...9)("("),
                PARENTHESIS_RIGHT(17...18)(")")
              )],
             [],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         nil,
         (2...3),
         (20...21)
       ),
       "f"
     )]
  )
)
