ProgramNode(0...14)(
  [IDENTIFIER(0...1)("a")],
  StatementsNode(0...14)(
    [LocalVariableWriteNode(0...14)(
       (0...1),
       RescueModifierNode(4...14)(
         IntegerNode(4...5)(),
         (6...12),
         IntegerNode(13...14)()
       ),
       (2...3),
       0
     )]
  )
)
