ProgramNode(0...6)(
  ScopeNode(0...0)([IDENTIFIER(0...1)("a")]),
  StatementsNode(0...6)(
    [LocalVariableWriteNode(0...6)(
       IDENTIFIER(0...1)("a"),
       EQUAL(2...3)("="),
       IntegerNode(4...6)()
     )]
  )
)
