ProgramNode(18...90)(
  [],
  StatementsNode(18...90)(
    [ClassNode(18...90)(
       [],
       (18...23),
       ConstantReadNode(24...52)(),
       nil,
       nil,
       StatementsNode(54...86)(
         [DefNode(54...86)(
            (63...65),
            SelfNode(58...62)(),
            nil,
            StatementsNode(67...81)(
              [LocalVariableWriteNode(67...81)(
                 (67...72),
                 SymbolNode(75...81)(
                   SYMBOL_BEGIN(75...76)(":"),
                   IDENTIFIER(76...81)("però"),
                   nil,
                   "però"
                 ),
                 (73...74),
                 0
               )]
            ),
            [IDENTIFIER(67...72)("così")],
            (54...57),
            (62...63),
            nil,
            nil,
            nil,
            (83...86)
          )]
       ),
       (87...90)
     )]
  )
)
