ProgramNode(0...43)(
  ScopeNode(0...0)([]),
  StatementsNode(0...43)(
    [CallNode(0...14)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       PARENTHESIS_LEFT(1...2)("("),
       ArgumentsNode(2...11)(
         [HashNode(2...11)(
            nil,
            [AssocNode(2...11)(
               SymbolNode(2...8)(
                 nil,
                 LABEL(2...7)("state"),
                 LABEL_END(7...8)(":"),
                 "state"
               ),
               HashNode(10...11)(
                 BRACE_LEFT(10...11)("{"),
                 [],
                 BRACE_RIGHT(12...13)("}")
               ),
               nil
             )],
            nil
          )]
       ),
       PARENTHESIS_RIGHT(13...14)(")"),
       nil,
       "f"
     ),
     CallNode(16...29)(
       nil,
       nil,
       IDENTIFIER(16...17)("f"),
       PARENTHESIS_LEFT(17...18)("("),
       ArgumentsNode(18...26)(
         [HashNode(18...26)(
            nil,
            [AssocNode(18...26)(
               SymbolNode(18...24)(
                 nil,
                 LABEL(18...23)("state"),
                 LABEL_END(23...24)(":"),
                 "state"
               ),
               HashNode(25...26)(
                 BRACE_LEFT(25...26)("{"),
                 [],
                 BRACE_RIGHT(27...28)("}")
               ),
               nil
             )],
            nil
          )]
       ),
       PARENTHESIS_RIGHT(28...29)(")"),
       nil,
       "f"
     ),
     CallNode(31...43)(
       nil,
       nil,
       IDENTIFIER(31...32)("f"),
       PARENTHESIS_LEFT(32...33)("("),
       ArgumentsNode(33...41)(
         [HashNode(33...41)(
            nil,
            [AssocNode(33...41)(
               SymbolNode(33...39)(
                 nil,
                 LABEL(33...38)("state"),
                 LABEL_END(38...39)(":"),
                 "state"
               ),
               HashNode(40...41)(
                 BRACE_LEFT(40...41)("{"),
                 [],
                 BRACE_RIGHT(41...42)("}")
               ),
               nil
             )],
            nil
          )]
       ),
       PARENTHESIS_RIGHT(42...43)(")"),
       nil,
       "f"
     )]
  )
)
