ProgramNode(0...43)(
  [],
  StatementsNode(0...43)(
    [CallNode(0...14)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       PARENTHESIS_LEFT(1...2)("("),
       ArgumentsNode(2...13)(
         [KeywordHashNode(2...13)(
            [AssocNode(2...13)(
               SymbolNode(2...8)(
                 nil,
                 LABEL(2...7)("state"),
                 LABEL_END(7...8)(":"),
                 "state"
               ),
               HashNode(10...13)((10...11), [], (12...13)),
               nil
             )]
          )]
       ),
       PARENTHESIS_RIGHT(13...14)(")"),
       nil,
       "f"
     ),
     CallNode(16...29)(
       nil,
       nil,
       IDENTIFIER(16...17)("f"),
       PARENTHESIS_LEFT(17...18)("("),
       ArgumentsNode(18...28)(
         [KeywordHashNode(18...28)(
            [AssocNode(18...28)(
               SymbolNode(18...24)(
                 nil,
                 LABEL(18...23)("state"),
                 LABEL_END(23...24)(":"),
                 "state"
               ),
               HashNode(25...28)((25...26), [], (27...28)),
               nil
             )]
          )]
       ),
       PARENTHESIS_RIGHT(28...29)(")"),
       nil,
       "f"
     ),
     CallNode(31...43)(
       nil,
       nil,
       IDENTIFIER(31...32)("f"),
       PARENTHESIS_LEFT(32...33)("("),
       ArgumentsNode(33...42)(
         [KeywordHashNode(33...42)(
            [AssocNode(33...42)(
               SymbolNode(33...39)(
                 nil,
                 LABEL(33...38)("state"),
                 LABEL_END(38...39)(":"),
                 "state"
               ),
               HashNode(40...42)((40...41), [], (41...42)),
               nil
             )]
          )]
       ),
       PARENTHESIS_RIGHT(42...43)(")"),
       nil,
       "f"
     )]
  )
)
