ProgramNode(0...9)(
  ScopeNode(0...0)([]),
  StatementsNode(0...9)(
    [OperatorAssignmentNode(0...9)(
       CallNode(0...4)(
         ConstantReadNode(0...1)(),
         COLON_COLON(1...3)("::"),
         IDENTIFIER(3...4)("b"),
         nil,
         nil,
         nil,
         nil,
         "b="
       ),
       STAR_EQUAL(5...7)("*="),
       CallNode(8...9)(
         nil,
         nil,
         IDENTIFIER(8...9)("c"),
         nil,
         ArgumentsNode(10...11)(
           [CallNode(10...11)(
              nil,
              nil,
              IDENTIFIER(10...11)("d"),
              nil,
              nil,
              nil,
              nil,
              "d"
            )]
         ),
         nil,
         nil,
         "c"
       )
     )]
  )
)
