ProgramNode(0...13)(
  [],
  StatementsNode(0...13)(
    [HashNode(0...13)(
       (0...1),
       [AssocNode(2...10)(
          SymbolNode(2...5)(
            SYMBOL_BEGIN(2...3)(":"),
            IDENTIFIER(3...5)("s1"),
            nil,
            "s1"
          ),
          IntegerNode(9...10)(),
          (6...8)
        )],
       (12...13)
     )]
  )
)
