ProgramNode(0...23)(
  ScopeNode(0...0)([]),
  StatementsNode(0...23)(
    [CallNode(0...23)(
       nil,
       nil,
       IDENTIFIER(0...1)("f"),
       nil,
       nil,
       nil,
       BlockNode(2...23)(
         ScopeNode(2...4)([IDENTIFIER(6...7)("x"), IDENTIFIER(9...10)("y")]),
         BlockParametersNode(6...10)(
           ParametersNode(6...10)(
             [RequiredParameterNode(6...7)(IDENTIFIER(6...7)("x")),
              RequiredParameterNode(9...10)(IDENTIFIER(9...10)("y"))],
             [],
             nil,
             [],
             nil,
             nil
           ),
           []
         ),
         StatementsNode(14...19)(
           [CallNode(14...19)(
              LocalVariableReadNode(14...15)(IDENTIFIER(14...15)("x")),
              nil,
              PLUS(16...17)("+"),
              nil,
              ArgumentsNode(18...19)(
                [LocalVariableReadNode(18...19)(IDENTIFIER(18...19)("y"))]
              ),
              nil,
              nil,
              "+"
            )]
         ),
         (2...4),
         (20...23)
       ),
       "f"
     )]
  )
)
