ProgramNode(9...48)(
  ScopeNode(0...0)([]),
  StatementsNode(9...48)(
    [HeredocNode(9...28)(
       HEREDOC_START(0...8)("<<-EOFOO"),
       [StringNode(9...28)(
          nil,
          STRING_CONTENT(9...28)("\\n\\n\\n\\n\\n\\n\\n\\n\\n\n"),
          nil,
          "\n" + "\n" + "\n" + "\n" + "\n" + "\n" + "\n" + "\n" + "\n" + "\n"
        )],
       HEREDOC_END(28...34)("EOFOO\n"),
       0
     ),
     ClassNode(35...48)(
       ScopeNode(35...40)([]),
       KEYWORD_CLASS(35...40)("class"),
       ConstantReadNode(41...44)(),
       nil,
       nil,
       nil,
       KEYWORD_END(45...48)("end")
     )]
  )
)
