ProgramNode(2...10)(
  ScopeNode(0...0)([]),
  StatementsNode(2...10)(
    [HashNode(2...10)(
       BRACE_LEFT(0...1)("{"),
       [AssocNode(2...10)(
          SymbolNode(2...5)(
            SYMBOL_BEGIN(2...3)(":"),
            IDENTIFIER(3...5)("s1"),
            nil,
            "s1"
          ),
          IntegerNode(9...10)((9...10), 10),
          EQUAL_GREATER(6...8)("=>")
        )],
       BRACE_RIGHT(12...13)("}")
     )]
  )
)
