ProgramNode(6...74)(
  [IDENTIFIER(6...12)("string")],
  StatementsNode(6...74)(
    [LocalVariableWriteNode(6...57)(
       (6...12),
       InterpolatedStringNode(15...57)(
         (15...22),
         [StringNode(23...48)(
            nil,
            (23...48),
            nil,
            "        very long string\n"
          )],
         (48...57)
       ),
       (13...14),
       0
     ),
     CallNode(63...74)(
       nil,
       nil,
       IDENTIFIER(63...67)("puts"),
       nil,
       ArgumentsNode(68...74)([LocalVariableReadNode(68...74)(0)]),
       nil,
       nil,
       "puts"
     )]
  )
)
