ProgramNode(0...65)(
  [],
  StatementsNode(0...65)(
    [CallNode(0...65)(
       nil,
       nil,
       IDENTIFIER(0...3)("tap"),
       nil,
       nil,
       nil,
       BlockNode(4...65)(
         [],
         nil,
         BeginNode(0...65)(
           nil,
           StatementsNode(9...14)(
             [CallNode(9...14)(
                nil,
                nil,
                IDENTIFIER(9...14)("raise"),
                nil,
                nil,
                nil,
                nil,
                "raise"
              )]
           ),
           RescueNode(15...31)(
             (15...21),
             [],
             nil,
             nil,
             StatementsNode(24...31)(
               [SymbolNode(24...31)(
                  SYMBOL_BEGIN(24...25)(":"),
                  KEYWORD_RESCUE(25...31)("rescue"),
                  nil,
                  "rescue"
                )]
             ),
             nil
           ),
           ElseNode(32...51)(
             (32...36),
             StatementsNode(39...44)(
               [SymbolNode(39...44)(
                  SYMBOL_BEGIN(39...40)(":"),
                  KEYWORD_ELSE(40...44)("else"),
                  nil,
                  "else"
                )]
             ),
             (45...51)
           ),
           EnsureNode(45...65)(
             (45...51),
             StatementsNode(54...61)(
               [SymbolNode(54...61)(
                  SYMBOL_BEGIN(54...55)(":"),
                  KEYWORD_ENSURE(55...61)("ensure"),
                  nil,
                  "ensure"
                )]
             ),
             (62...65)
           ),
           (62...65)
         ),
         (4...6),
         (62...65)
       ),
       "tap"
     )]
  )
)
