ProgramNode(0...13)(
  ScopeNode(0...0)([]),
  StatementsNode(0...13)(
    [ArrayNode(0...13)(
       [ImaginaryNode(1...3)(IntegerNode(1...3)()),
        RationalNode(5...7)(IntegerNode(5...7)()),
        ImaginaryNode(9...12)(RationalNode(9...12)(IntegerNode(9...11)()))],
       BRACKET_LEFT_ARRAY(0...1)("["),
       BRACKET_RIGHT(12...13)("]")
     )]
  )
)
