ProgramNode(0...21)(
  ScopeNode(0...0)([]),
  StatementsNode(0...21)(
    [LambdaNode(0...21)(
       ScopeNode(0...2)(
         [IDENTIFIER(3...4)("b"),
          IDENTIFIER(6...7)("c"),
          IDENTIFIER(12...13)("d"),
          IDENTIFIER(15...16)("e"),
          IDENTIFIER(19...20)("f")]
       ),
       MINUS_GREATER(0...2)("->"),
       PARENTHESIS_LEFT(2...3)("("),
       BlockParametersNode(3...20)(
         ParametersNode(3...20)(
           [RequiredParameterNode(3...4)(IDENTIFIER(3...4)("b")),
            RequiredParameterNode(15...16)(IDENTIFIER(15...16)("e"))],
           [OptionalParameterNode(6...9)(
              IDENTIFIER(6...7)("c"),
              EQUAL(7...8)("="),
              IntegerNode(8...9)()
            )],
           RestParameterNode(11...13)(
             USTAR(11...12)("*"),
             IDENTIFIER(12...13)("d")
           ),
           [],
           nil,
           BlockParameterNode(18...20)(IDENTIFIER(19...20)("f"), (18...19))
         ),
         []
       ),
       PARENTHESIS_RIGHT(20...21)(")"),
       nil
     )]
  )
)
