ProgramNode(0...3)(
  [],
  StatementsNode(0...3)(
    [LambdaNode(0...3)(
       [IDENTIFIER(2...3)("a")],
       (0...2),
       BlockParametersNode(2...3)(
         ParametersNode(2...3)(
           [RequiredParameterNode(2...3)()],
           [],
           [],
           nil,
           [],
           nil,
           nil
         ),
         [],
         nil,
         nil
       ),
       nil
     )]
  )
)
