ProgramNode(0...8)(
  ScopeNode(0...0)([]),
  StatementsNode(0...8)(
    [LambdaNode(0...8)(
       ScopeNode(0...2)([IDENTIFIER(3...4)("a"), IDENTIFIER(6...7)("b")]),
       MINUS_GREATER(0...2)("->"),
       PARENTHESIS_LEFT(2...3)("("),
       BlockParametersNode(3...7)(
         ParametersNode(3...4)(
           [RequiredParameterNode(3...4)()],
           [],
           [],
           nil,
           [],
           nil,
           nil
         ),
         [IDENTIFIER(6...7)("b")]
       ),
       PARENTHESIS_RIGHT(7...8)(")"),
       nil
     )]
  )
)
