ProgramNode(0...23)(
  [],
  StatementsNode(0...23)(
    [InterpolatedStringNode(0...23)(
       (0...1),
       [StringInterpolatedNode(1...22)(
          (1...3),
          StatementsNode(8...21)(
            [IfNode(8...21)(
               (8...9),
               CallNode(3...7)(
                 CallNode(3...4)(
                   nil,
                   nil,
                   IDENTIFIER(3...4)("a"),
                   nil,
                   nil,
                   nil,
                   nil,
                   "a"
                 ),
                 DOT(4...5)("."),
                 IDENTIFIER(5...7)("b?"),
                 nil,
                 nil,
                 nil,
                 nil,
                 "b?"
               ),
               StatementsNode(10...17)(
                 [CallNode(10...17)(
                    CallNode(10...14)(
                      StringNode(10...12)((10...11), (11...11), (11...12), ""),
                      nil,
                      PLUS(12...13)("+"),
                      nil,
                      ArgumentsNode(13...14)(
                        [CallNode(13...14)(
                           nil,
                           nil,
                           IDENTIFIER(13...14)("a"),
                           nil,
                           nil,
                           nil,
                           nil,
                           "a"
                         )]
                      ),
                      nil,
                      nil,
                      "+"
                    ),
                    nil,
                    PLUS(14...15)("+"),
                    nil,
                    ArgumentsNode(15...17)(
                      [StringNode(15...17)(
                         (15...16),
                         (16...16),
                         (16...17),
                         ""
                       )]
                    ),
                    nil,
                    nil,
                    "+"
                  )]
               ),
               ElseNode(17...21)(
                 (17...18),
                 StatementsNode(19...21)(
                   [StringNode(19...21)((19...20), (20...20), (20...21), "")]
                 ),
                 nil
               ),
               nil
             )]
          ),
          (21...22)
        )],
       (22...23)
     )]
  )
)
