ProgramNode(0...16)(
  [],
  StatementsNode(0...16)(
    [InterpolatedStringNode(0...16)(
       (0...1),
       [StringNode(1...3)(nil, STRING_CONTENT(1...3)("a "), nil, "a "),
        StringInterpolatedNode(3...7)(
          (3...5),
          StatementsNode(5...6)(
            [CallNode(5...6)(
               nil,
               nil,
               IDENTIFIER(5...6)("b"),
               nil,
               nil,
               nil,
               nil,
               "b"
             )]
          ),
          (6...7)
        ),
        StringNode(7...15)(
          nil,
          STRING_CONTENT(7...15)("\\302\\275"),
          nil,
          "½"
        )],
       (15...16)
     )]
  )
)
