ProgramNode(0...13)(
  [],
  StatementsNode(0...13)(
    [ArrayNode(0...13)(
       [InterpolatedSymbolNode(0...7)(
          nil,
          [StringInterpolatedNode(3...7)(
             (3...5),
             StatementsNode(5...6)(
               [CallNode(5...6)(
                  nil,
                  nil,
                  IDENTIFIER(5...6)("a"),
                  nil,
                  nil,
                  nil,
                  nil,
                  "a"
                )]
             ),
             (6...7)
           )],
          nil
        ),
        InterpolatedSymbolNode(0...12)(
          nil,
          [StringInterpolatedNode(8...12)(
             (8...10),
             StatementsNode(10...11)(
               [CallNode(10...11)(
                  nil,
                  nil,
                  IDENTIFIER(10...11)("b"),
                  nil,
                  nil,
                  nil,
                  nil,
                  "b"
                )]
             ),
             (11...12)
           )],
          nil
        )],
       (0...3),
       (12...13)
     )]
  )
)
