ProgramNode(0...9)(
  [],
  StatementsNode(0...9)(
    [ArrayNode(0...9)(
       [InterpolatedStringNode(0...8)(
          nil,
          [StringInterpolatedNode(3...7)(
             EMBEXPR_BEGIN(3...5)("\#{"),
             StatementsNode(5...6)([IntegerNode(5...6)()]),
             EMBEXPR_END(6...7)("}")
           ),
           StringNode(7...8)(nil, STRING_CONTENT(7...8)("b"), nil, "b")],
          nil
        )],
       (0...3),
       (8...9)
     )]
  )
)
