ProgramNode(0...23)(
  [],
  StatementsNode(0...23)(
    [LambdaNode(0...23)(
       [IDENTIFIER(3...4)("a"), IDENTIFIER(6...7)("b")],
       (0...2),
       BlockParametersNode(2...12)(
         ParametersNode(3...11)(
           [RequiredParameterNode(3...4)()],
           [OptionalParameterNode(6...11)(
              (6...7),
              (7...8),
              NilNode(8...11)()
            )],
           [],
           nil,
           [],
           nil,
           nil
         ),
         [],
         (2...3),
         (11...12)
       ),
       StatementsNode(15...23)(
         [CallNode(15...23)(
            nil,
            nil,
            IDENTIFIER(15...16)("p"),
            nil,
            ArgumentsNode(17...23)(
              [ArrayNode(17...23)(
                 [LocalVariableReadNode(18...19)(0),
                  LocalVariableReadNode(21...22)(0)],
                 (17...18),
                 (22...23)
               )]
            ),
            nil,
            nil,
            "p"
          )]
       )
     )]
  )
)
