//! # ruby-prism-sys
//!
//! FFI-bindings for `prism`.
//!
#![deny(unused_extern_crates)]
#![warn(
    clippy::all,
    clippy::nursery,
    clippy::pedantic,
    future_incompatible,
    missing_copy_implementations,
    missing_docs,
    nonstandard_style,
    rust_2018_idioms,
    trivial_casts,
    trivial_numeric_casts,
    unreachable_pub,
    unused_qualifications
)]

#[allow(clippy::all, clippy::pedantic, clippy::cognitive_complexity)]
#[allow(missing_copy_implementations)]
#[allow(missing_docs)]
#[allow(non_camel_case_types)]
#[allow(non_snake_case)]
#[allow(non_upper_case_globals)]
#[allow(unused_qualifications)]
#[allow(clippy::missing_const_for_fn)]
#[allow(clippy::use_self)]
#[allow(trivial_casts)]
mod bindings {
    // Pregenerated by `bundle exec rake cargo:bindings`; `buildtime_bindgen`
    // regenerates at build time instead.
    #[cfg(not(feature = "buildtime_bindgen"))]
    include!("bindings.rs");

    #[cfg(feature = "buildtime_bindgen")]
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use self::bindings::*;
