# frozen_string_literal: true

source "https://rubygems.org"

ruby "~> 2.7.0"

gemspec path: "../.."

gem "onigmo", platforms: :ruby
gem "parser"
gem "power_assert", "~> 2.0" # https://github.com/test-unit/test-unit/pull/329
gem "rake-compiler"
gem "rake"
gem "rbs"
gem "ruby_parser"
gem "test-unit"
