/******************************************************************************/
/* This file is generated by the bin/template script and should not be        */
/* modified manually. See                                                     */
/* templates/src/errors.c.erb                                                 */
/* if you are looking to modify the                                           */
/* template                                                                   */
/******************************************************************************/
#include "errors.h"



bool
yp_diagnost_list_append_duplicate_parameter(yp_parser_t *parser, const char *start, const char *end) {
yp_diagnostic_t *diagnostic = (yp_diagnostic_t *) malloc(sizeof(yp_diagnostic_t));
    if (diagnostic == NULL) return false;

    yp_list_t *list = &parser->error_list;
    const char *line_start = (parser->newline_list.start + parser->newline_list.offsets[parser->newline_list.size-1]);

    char *line_end = strchr((char*)line_start, '\n');
    if (line_end == line_start) {
      line_start++;
      line_end = strchr((char*)line_start, '\n');
    }
    
    unsigned long line_size = (unsigned long)((line_end - line_start));
    char * line = malloc(sizeof(char) * (line_size+1));
    memcpy(line, line_start, line_size);
    line[line_size+1] = '\0';

    char * message_buf = malloc((sizeof(char)*36) + (unsigned int)(end - start));
    sprintf(message_buf, "duplicate parameter `%.*s` in parameters)", (unsigned int)(end - start), start);

    *diagnostic = (yp_diagnostic_t) {
      .start = start,
      .end = end,
      .message = message_buf,
      .line = line,
      .line_start = line_start,
      .lineno = parser->newline_list.size
    };
    
    yp_list_append(list, (yp_list_node_t *) diagnostic);
    return true;
}

