/******************************************************************************/
/* This file is generated by the bin/template script and should not be        */
/* modified manually. See                                                     */
/* templates/src/errors.h.erb                                                 */
/* if you are looking to modify the                                           */
/* template                                                                   */
/******************************************************************************/
#include "yarp/diagnostic.h"



bool
yp_diagnost_list_append_duplicate_parameter(yp_parser_t *parser, const char *start, const char *end);

