/******************************************************************************/
/* This file is generated by the bin/template script and should not be        */
/* modified manually.                                                         */
/******************************************************************************/

#include "yarp/node.h"

// Clear the node but preserves the location.
void yp_node_clear(yp_node_t *node) {
  yp_location_t location = node->location;
  memset(node, 0, sizeof(yp_node_t));
  node->location = location;
}

// Initialize a yp_token_list_t with its default values.
void
yp_token_list_init(yp_token_list_t *token_list) {
  *token_list = (yp_token_list_t) { .tokens = NULL, .size = 0, .capacity = 0 };
}

// Calculate the size of the token list in bytes.
static size_t
yp_token_list_memsize(yp_token_list_t *token_list) {
  return sizeof(yp_token_list_t) + (token_list->capacity * sizeof(yp_token_t));
}

// Append a token to the given list.
void
yp_token_list_append(yp_token_list_t *token_list, const yp_token_t *token) {
  if (token_list->size == token_list->capacity) {
    token_list->capacity = token_list->capacity == 0 ? 1 : token_list->capacity * 2;
    token_list->tokens = realloc(token_list->tokens, sizeof(yp_token_t) * token_list->capacity);
  }
  token_list->tokens[token_list->size++] = *token;
}

// Checks if the current token list includes the given token.
bool
yp_token_list_includes(yp_token_list_t *token_list, const yp_token_t *token) {
  size_t length = token->end - token->start;

  for (size_t index = 0; index < token_list->size; index++) {
    yp_token_t current_token = token_list->tokens[index];

    if (
      ((current_token.end - current_token.start) == length) &&
      (memcmp(current_token.start, token->start, length) == 0)
    ) {
      return true;
    }
  }
  return false;
}

// Free the memory associated with the token list.
static void
yp_token_list_free(yp_token_list_t *token_list) {
  if (token_list->tokens != NULL) {
    free(token_list->tokens);
  }
}

static void
yp_node_memsize_node(yp_node_t *node, yp_memsize_t *memsize);

// Initiailize a list of nodes.
void
yp_node_list_init(yp_node_list_t *node_list) {
  *node_list = (yp_node_list_t) { .nodes = NULL, .size = 0, .capacity = 0 };
}

// Calculate the size of the node list in bytes.
static size_t
yp_node_list_memsize(yp_node_list_t *node_list, yp_memsize_t *memsize) {
  size_t size = sizeof(yp_node_list_t) + (node_list->capacity * sizeof(yp_node_t *));
  for (size_t index = 0; index < node_list->size; index++) {
    yp_node_memsize_node(node_list->nodes[index], memsize);
  }
  return size;
}

// Append a new node onto the end of the node list.
void
yp_node_list_append(yp_parser_t *parser, yp_node_t *parent, yp_node_list_t *list, yp_node_t *node) {
  if (list->size == list->capacity) {
    list->capacity = list->capacity == 0 ? 4 : list->capacity * 2;
    list->nodes = realloc(list->nodes, list->capacity * sizeof(yp_node_t *));
  }

  list->nodes[list->size++] = node;

  if (list->size == 1) parent->location.start = node->location.start;
  parent->location.end = node->location.end;
}

__attribute__((__visibility__("default"))) void
yp_node_destroy(yp_parser_t *parser, yp_node_t *node);

// Deallocate the inner memory of a list of nodes. The parser argument is not
// used, but is here for the future possibility of pre-allocating memory pools.
static void
yp_node_list_free(yp_parser_t *parser, yp_node_list_t *list) {
  if (list->capacity > 0) {
    for (size_t index = 0; index < list->size; index++) {
      yp_node_destroy(parser, list->nodes[index]);
    }
    free(list->nodes);
  }
}

// Deallocate the space for a yp_node_t. Similarly to yp_node_alloc, we're not
// using the parser argument, but it's there to allow for the future possibility
// of pre-allocating larger memory pools.
__attribute__((__visibility__("default"))) void
yp_node_destroy(yp_parser_t *parser, yp_node_t *node) {
  switch (node->type) {
    case YP_NODE_ARRAY_PATTERN_NODE:
      if (node->as.array_pattern_node.constant != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.array_pattern_node.constant);
      }
      yp_node_list_free(parser, &node->as.array_pattern_node.requireds);
      if (node->as.array_pattern_node.rest != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.array_pattern_node.rest);
      }
      yp_node_list_free(parser, &node->as.array_pattern_node.posts);
      break;
    case YP_NODE_AS_PATTERN_NODE:
      yp_node_destroy(parser, (yp_node_t *)node->as.as_pattern_node.value);
      yp_node_destroy(parser, (yp_node_t *)node->as.as_pattern_node.target);
      break;
    case YP_NODE_ASSOC_NODE:
      yp_node_destroy(parser, (yp_node_t *)node->as.assoc_node.key);
      if (node->as.assoc_node.value != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.assoc_node.value);
      }
      break;
    case YP_NODE_ASSOC_SPLAT_NODE:
      if (node->as.assoc_splat_node.value != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.assoc_splat_node.value);
      }
      break;
    case YP_NODE_CALL_NODE:
      if (node->as.call_node.receiver != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.call_node.receiver);
      }
      if (node->as.call_node.arguments != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.call_node.arguments);
      }
      if (node->as.call_node.block != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.call_node.block);
      }
      yp_string_free(&node->as.call_node.name);
      break;
    case YP_NODE_CLASS_VARIABLE_READ_NODE:
      break;
    case YP_NODE_CLASS_VARIABLE_WRITE_NODE:
      if (node->as.class_variable_write_node.value != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.class_variable_write_node.value);
      }
      break;
    case YP_NODE_CONSTANT_PATH_WRITE_NODE:
      yp_node_destroy(parser, (yp_node_t *)node->as.constant_path_write_node.target);
      if (node->as.constant_path_write_node.value != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.constant_path_write_node.value);
      }
      break;
    case YP_NODE_CONSTANT_READ_NODE:
      break;
    case YP_NODE_FIND_PATTERN_NODE:
      if (node->as.find_pattern_node.constant != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.find_pattern_node.constant);
      }
      yp_node_destroy(parser, (yp_node_t *)node->as.find_pattern_node.left);
      yp_node_list_free(parser, &node->as.find_pattern_node.requireds);
      yp_node_destroy(parser, (yp_node_t *)node->as.find_pattern_node.right);
      break;
    case YP_NODE_GLOBAL_VARIABLE_READ_NODE:
      break;
    case YP_NODE_GLOBAL_VARIABLE_WRITE_NODE:
      if (node->as.global_variable_write_node.value != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.global_variable_write_node.value);
      }
      break;
    case YP_NODE_HASH_NODE:
      yp_node_list_free(parser, &node->as.hash_node.elements);
      break;
    case YP_NODE_HASH_PATTERN_NODE:
      if (node->as.hash_pattern_node.constant != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.hash_pattern_node.constant);
      }
      yp_node_list_free(parser, &node->as.hash_pattern_node.assocs);
      if (node->as.hash_pattern_node.kwrest != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.hash_pattern_node.kwrest);
      }
      break;
    case YP_NODE_HEREDOC_NODE:
      yp_node_list_free(parser, &node->as.heredoc_node.parts);
      break;
    case YP_NODE_IF_NODE:
      yp_node_destroy(parser, (yp_node_t *)node->as.if_node.predicate);
      if (node->as.if_node.statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.if_node.statements);
      }
      if (node->as.if_node.consequent != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.if_node.consequent);
      }
      break;
    case YP_NODE_IMAGINARY_NODE:
      break;
    case YP_NODE_IN_NODE:
      yp_node_destroy(parser, (yp_node_t *)node->as.in_node.pattern);
      if (node->as.in_node.statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.in_node.statements);
      }
      break;
    case YP_NODE_INSTANCE_VARIABLE_READ_NODE:
      break;
    case YP_NODE_INSTANCE_VARIABLE_WRITE_NODE:
      if (node->as.instance_variable_write_node.value != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.instance_variable_write_node.value);
      }
      break;
    case YP_NODE_INTEGER_NODE:
      break;
    case YP_NODE_INTERPOLATED_REGULAR_EXPRESSION_NODE:
      yp_node_list_free(parser, &node->as.interpolated_regular_expression_node.parts);
      break;
    case YP_NODE_INTERPOLATED_STRING_NODE:
      yp_node_list_free(parser, &node->as.interpolated_string_node.parts);
      break;
    case YP_NODE_INTERPOLATED_SYMBOL_NODE:
      yp_node_list_free(parser, &node->as.interpolated_symbol_node.parts);
      break;
    case YP_NODE_INTERPOLATED_X_STRING_NODE:
      yp_node_list_free(parser, &node->as.interpolated_x_string_node.parts);
      break;
    case YP_NODE_KEYWORD_PARAMETER_NODE:
      if (node->as.keyword_parameter_node.value != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.keyword_parameter_node.value);
      }
      break;
    case YP_NODE_KEYWORD_REST_PARAMETER_NODE:
      break;
    case YP_NODE_LAMBDA_NODE:
      yp_node_destroy(parser, (yp_node_t *)node->as.lambda_node.scope);
      if (node->as.lambda_node.parameters != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.lambda_node.parameters);
      }
      if (node->as.lambda_node.statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)node->as.lambda_node.statements);
      }
      break;
    case YP_NODE_ALIAS_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_alias_node_t *)node)->new_name);
      yp_node_destroy(parser, (yp_node_t *)((yp_alias_node_t *)node)->old_name);
      break;
    case YP_NODE_ALTERNATION_PATTERN_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_alternation_pattern_node_t *)node)->left);
      yp_node_destroy(parser, (yp_node_t *)((yp_alternation_pattern_node_t *)node)->right);
      break;
    case YP_NODE_AND_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_and_node_t *)node)->left);
      yp_node_destroy(parser, (yp_node_t *)((yp_and_node_t *)node)->right);
      break;
    case YP_NODE_ARGUMENTS_NODE:
      yp_node_list_free(parser, &((yp_arguments_node_t *)node)->arguments);
      break;
    case YP_NODE_ARRAY_NODE:
      yp_node_list_free(parser, &((yp_array_node_t *)node)->elements);
      break;
    case YP_NODE_BEGIN_NODE:
      if (((yp_begin_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_begin_node_t *)node)->statements);
      }
      if (((yp_begin_node_t *)node)->rescue_clause != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_begin_node_t *)node)->rescue_clause);
      }
      if (((yp_begin_node_t *)node)->else_clause != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_begin_node_t *)node)->else_clause);
      }
      if (((yp_begin_node_t *)node)->ensure_clause != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_begin_node_t *)node)->ensure_clause);
      }
      break;
    case YP_NODE_BLOCK_ARGUMENT_NODE:
      if (((yp_block_argument_node_t *)node)->expression != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_block_argument_node_t *)node)->expression);
      }
      break;
    case YP_NODE_BLOCK_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_block_node_t *)node)->scope);
      if (((yp_block_node_t *)node)->parameters != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_block_node_t *)node)->parameters);
      }
      if (((yp_block_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_block_node_t *)node)->statements);
      }
      break;
    case YP_NODE_BLOCK_PARAMETER_NODE:
      break;
    case YP_NODE_BLOCK_PARAMETERS_NODE:
      if (((yp_block_parameters_node_t *)node)->parameters != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_block_parameters_node_t *)node)->parameters);
      }
      yp_token_list_free(&((yp_block_parameters_node_t *)node)->locals);
      break;
    case YP_NODE_BREAK_NODE:
      if (((yp_break_node_t *)node)->arguments != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_break_node_t *)node)->arguments);
      }
      break;
    case YP_NODE_CASE_NODE:
      if (((yp_case_node_t *)node)->predicate != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_case_node_t *)node)->predicate);
      }
      yp_node_list_free(parser, &((yp_case_node_t *)node)->conditions);
      if (((yp_case_node_t *)node)->consequent != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_case_node_t *)node)->consequent);
      }
      break;
    case YP_NODE_CLASS_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_class_node_t *)node)->scope);
      yp_node_destroy(parser, (yp_node_t *)((yp_class_node_t *)node)->constant_path);
      if (((yp_class_node_t *)node)->superclass != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_class_node_t *)node)->superclass);
      }
      if (((yp_class_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_class_node_t *)node)->statements);
      }
      break;
    case YP_NODE_CONSTANT_PATH_NODE:
      if (((yp_constant_path_node_t *)node)->parent != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_constant_path_node_t *)node)->parent);
      }
      yp_node_destroy(parser, (yp_node_t *)((yp_constant_path_node_t *)node)->child);
      break;
    case YP_NODE_DEF_NODE:
      if (((yp_def_node_t *)node)->receiver != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_def_node_t *)node)->receiver);
      }
      if (((yp_def_node_t *)node)->parameters != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_def_node_t *)node)->parameters);
      }
      if (((yp_def_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_def_node_t *)node)->statements);
      }
      yp_node_destroy(parser, (yp_node_t *)((yp_def_node_t *)node)->scope);
      break;
    case YP_NODE_DEFINED_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_defined_node_t *)node)->value);
      break;
    case YP_NODE_ELSE_NODE:
      if (((yp_else_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_else_node_t *)node)->statements);
      }
      break;
    case YP_NODE_ENSURE_NODE:
      if (((yp_ensure_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_ensure_node_t *)node)->statements);
      }
      break;
    case YP_NODE_FALSE_NODE:
      break;
    case YP_NODE_FLOAT_NODE:
      break;
    case YP_NODE_FOR_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_for_node_t *)node)->index);
      yp_node_destroy(parser, (yp_node_t *)((yp_for_node_t *)node)->collection);
      if (((yp_for_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_for_node_t *)node)->statements);
      }
      break;
    case YP_NODE_FORWARDING_ARGUMENTS_NODE:
      break;
    case YP_NODE_FORWARDING_PARAMETER_NODE:
      break;
    case YP_NODE_FORWARDING_SUPER_NODE:
      if (((yp_forwarding_super_node_t *)node)->block != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_forwarding_super_node_t *)node)->block);
      }
      break;
    case YP_NODE_LOCAL_VARIABLE_READ_NODE:
      break;
    case YP_NODE_LOCAL_VARIABLE_WRITE_NODE:
      if (((yp_local_variable_write_node_t *)node)->value != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_local_variable_write_node_t *)node)->value);
      }
      break;
    case YP_NODE_MATCH_PREDICATE_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_match_predicate_node_t *)node)->value);
      yp_node_destroy(parser, (yp_node_t *)((yp_match_predicate_node_t *)node)->pattern);
      break;
    case YP_NODE_MATCH_REQUIRED_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_match_required_node_t *)node)->value);
      yp_node_destroy(parser, (yp_node_t *)((yp_match_required_node_t *)node)->pattern);
      break;
    case YP_NODE_MISSING_NODE:
      break;
    case YP_NODE_MODULE_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_module_node_t *)node)->scope);
      yp_node_destroy(parser, (yp_node_t *)((yp_module_node_t *)node)->constant_path);
      if (((yp_module_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_module_node_t *)node)->statements);
      }
      break;
    case YP_NODE_MULTI_WRITE_NODE:
      yp_node_list_free(parser, &((yp_multi_write_node_t *)node)->targets);
      if (((yp_multi_write_node_t *)node)->value != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_multi_write_node_t *)node)->value);
      }
      break;
    case YP_NODE_NEXT_NODE:
      if (((yp_next_node_t *)node)->arguments != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_next_node_t *)node)->arguments);
      }
      break;
    case YP_NODE_NIL_NODE:
      break;
    case YP_NODE_NO_KEYWORDS_PARAMETER_NODE:
      break;
    case YP_NODE_OPERATOR_AND_ASSIGNMENT_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_operator_and_assignment_node_t *)node)->target);
      yp_node_destroy(parser, (yp_node_t *)((yp_operator_and_assignment_node_t *)node)->value);
      break;
    case YP_NODE_OPERATOR_ASSIGNMENT_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_operator_assignment_node_t *)node)->target);
      yp_node_destroy(parser, (yp_node_t *)((yp_operator_assignment_node_t *)node)->value);
      break;
    case YP_NODE_OPERATOR_OR_ASSIGNMENT_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_operator_or_assignment_node_t *)node)->target);
      yp_node_destroy(parser, (yp_node_t *)((yp_operator_or_assignment_node_t *)node)->value);
      break;
    case YP_NODE_OPTIONAL_PARAMETER_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_optional_parameter_node_t *)node)->value);
      break;
    case YP_NODE_OR_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_or_node_t *)node)->left);
      yp_node_destroy(parser, (yp_node_t *)((yp_or_node_t *)node)->right);
      break;
    case YP_NODE_PARAMETERS_NODE:
      yp_node_list_free(parser, &((yp_parameters_node_t *)node)->requireds);
      yp_node_list_free(parser, &((yp_parameters_node_t *)node)->optionals);
      if (((yp_parameters_node_t *)node)->rest != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_parameters_node_t *)node)->rest);
      }
      yp_node_list_free(parser, &((yp_parameters_node_t *)node)->keywords);
      if (((yp_parameters_node_t *)node)->keyword_rest != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_parameters_node_t *)node)->keyword_rest);
      }
      if (((yp_parameters_node_t *)node)->block != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_parameters_node_t *)node)->block);
      }
      break;
    case YP_NODE_PARENTHESES_NODE:
      if (((yp_parentheses_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_parentheses_node_t *)node)->statements);
      }
      break;
    case YP_NODE_PINNED_EXPRESSION_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_pinned_expression_node_t *)node)->expression);
      break;
    case YP_NODE_PINNED_VARIABLE_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_pinned_variable_node_t *)node)->variable);
      break;
    case YP_NODE_POST_EXECUTION_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_post_execution_node_t *)node)->statements);
      break;
    case YP_NODE_PRE_EXECUTION_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_pre_execution_node_t *)node)->statements);
      break;
    case YP_NODE_PROGRAM_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_program_node_t *)node)->scope);
      yp_node_destroy(parser, (yp_node_t *)((yp_program_node_t *)node)->statements);
      break;
    case YP_NODE_RANGE_NODE:
      if (((yp_range_node_t *)node)->left != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_range_node_t *)node)->left);
      }
      if (((yp_range_node_t *)node)->right != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_range_node_t *)node)->right);
      }
      break;
    case YP_NODE_RATIONAL_NODE:
      break;
    case YP_NODE_REDO_NODE:
      break;
    case YP_NODE_REGULAR_EXPRESSION_NODE:
      yp_string_free(&((yp_regular_expression_node_t *)node)->unescaped);
      break;
    case YP_NODE_REQUIRED_DESTRUCTURED_PARAMETER_NODE:
      yp_node_list_free(parser, &((yp_required_destructured_parameter_node_t *)node)->parameters);
      break;
    case YP_NODE_REQUIRED_PARAMETER_NODE:
      break;
    case YP_NODE_RESCUE_MODIFIER_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_rescue_modifier_node_t *)node)->expression);
      yp_node_destroy(parser, (yp_node_t *)((yp_rescue_modifier_node_t *)node)->rescue_expression);
      break;
    case YP_NODE_RESCUE_NODE:
      yp_node_list_free(parser, &((yp_rescue_node_t *)node)->exceptions);
      if (((yp_rescue_node_t *)node)->exception != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_rescue_node_t *)node)->exception);
      }
      if (((yp_rescue_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_rescue_node_t *)node)->statements);
      }
      if (((yp_rescue_node_t *)node)->consequent != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_rescue_node_t *)node)->consequent);
      }
      break;
    case YP_NODE_REST_PARAMETER_NODE:
      break;
    case YP_NODE_RETRY_NODE:
      break;
    case YP_NODE_RETURN_NODE:
      if (((yp_return_node_t *)node)->arguments != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_return_node_t *)node)->arguments);
      }
      break;
    case YP_NODE_SCOPE_NODE:
      yp_token_list_free(&((yp_scope_node_t *)node)->locals);
      break;
    case YP_NODE_SELF_NODE:
      break;
    case YP_NODE_SINGLETON_CLASS_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_singleton_class_node_t *)node)->scope);
      yp_node_destroy(parser, (yp_node_t *)((yp_singleton_class_node_t *)node)->expression);
      if (((yp_singleton_class_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_singleton_class_node_t *)node)->statements);
      }
      break;
    case YP_NODE_SOURCE_ENCODING_NODE:
      break;
    case YP_NODE_SOURCE_FILE_NODE:
      break;
    case YP_NODE_SOURCE_LINE_NODE:
      break;
    case YP_NODE_SPLAT_NODE:
      if (((yp_splat_node_t *)node)->expression != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_splat_node_t *)node)->expression);
      }
      break;
    case YP_NODE_STATEMENTS_NODE:
      yp_node_list_free(parser, &((yp_statements_node_t *)node)->body);
      break;
    case YP_NODE_STRING_CONCAT_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_string_concat_node_t *)node)->left);
      yp_node_destroy(parser, (yp_node_t *)((yp_string_concat_node_t *)node)->right);
      break;
    case YP_NODE_STRING_INTERPOLATED_NODE:
      if (((yp_string_interpolated_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_string_interpolated_node_t *)node)->statements);
      }
      break;
    case YP_NODE_STRING_NODE:
      yp_string_free(&((yp_string_node_t *)node)->unescaped);
      break;
    case YP_NODE_SUPER_NODE:
      if (((yp_super_node_t *)node)->arguments != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_super_node_t *)node)->arguments);
      }
      if (((yp_super_node_t *)node)->block != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_super_node_t *)node)->block);
      }
      break;
    case YP_NODE_SYMBOL_NODE:
      yp_string_free(&((yp_symbol_node_t *)node)->unescaped);
      break;
    case YP_NODE_TRUE_NODE:
      break;
    case YP_NODE_UNDEF_NODE:
      yp_node_list_free(parser, &((yp_undef_node_t *)node)->names);
      break;
    case YP_NODE_UNLESS_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_unless_node_t *)node)->predicate);
      if (((yp_unless_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_unless_node_t *)node)->statements);
      }
      if (((yp_unless_node_t *)node)->consequent != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_unless_node_t *)node)->consequent);
      }
      break;
    case YP_NODE_UNTIL_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_until_node_t *)node)->predicate);
      if (((yp_until_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_until_node_t *)node)->statements);
      }
      break;
    case YP_NODE_WHEN_NODE:
      yp_node_list_free(parser, &((yp_when_node_t *)node)->conditions);
      if (((yp_when_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_when_node_t *)node)->statements);
      }
      break;
    case YP_NODE_WHILE_NODE:
      yp_node_destroy(parser, (yp_node_t *)((yp_while_node_t *)node)->predicate);
      if (((yp_while_node_t *)node)->statements != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_while_node_t *)node)->statements);
      }
      break;
    case YP_NODE_X_STRING_NODE:
      yp_string_free(&((yp_x_string_node_t *)node)->unescaped);
      break;
    case YP_NODE_YIELD_NODE:
      if (((yp_yield_node_t *)node)->arguments != NULL) {
        yp_node_destroy(parser, (yp_node_t *)((yp_yield_node_t *)node)->arguments);
      }
      break;
    default:
      assert(false && "unreachable");
      break;
  }
  free(node);
}

static void
yp_node_memsize_node(yp_node_t *node, yp_memsize_t *memsize) {
  memsize->node_count++;

  switch (node->type) {
    case YP_NODE_ARRAY_PATTERN_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (node->as.array_pattern_node.constant != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.array_pattern_node.constant, memsize);
      }
      yp_node_list_memsize(&node->as.array_pattern_node.requireds, memsize);
      if (node->as.array_pattern_node.rest != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.array_pattern_node.rest, memsize);
      }
      yp_node_list_memsize(&node->as.array_pattern_node.posts, memsize);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_AS_PATTERN_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)node->as.as_pattern_node.value, memsize);
      yp_node_memsize_node((yp_node_t *)node->as.as_pattern_node.target, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_ASSOC_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)node->as.assoc_node.key, memsize);
      if (node->as.assoc_node.value != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.assoc_node.value, memsize);
      }
      break;
    }
    case YP_NODE_ASSOC_SPLAT_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (node->as.assoc_splat_node.value != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.assoc_splat_node.value, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_CALL_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (node->as.call_node.receiver != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.call_node.receiver, memsize);
      }
      if (node->as.call_node.arguments != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.call_node.arguments, memsize);
      }
      if (node->as.call_node.block != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.call_node.block, memsize);
      }
      memsize->memsize += yp_string_memsize(&node->as.call_node.name);
      break;
    }
    case YP_NODE_CLASS_VARIABLE_READ_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_CLASS_VARIABLE_WRITE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      memsize->memsize += sizeof(yp_location_t);
      if (node->as.class_variable_write_node.value != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.class_variable_write_node.value, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_CONSTANT_PATH_WRITE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)node->as.constant_path_write_node.target, memsize);
      if (node->as.constant_path_write_node.value != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.constant_path_write_node.value, memsize);
      }
      break;
    }
    case YP_NODE_CONSTANT_READ_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_FIND_PATTERN_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (node->as.find_pattern_node.constant != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.find_pattern_node.constant, memsize);
      }
      yp_node_memsize_node((yp_node_t *)node->as.find_pattern_node.left, memsize);
      yp_node_list_memsize(&node->as.find_pattern_node.requireds, memsize);
      yp_node_memsize_node((yp_node_t *)node->as.find_pattern_node.right, memsize);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_GLOBAL_VARIABLE_READ_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_GLOBAL_VARIABLE_WRITE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (node->as.global_variable_write_node.value != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.global_variable_write_node.value, memsize);
      }
      break;
    }
    case YP_NODE_HASH_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&node->as.hash_node.elements, memsize);
      break;
    }
    case YP_NODE_HASH_PATTERN_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (node->as.hash_pattern_node.constant != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.hash_pattern_node.constant, memsize);
      }
      yp_node_list_memsize(&node->as.hash_pattern_node.assocs, memsize);
      if (node->as.hash_pattern_node.kwrest != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.hash_pattern_node.kwrest, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_HEREDOC_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&node->as.heredoc_node.parts, memsize);
      memsize->memsize += sizeof(int);
      break;
    }
    case YP_NODE_IF_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)node->as.if_node.predicate, memsize);
      if (node->as.if_node.statements != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.if_node.statements, memsize);
      }
      if (node->as.if_node.consequent != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.if_node.consequent, memsize);
      }
      break;
    }
    case YP_NODE_IMAGINARY_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_IN_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)node->as.in_node.pattern, memsize);
      if (node->as.in_node.statements != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.in_node.statements, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_INSTANCE_VARIABLE_READ_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_INSTANCE_VARIABLE_WRITE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      memsize->memsize += sizeof(yp_location_t);
      if (node->as.instance_variable_write_node.value != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.instance_variable_write_node.value, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_INTEGER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_INTERPOLATED_REGULAR_EXPRESSION_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&node->as.interpolated_regular_expression_node.parts, memsize);
      break;
    }
    case YP_NODE_INTERPOLATED_STRING_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&node->as.interpolated_string_node.parts, memsize);
      break;
    }
    case YP_NODE_INTERPOLATED_SYMBOL_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&node->as.interpolated_symbol_node.parts, memsize);
      break;
    }
    case YP_NODE_INTERPOLATED_X_STRING_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&node->as.interpolated_x_string_node.parts, memsize);
      break;
    }
    case YP_NODE_KEYWORD_PARAMETER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (node->as.keyword_parameter_node.value != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.keyword_parameter_node.value, memsize);
      }
      break;
    }
    case YP_NODE_KEYWORD_REST_PARAMETER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_LAMBDA_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)node->as.lambda_node.scope, memsize);
      if (node->as.lambda_node.parameters != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.lambda_node.parameters, memsize);
      }
      if (node->as.lambda_node.statements != NULL) {
        yp_node_memsize_node((yp_node_t *)node->as.lambda_node.statements, memsize);
      }
      break;
    }
    case YP_NODE_ALIAS_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_alias_node_t *)node)->new_name, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_alias_node_t *)node)->old_name, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_ALTERNATION_PATTERN_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_alternation_pattern_node_t *)node)->left, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_alternation_pattern_node_t *)node)->right, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_AND_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_and_node_t *)node)->left, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_and_node_t *)node)->right, memsize);
      break;
    }
    case YP_NODE_ARGUMENTS_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&((yp_arguments_node_t *)node)->arguments, memsize);
      break;
    }
    case YP_NODE_ARRAY_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&((yp_array_node_t *)node)->elements, memsize);
      break;
    }
    case YP_NODE_BEGIN_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_begin_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_begin_node_t *)node)->statements, memsize);
      }
      if (((yp_begin_node_t *)node)->rescue_clause != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_begin_node_t *)node)->rescue_clause, memsize);
      }
      if (((yp_begin_node_t *)node)->else_clause != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_begin_node_t *)node)->else_clause, memsize);
      }
      if (((yp_begin_node_t *)node)->ensure_clause != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_begin_node_t *)node)->ensure_clause, memsize);
      }
      break;
    }
    case YP_NODE_BLOCK_ARGUMENT_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_block_argument_node_t *)node)->expression != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_block_argument_node_t *)node)->expression, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_BLOCK_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_block_node_t *)node)->scope, memsize);
      if (((yp_block_node_t *)node)->parameters != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_block_node_t *)node)->parameters, memsize);
      }
      if (((yp_block_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_block_node_t *)node)->statements, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_BLOCK_PARAMETER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_BLOCK_PARAMETERS_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_block_parameters_node_t *)node)->parameters != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_block_parameters_node_t *)node)->parameters, memsize);
      }
      memsize->memsize += yp_token_list_memsize(&((yp_block_parameters_node_t *)node)->locals);
      break;
    }
    case YP_NODE_BREAK_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_break_node_t *)node)->arguments != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_break_node_t *)node)->arguments, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_CASE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_case_node_t *)node)->predicate != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_case_node_t *)node)->predicate, memsize);
      }
      yp_node_list_memsize(&((yp_case_node_t *)node)->conditions, memsize);
      if (((yp_case_node_t *)node)->consequent != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_case_node_t *)node)->consequent, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_CLASS_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_class_node_t *)node)->scope, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_class_node_t *)node)->constant_path, memsize);
      if (((yp_class_node_t *)node)->superclass != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_class_node_t *)node)->superclass, memsize);
      }
      if (((yp_class_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_class_node_t *)node)->statements, memsize);
      }
      break;
    }
    case YP_NODE_CONSTANT_PATH_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_constant_path_node_t *)node)->parent != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_constant_path_node_t *)node)->parent, memsize);
      }
      yp_node_memsize_node((yp_node_t *)((yp_constant_path_node_t *)node)->child, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_DEF_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_def_node_t *)node)->receiver != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_def_node_t *)node)->receiver, memsize);
      }
      if (((yp_def_node_t *)node)->parameters != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_def_node_t *)node)->parameters, memsize);
      }
      if (((yp_def_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_def_node_t *)node)->statements, memsize);
      }
      yp_node_memsize_node((yp_node_t *)((yp_def_node_t *)node)->scope, memsize);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_DEFINED_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_defined_node_t *)node)->value, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_ELSE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_else_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_else_node_t *)node)->statements, memsize);
      }
      break;
    }
    case YP_NODE_ENSURE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_ensure_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_ensure_node_t *)node)->statements, memsize);
      }
      break;
    }
    case YP_NODE_FALSE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_FLOAT_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_FOR_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_for_node_t *)node)->index, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_for_node_t *)node)->collection, memsize);
      if (((yp_for_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_for_node_t *)node)->statements, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_FORWARDING_ARGUMENTS_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_FORWARDING_PARAMETER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_FORWARDING_SUPER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_forwarding_super_node_t *)node)->block != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_forwarding_super_node_t *)node)->block, memsize);
      }
      break;
    }
    case YP_NODE_LOCAL_VARIABLE_READ_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_LOCAL_VARIABLE_WRITE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      memsize->memsize += sizeof(yp_location_t);
      if (((yp_local_variable_write_node_t *)node)->value != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_local_variable_write_node_t *)node)->value, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_MATCH_PREDICATE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_match_predicate_node_t *)node)->value, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_match_predicate_node_t *)node)->pattern, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_MATCH_REQUIRED_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_match_required_node_t *)node)->value, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_match_required_node_t *)node)->pattern, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_MISSING_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_MODULE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_module_node_t *)node)->scope, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_module_node_t *)node)->constant_path, memsize);
      if (((yp_module_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_module_node_t *)node)->statements, memsize);
      }
      break;
    }
    case YP_NODE_MULTI_WRITE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&((yp_multi_write_node_t *)node)->targets, memsize);
      if (((yp_multi_write_node_t *)node)->value != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_multi_write_node_t *)node)->value, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_NEXT_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_next_node_t *)node)->arguments != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_next_node_t *)node)->arguments, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_NIL_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_NO_KEYWORDS_PARAMETER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_OPERATOR_AND_ASSIGNMENT_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_operator_and_assignment_node_t *)node)->target, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_operator_and_assignment_node_t *)node)->value, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_OPERATOR_ASSIGNMENT_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_operator_assignment_node_t *)node)->target, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_operator_assignment_node_t *)node)->value, memsize);
      break;
    }
    case YP_NODE_OPERATOR_OR_ASSIGNMENT_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_operator_or_assignment_node_t *)node)->target, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_operator_or_assignment_node_t *)node)->value, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_OPTIONAL_PARAMETER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_optional_parameter_node_t *)node)->value, memsize);
      break;
    }
    case YP_NODE_OR_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_or_node_t *)node)->left, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_or_node_t *)node)->right, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_PARAMETERS_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&((yp_parameters_node_t *)node)->requireds, memsize);
      yp_node_list_memsize(&((yp_parameters_node_t *)node)->optionals, memsize);
      if (((yp_parameters_node_t *)node)->rest != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_parameters_node_t *)node)->rest, memsize);
      }
      yp_node_list_memsize(&((yp_parameters_node_t *)node)->keywords, memsize);
      if (((yp_parameters_node_t *)node)->keyword_rest != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_parameters_node_t *)node)->keyword_rest, memsize);
      }
      if (((yp_parameters_node_t *)node)->block != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_parameters_node_t *)node)->block, memsize);
      }
      break;
    }
    case YP_NODE_PARENTHESES_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_parentheses_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_parentheses_node_t *)node)->statements, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_PINNED_EXPRESSION_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_pinned_expression_node_t *)node)->expression, memsize);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_PINNED_VARIABLE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_pinned_variable_node_t *)node)->variable, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_POST_EXECUTION_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_post_execution_node_t *)node)->statements, memsize);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_PRE_EXECUTION_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_pre_execution_node_t *)node)->statements, memsize);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_PROGRAM_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_program_node_t *)node)->scope, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_program_node_t *)node)->statements, memsize);
      break;
    }
    case YP_NODE_RANGE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_range_node_t *)node)->left != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_range_node_t *)node)->left, memsize);
      }
      if (((yp_range_node_t *)node)->right != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_range_node_t *)node)->right, memsize);
      }
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_RATIONAL_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_REDO_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_REGULAR_EXPRESSION_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      memsize->memsize += yp_string_memsize(&((yp_regular_expression_node_t *)node)->unescaped);
      break;
    }
    case YP_NODE_REQUIRED_DESTRUCTURED_PARAMETER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&((yp_required_destructured_parameter_node_t *)node)->parameters, memsize);
      break;
    }
    case YP_NODE_REQUIRED_PARAMETER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_RESCUE_MODIFIER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_rescue_modifier_node_t *)node)->expression, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_rescue_modifier_node_t *)node)->rescue_expression, memsize);
      break;
    }
    case YP_NODE_RESCUE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&((yp_rescue_node_t *)node)->exceptions, memsize);
      if (((yp_rescue_node_t *)node)->exception != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_rescue_node_t *)node)->exception, memsize);
      }
      if (((yp_rescue_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_rescue_node_t *)node)->statements, memsize);
      }
      if (((yp_rescue_node_t *)node)->consequent != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_rescue_node_t *)node)->consequent, memsize);
      }
      break;
    }
    case YP_NODE_REST_PARAMETER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_RETRY_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_RETURN_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_return_node_t *)node)->arguments != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_return_node_t *)node)->arguments, memsize);
      }
      break;
    }
    case YP_NODE_SCOPE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      memsize->memsize += yp_token_list_memsize(&((yp_scope_node_t *)node)->locals);
      break;
    }
    case YP_NODE_SELF_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_SINGLETON_CLASS_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_singleton_class_node_t *)node)->scope, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_singleton_class_node_t *)node)->expression, memsize);
      if (((yp_singleton_class_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_singleton_class_node_t *)node)->statements, memsize);
      }
      break;
    }
    case YP_NODE_SOURCE_ENCODING_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_SOURCE_FILE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_SOURCE_LINE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_SPLAT_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_splat_node_t *)node)->expression != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_splat_node_t *)node)->expression, memsize);
      }
      break;
    }
    case YP_NODE_STATEMENTS_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&((yp_statements_node_t *)node)->body, memsize);
      break;
    }
    case YP_NODE_STRING_CONCAT_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_string_concat_node_t *)node)->left, memsize);
      yp_node_memsize_node((yp_node_t *)((yp_string_concat_node_t *)node)->right, memsize);
      break;
    }
    case YP_NODE_STRING_INTERPOLATED_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_string_interpolated_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_string_interpolated_node_t *)node)->statements, memsize);
      }
      break;
    }
    case YP_NODE_STRING_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      memsize->memsize += yp_string_memsize(&((yp_string_node_t *)node)->unescaped);
      break;
    }
    case YP_NODE_SUPER_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_super_node_t *)node)->arguments != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_super_node_t *)node)->arguments, memsize);
      }
      if (((yp_super_node_t *)node)->block != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_super_node_t *)node)->block, memsize);
      }
      break;
    }
    case YP_NODE_SYMBOL_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      memsize->memsize += yp_string_memsize(&((yp_symbol_node_t *)node)->unescaped);
      break;
    }
    case YP_NODE_TRUE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      break;
    }
    case YP_NODE_UNDEF_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&((yp_undef_node_t *)node)->names, memsize);
      memsize->memsize += sizeof(yp_location_t);
      break;
    }
    case YP_NODE_UNLESS_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_unless_node_t *)node)->predicate, memsize);
      if (((yp_unless_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_unless_node_t *)node)->statements, memsize);
      }
      if (((yp_unless_node_t *)node)->consequent != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_unless_node_t *)node)->consequent, memsize);
      }
      break;
    }
    case YP_NODE_UNTIL_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_until_node_t *)node)->predicate, memsize);
      if (((yp_until_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_until_node_t *)node)->statements, memsize);
      }
      break;
    }
    case YP_NODE_WHEN_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_list_memsize(&((yp_when_node_t *)node)->conditions, memsize);
      if (((yp_when_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_when_node_t *)node)->statements, memsize);
      }
      break;
    }
    case YP_NODE_WHILE_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      yp_node_memsize_node((yp_node_t *)((yp_while_node_t *)node)->predicate, memsize);
      if (((yp_while_node_t *)node)->statements != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_while_node_t *)node)->statements, memsize);
      }
      break;
    }
    case YP_NODE_X_STRING_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      memsize->memsize += yp_string_memsize(&((yp_x_string_node_t *)node)->unescaped);
      break;
    }
    case YP_NODE_YIELD_NODE: {
      memsize->memsize += sizeof(yp_node_t);
      if (((yp_yield_node_t *)node)->arguments != NULL) {
        yp_node_memsize_node((yp_node_t *)((yp_yield_node_t *)node)->arguments, memsize);
      }
      break;
    }
  }
}

// Calculates the memory footprint of a given node.
__attribute__((__visibility__("default"))) extern void
yp_node_memsize(yp_node_t *node, yp_memsize_t *memsize) {
  *memsize = (yp_memsize_t) { .memsize = 0, .node_count = 0 };
  yp_node_memsize_node(node, memsize);
}
