name: Java WASM bindings

on:
  push:
    paths:
      - ".github/workflows/java-wasm-bindings.yml"
      - "include/"
      - "src/"
      - "*akefile*"
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
          bundler-cache: true

      - name: rake templates
        run: PRISM_EXCLUDE_PRETTYPRINT=1 PRISM_SERIALIZE_ONLY_SEMANTICS_FIELDS=1 bundle exec rake templates

      - name: Set up WASI-SDK
        run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-25/wasi-sdk-25.0-x86_64-linux.tar.gz
          tar xvf wasi-sdk-25.0-x86_64-linux.tar.gz

      - name: Build the project
        run: make java-wasm WASI_SDK_PATH=$(pwd)/wasi-sdk-25.0-x86_64-linux

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Run the tests
        run: mvn -B install
        working-directory: java-wasm

      - uses: actions/upload-artifact@v5
        with:
          name: prism.wasm
          path: java-wasm/src/test/resources/prism.wasm
