name: JavaScript bindings

on:
  push:
    paths:
      - ".github/workflows/javascript-bindings.yml"
      - "include/"
      - "src/"
      - "*akefile*"
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
          bundler-cache: true

      - name: rake templates
        run: bundle exec rake templates

      - name: Set up WASI-SDK
        run: |
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-25/wasi-sdk-25.0-x86_64-linux.tar.gz
          tar xvf wasi-sdk-25.0-x86_64-linux.tar.gz

      - name: Build the project
        run: make wasm WASI_SDK_PATH=$(pwd)/wasi-sdk-25.0-x86_64-linux

      - uses: actions/upload-artifact@v5
        with:
          name: prism.wasm
          path: javascript/src/prism.wasm

      - uses: actions/setup-node@v6
        with:
          node-version: 20.x

      - name: Run the tests
        run: npm test
        working-directory: javascript
