name: Main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.4"
        bundler-cache: true
    - name: Lint
      run: bundle exec rake lint

  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-latest
          # - ubuntu-24.04-arm
          # - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: head
    
    - run: cat D:/rubyinstaller-head-x64/lib/ruby/3.5.0+4/win32/resolv.rb
    
    - run: bundle install
    - name: Run Ruby tests
      run: bundle exec rake
      shell: bash
