name: Windows

concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  push:
    #branches:
    #  - main
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ucrt
        bundler-cache: true
    - name: build
      id: build
      run: bundle exec rake compile
      continue-on-error: true
      if: success()
    - name: >-
        Build outcome: ${{ steps.build.outcome }}
      # every step must define a `uses` or `run` key
      run: echo NOOP

    #- name: test
    #  run: bundle exec rake test

